'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,Lock,MessageCircle,School,Send,Unlock,Users} from 'lucide-react';
import {onAuthStateChanged} from 'firebase/auth';
import {addDoc,collection,doc,getDoc,limit,onSnapshot,orderBy,query,serverTimestamp,updateDoc,where} from 'firebase/firestore';
import {auth,db} from '@/lib/firebase';
const BASE='/eduwills';
const active=(d:any)=>d?.activationStatus==='active'||d?.activated===true||d?.williTokenActive===true||d?.activationActive===true||d?.isActive===true;
export default function Schools(){
 const[user,setUser]=useState<any>(null),[profile,setProfile]=useState<any>({}),[schools,setSchools]=useState<any[]>([]),[school,setSchool]=useState<any>(null),[messages,setMessages]=useState<any[]>([]),[draft,setDraft]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>onAuthStateChanged(auth,async u=>{if(!u){location.replace(BASE+'/login/');return}const s=await getDoc(doc(db,'users',u.uid));const p=s.data()||{};if(!active(p)){location.replace(BASE+'/dashboard/activation/');return}setUser(u);setProfile(p);setLoading(false)}),[]);
 useEffect(()=>{if(!user)return;return onSnapshot(query(collection(db,'schoolCommunities'),where('memberIds','array-contains',user.uid),limit(100)),s=>setSchools(s.docs.map(x=>({id:x.id,...x.data()}))))},[user?.uid]);
 useEffect(()=>{if(!school||!user)return;return onSnapshot(query(collection(db,'schoolCommunities',school.id,'messages'),orderBy('createdAt','asc'),limit(300)),s=>setMessages(s.docs.map(x=>({id:x.id,...x.data()}))))},[school?.id,user?.uid]);
 const isAdmin=!!school?.adminIds?.includes(user?.uid); const locked=school?.messagingLocked===true;
 async function toggle(){if(!isAdmin)return;try{await updateDoc(doc(db,'schoolCommunities',school.id),{messagingLocked:!locked,updatedAt:serverTimestamp()});setNotice(!locked?'Sending is locked for this school.':'Sending is unlocked for this school.')}catch(e:any){setNotice(e?.message||'Could not change school message lock.')}}
 async function send(){if(!draft.trim()||locked||!school||!user)return;const text=draft.trim();setDraft('');try{await addDoc(collection(db,'schoolCommunities',school.id,'messages'),{senderId:user.uid,senderName:profile.fullName||'Learner',senderUsername:profile.username||'',text,createdAt:serverTimestamp()})}catch(e:any){setDraft(text);setNotice(e?.message||'Message could not be sent.')}}
 if(loading)return <main className="grid min-h-screen place-items-center bg-paper font-bold text-slate-500">Loading school communities…</main>;
 if(!school)return <main className="min-h-screen bg-paper p-5 text-ink"><a href={BASE+'/dashboard/community/'} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-3 text-sm font-black"><ArrowLeft size={17}/> Community</a><div className="mx-auto max-w-4xl pt-8"><section className="rounded-[2rem] bg-ink p-7 text-white"><School className="text-cyan-300" size={34}/><h1 className="mt-3 text-3xl font-black">School Communities</h1><p className="mt-2 text-sm leading-6 text-slate-300">Your verified school communities appear here. School admins can lock or unlock member message sending.</p></section>{notice&&<p className="mt-4 rounded-2xl bg-cyan-50 p-4 text-sm font-bold">{notice}</p>}<div className="mt-5 grid gap-3">{schools.length?schools.map(s=><button key={s.id} onClick={()=>setSchool(s)} className="rounded-2xl border bg-white p-5 text-left shadow-sm"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-xl bg-cyan-50 text-cyan-700"><School size={22}/></div><div className="min-w-0 flex-1"><b className="block truncate">{s.name||s.schoolName||'School community'}</b><span className="text-xs text-slate-400">{Array.isArray(s.memberIds)?s.memberIds.length:0} members</span></div></div></button>):<div className="rounded-3xl border border-dashed bg-white p-10 text-center"><Users className="mx-auto text-slate-300" size={38}/><p className="mt-3 font-black">No school community yet</p><p className="mt-1 text-xs leading-5 text-slate-400">Once a verified school community is active and you are a member, it will appear here.</p></div>}</div></div></main>;
 return <main className="min-h-screen bg-[#eef3f7] text-ink"><header className="sticky top-0 z-40 border-b bg-white/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-5xl items-center gap-3 px-4"><button onClick={()=>setSchool(null)} className="grid h-10 w-10 place-items-center rounded-full hover:bg-slate-100"><ArrowLeft size={20}/></button><div className="min-w-0 flex-1"><p className="text-[10px] font-black uppercase tracking-wider text-cyan-700">SCHOOL COMMUNITY</p><h1 className="truncate font-black">{school.name||school.schoolName||'School community'}</h1></div>{isAdmin&&<button onClick={toggle} className="inline-flex items-center gap-2 rounded-xl bg-ink px-3 py-2 text-[10px] font-black text-white">{locked?<Unlock size={14}/>:<Lock size={14}/>} {locked?'UNLOCK':'LOCK'} SENDING</button>}</div></header><div className="mx-auto max-w-5xl p-3 sm:p-5">{notice&&<div className="mb-3 rounded-2xl bg-cyan-50 p-4 text-xs font-bold">{notice}</div>}{locked&&<div className="mb-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-xs font-black text-amber-900">Sending is locked by a school admin. Members can still read the conversation.</div>}<section className="rounded-3xl border bg-white shadow-sm"><div className="h-[62vh] min-h-[360px] space-y-3 overflow-y-auto p-4">{messages.length?messages.map(m=><div key={m.id} className={'flex '+(m.senderId===user.uid?'justify-end':'')}><div className={'max-w-[82%] rounded-2xl px-4 py-2.5 '+(m.senderId===user.uid?'bg-ink text-white':'bg-slate-50 border')}><p className="text-[10px] font-black opacity-60">{m.senderName||m.senderUsername||'Learner'}</p><p className="mt-1 whitespace-pre-wrap text-sm leading-6">{m.text}</p></div></div>):<div className="grid h-full place-items-center text-center"><MessageCircle className="mx-auto text-slate-300" size={38}/><p className="mt-3 font-black">No messages yet</p></div>}</div><div className="flex gap-2 border-t p-3"><textarea value={draft} onChange={e=>setDraft(e.target.value)} disabled={locked} placeholder={locked?'Sending is locked by an admin':'Write a message…'} className="min-h-11 flex-1 resize-none rounded-2xl border bg-slate-50 px-4 py-3 text-sm font-semibold outline-none disabled:opacity-60"/><button onClick={send} disabled={locked||!draft.trim()} className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-ink text-white disabled:opacity-30"><Send size={17}/></button></div></section></div></main>;
}
