import {NextRequest,NextResponse} from 'next/server';

type Source={title:string;text:string};
type Book={title:string;author:string};
type Question={question:string;options:string[];answer:number;explanation?:string};
const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
const fingerprint=(s:string)=>normalize(s).replace(/\b(the|a|an|what|which|who|how|why|did|does|is|was|were|of|in|on|to|and|for|from)\b/g,'').replace(/\s+/g,' ').trim();
const similar=(a:string,b:string)=>{const x=new Set(fingerprint(a).split(' ').filter(Boolean)),y=new Set(fingerprint(b).split(' ').filter(Boolean));if(!x.size||!y.size)return false;return [...x].filter(v=>y.has(v)).length/Math.max(1,Math.min(x.size,y.size))>=0.82};
function parseQuestions(text:string):Question[]{const c=text.replace(/^```(?:json)?/i,'').replace(/```$/,'').trim(),a=c.indexOf('['),b=c.lastIndexOf(']');if(a<0||b<=a)throw new Error('AI did not return JSON');const p=JSON.parse(c.slice(a,b+1));if(!Array.isArray(p))throw new Error('Invalid questions');return p.map((q:any)=>({question:String(q.question||'').trim(),options:Array.isArray(q.options)?q.options.slice(0,4).map(String):[],answer:Number(q.answer),explanation:q.explanation?String(q.explanation):''})).filter((q:Question)=>q.question&&q.options.length===4&&Number.isInteger(q.answer)&&q.answer>=0&&q.answer<4)}
async function json(url:string){const r=await fetch(url,{cache:'no-store',headers:{Accept:'application/json'}});if(!r.ok)throw new Error(String(r.status));return r.json()}
async function researchBook(book:Book):Promise<Source[]>{const out:Source[]=[];const add=(title:string,text:any)=>{if(text)out.push({title,text:String(text).slice(0,7000)})};try{const d=await json(`https://www.googleapis.com/books/v1/volumes?q=intitle:${encodeURIComponent(book.title)}+inauthor:${encodeURIComponent(book.author)}&maxResults=40`);for(const x of d.items||[]){const v=x.volumeInfo||{};add(v.title||book.title,v.description);if(v.categories)add(`${v.title||book.title} categories`,v.categories.join(', '));}}catch{}try{const d=await json(`https://openlibrary.org/search.json?title=${encodeURIComponent(book.title)}&author=${encodeURIComponent(book.author)}&limit=50`);for(const x of d.docs||[]){add(x.title||book.title,(x.first_sentence||[]).join(' '));if(x.subject)add(`${x.title||book.title} subjects`,(x.subject||[]).slice(0,120).join(', '));}}catch{}try{const d=await json(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(book.title.replace(/ /g,'_'))}`);add(d.title||book.title,d.extract)}catch{}return out}
export async function POST(req:NextRequest){try{const body=await req.json(),books:Array<Book>=Array.isArray(body.books)?body.books:[],requested=Math.min(100,Math.max(1,Number(body.questions)||10)),difficulty=String(body.difficulty||'Mixed'),instructions=String(body.instructions||'').slice(0,100),previous:Array<string>=Array.isArray(body.previousQuestions)?body.previousQuestions.map(String).slice(-300):[];if(!books.length)return NextResponse.json({error:'At least one book is required.'},{status:400});const sources=(await Promise.all(books.map(researchBook))).flat(),context=sources.map(s=>`SOURCE: ${s.title}\n${s.text}`).join('\n\n').slice(0,50000),accepted:Question[]=[],seen=new Set(previous.map(fingerprint).filter(Boolean));for(let round=0;round<8&&accepted.length<requested;round++){const need=requested-accepted.length,prompt=`You are EDUWILLS Book Intelligence Quiz AI. Create up to ${Math.min(need+15,40)} NEW multiple-choice questions about ${books.map(b=>`${b.title} by ${b.author}`).join('; ')}. Use only facts supported by the research below. Difficulty: ${difficulty}. User instruction: ${instructions||'None'}. Vary targets across plot/events, characters, relationships, themes, setting, chronology, cause/effect, inference, vocabulary/literary devices and chapter details when supported. Never repeat or paraphrase a prior question. Never invent facts or quotations. Exactly four options and one correct answer. Return ONLY JSON: [{"question":"...","options":["...","...","...","..."],"answer":0,"explanation":"..."}]. PRIOR QUESTIONS: ${[...seen].slice(-300).join(' | ')}\nRESEARCH:\n${context}`;try{const r=await fetch('https://text.pollinations.ai/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:[{role:'user',content:prompt}],model:'openai'})});if(!r.ok)continue;for(const q of parseQuestions(await r.text())){const fp=fingerprint(q.question);if(!fp||seen.has(fp)||accepted.some(x=>similar(x.question,q.question)))continue;seen.add(fp);accepted.push(q);if(accepted.length>=requested)break}}catch{}}return NextResponse.json({questions:accepted,sourcesUsed:sources.length,complete:accepted.length>=requested,notice:accepted.length<requested?'EDUWILLS could not find enough reliable, non-repeating material without inventing facts.':''})}catch(e:any){return NextResponse.json({error:e?.message||'Quiz AI unavailable.'},{status:500})}}