import {NextRequest,NextResponse} from 'next/server';

type Book={title:string;author:string};
type Source={title:string;text:string;url?:string};
type Question={question:string;options:string[];answer:number;explanation?:string};
const clean=(s:any)=>String(s??'').replace(/\s+/g,' ').trim();
const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
const fp=(s:string)=>norm(s).replace(/\b(the|a|an|what|which|who|how|why|did|does|is|was|were|of|in|on|to|and|for|from|about|according)\b/g,'').replace(/\s+/g,' ').trim();
const similar=(a:string,b:string)=>{const x=new Set(fp(a).split(' ').filter(Boolean)),y=new Set(fp(b).split(' ').filter(Boolean));if(!x.size||!y.size)return false;const hit=[...x].filter(v=>y.has(v)).length;return hit/Math.max(1,Math.min(x.size,y.size))>=0.84};
const curated:Record<string,string[]>= {
 'the lekki headmaster':['The Lekki Headmaster was written by Kabir Alabi Garba.','The story follows Bepo Adewale, a dedicated headmaster at Stardom Schools in Lekki, Lagos.','The novel explores education, integrity, service, migration pressure and the japa phenomenon.','Bepo faces pressure to relocate to the United Kingdom but remains committed to his students and school.','The novel was published by Winepress Publishing in 2023.','JAMB selected The Lekki Headmaster as the general reading text for the 2025 and 2026 UTME Use of English.'],
 'sanya':['Sànyà is a Nigerian literary work by Oyin Olugbile.'],
 'scars':['SCARS: Nigeria’s Journey and the Boko Haram Conundrum examines Nigeria’s journey and the Boko Haram conundrum.','SCARS is associated with Gen. Lucky Irabor.']
};
async function json(url:string,ms=5000){const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),ms);try{const r=await fetch(url,{cache:'no-store',headers:{Accept:'application/json'},signal:ctl.signal});if(!r.ok)throw Error(String(r.status));return await r.json()}finally{clearTimeout(t)}}
function add(out:Source[],title:string,text:any,url?:string){const t=clean(text);if(t)out.push({title:clean(title)||'Book source',text:t.slice(0,7000),url})}
async function researchBook(book:Book){const out:Source[]=[];const title=clean(book.title),author=clean(book.author),t=encodeURIComponent(title),a=encodeURIComponent(author),key=norm(title);
 for(const f of curated[key]||[])add(out,'EDUWILLS verified catalogue',f);
 const urls=[
  ['Google Books',`https://www.googleapis.com/books/v1/volumes?q=intitle:${t}+inauthor:${a}&maxResults=40`],
  ['Open Library',`https://openlibrary.org/search.json?title=${t}&author=${a}&limit=50`],
  ['Wikipedia',`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(title.replace(/ /g,'_'))}`],
  ['Wikipedia search',`https://en.wikipedia.org/w/api.php?action=query&format=json&origin=*&prop=extracts&exintro=1&explaintext=1&titles=${t}`],
  ['Wikidata',`https://www.wikidata.org/w/api.php?action=wbsearchentities&search=${encodeURIComponent(title+' '+author)}&language=en&format=json&limit=6&origin=*`],
  ['Internet Archive',`https://archive.org/advancedsearch.php?q=title%3A%22${encodeURIComponent(title)}%22&fl%5B%5D=title&fl%5B%5D=description&fl%5B%5D=creator&rows=10&output=json`]
 ];
 const results=await Promise.allSettled(urls.map(x=>json(x[1],5000)));
 for(let i=0;i<results.length;i++){const r=results[i];if(r.status!=='fulfilled')continue;const d:any=r.value;
  if(i===0)for(const x of d.items||[]){const v=x.volumeInfo||{};add(out,v.title||title,v.description,x.selfLink);if(v.publishedDate)add(out,`${v.title||title} publication`,`Published ${v.publishedDate}. Publisher: ${v.publisher||'unknown'}.`,x.selfLink)}
  if(i===1)for(const x of d.docs||[]){add(out,x.title||title,(x.first_sentence||[]).join(' '),`https://openlibrary.org/works/${String(x.key||'').replace('/works/','')}`);if(x.subject)add(out,`${x.title||title} subjects`,(x.subject||[]).slice(0,100).join(', '))}
  if(i===2)add(out,d.title||title,d.extract,`https://en.wikipedia.org/wiki/${encodeURIComponent(title.replace(/ /g,'_'))}`);
  if(i===3)for(const p of Object.values(d.query?.pages||{}) as any[])add(out,p.title||title,p.extract,`https://en.wikipedia.org/wiki/${encodeURIComponent(String(p.title||title).replace(/ /g,'_'))}`);
  if(i===4)for(const x of d.search||[])add(out,`Wikidata: ${x.label||title}`,`${x.description||''}${x.aliases?.length?' Aliases: '+x.aliases.join(', '):''}`,`https://www.wikidata.org/wiki/${x.id}`);
  if(i===5)for(const x of d.response?.docs||[])add(out,`Internet Archive: ${x.title||title}`,`${x.creator||''} ${x.description||''}`,`https://archive.org/details/${x.identifier||''}`);
 }
 return out;
}
function parse(text:string):Question[]{const c=text.replace(/^```(?:json)?/i,'').replace(/```$/,'').trim(),a=c.indexOf('['),b=c.lastIndexOf(']');if(a<0||b<=a)throw Error('Invalid AI JSON');const p=JSON.parse(c.slice(a,b+1));return(Array.isArray(p)?p:[]).map((q:any)=>({question:clean(q.question),options:Array.isArray(q.options)?q.options.slice(0,4).map(clean):[],answer:Number(q.answer),explanation:clean(q.explanation)})).filter((q:Question)=>q.question&&q.options.length===4&&Number.isInteger(q.answer)&&q.answer>=0&&q.answer<4)}
async function ai(prompt:string){const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),9000);try{const r=await fetch('https://text.pollinations.ai/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:[{role:'user',content:prompt}],model:'openai',temperature:0.85}),signal:ctl.signal});if(!r.ok)throw Error(String(r.status));return parse(await r.text())}finally{clearTimeout(t)}}
function fallback(books:Book[],sources:Source[],count:number,seen:Set<string>){const out:Question[]=[];const facts=[...sources.map(s=>s.text).filter(x=>x.length>35)];const push=(q:Question)=>{const n=fp(q.question);if(!n||seen.has(n)||out.some(x=>fp(x.question)===n))return;seen.add(n);out.push(q)};for(let i=0;i<facts.length&&out.length<count;i++){const b=books[i%books.length],f=facts[i].slice(0,260);push({question:`Which statement is supported by the research about ${b.title}?`,options:[f,'The research gives no information about this title.','The selected author is unrelated to this title.','The research directly contradicts this detail.'],answer:0,explanation:'This answer is directly supported by the verified research gathered for the selected book.'})}for(const b of books){push({question:`Who is the verified author of ${b.title}?`,options:[b.author,'Chinua Achebe','Wole Soyinka','Buchi Emecheta'],answer:0,explanation:'The author comes from the verified saved-book record.'});if(out.length>=count)break}return out.slice(0,count)}
export async function POST(req:NextRequest){try{const body=await req.json(),books:Array<Book>=Array.isArray(body.books)?body.books.filter((b:any)=>clean(b?.title)&&clean(b?.author)).slice(0,5):[],requested=Math.min(100,Math.max(1,Number(body.questions)||10)),difficulty=clean(body.difficulty)||'Mixed',instructions=clean(body.instructions).slice(0,100),previous:Array<string>=Array.isArray(body.previousQuestions)?body.previousQuestions.map(String).slice(-80):[];if(!books.length)return NextResponse.json({error:'At least one book is required.'},{status:400});const sources=(await Promise.all(books.map(researchBook))).flat();const context=sources.map(s=>`SOURCE: ${s.title}\nURL: ${s.url||''}\n${s.text}`).join('\n\n').slice(0,90000);const seen=new Set(previous.map(fp).filter(Boolean)),accepted:Question[]=[];const batchCount=requested<=12?2:requested<=40?3:4;const per=Math.ceil(requested/batchCount)+6;const prompts=Array.from({length:batchCount},(_,i)=>`You are EDUWILLS Book Intelligence AI, generation batch ${i+1}. Create up to ${per} multiple-choice questions for ${books.map(b=>`${b.title} by ${b.author}`).join('; ')}. Use ONLY facts supported by the research. Difficulty: ${difficulty}. ${instructions?'Special instruction: '+instructions+'.':''} Deliberately vary the knowledge areas across batches: characters, relationships, events, chronology, themes, setting, causes/effects, vocabulary, literary devices, inference, factual details and author/publication information where supported. Questions may appear again in a later test after a cooling-off period, but never copy or closely paraphrase the recent questions supplied below. Do not invent quotations, chapters, scenes or facts. Exactly four plausible options and one correct answer. Return ONLY a JSON array. RECENT QUESTIONS: ${previous.join(' | ')}\nRESEARCH:\n${context}`);const batches=await Promise.allSettled(prompts.map(p=>ai(p)));for(const b of batches){if(b.status!=='fulfilled')continue;for(const q of b.value){const n=fp(q.question);if(!n||seen.has(n)||accepted.some(x=>similar(x.question,q.question)))continue;seen.add(n);accepted.push(q);if(accepted.length>=requested)break}if(accepted.length>=requested)break}if(accepted.length<requested)accepted.push(...fallback(books,sources,requested-accepted.length,seen));return NextResponse.json({questions:accepted.slice(0,requested),sourcesUsed:sources.length,complete:accepted.length>=requested,generationMode:accepted.length>=requested?'ai-research':'research-fallback',notice:accepted.length<requested?'Not enough verified material was available to safely create the requested number of unique questions.':''});}catch(e:any){return NextResponse.json({error:e?.message||'Quiz AI unavailable.'},{status:500})}}
