'use client';

import { useState } from 'react';
import { ArrowLeft, KeyRound, ShieldCheck } from 'lucide-react';

export default function AdminSettingsPage() {
  const [current, setCurrent] = useState('');
  const [next, setNext] = useState('');
  const [confirm, setConfirm] = useState('');
  const [message, setMessage] = useState('');
  const save = (e: React.FormEvent) => { e.preventDefault(); const saved = localStorage.getItem('eduwills_admin_password') || 'admin'; if (current !== saved) return setMessage('Current password is incorrect.'); if (!next || next.length < 4) return setMessage('New password must be at least 4 characters.'); if (next !== confirm) return setMessage('New passwords do not match.'); localStorage.setItem('eduwills_admin_password', next); setCurrent(''); setNext(''); setConfirm(''); setMessage('Admin password changed successfully on this browser.'); };
  return <main className="min-h-screen bg-slate-950 px-5 py-8 text-white"><div className="mx-auto max-w-2xl"><a href="/admin" className="inline-flex items-center gap-2 text-sm font-bold text-slate-300"><ArrowLeft size={17}/> Back to Admin</a><div className="mt-10 rounded-[2rem] border border-white/10 bg-white/5 p-7 sm:p-9"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-cyan-400 text-slate-950"><KeyRound size={22}/></div><p className="mt-7 text-xs font-black uppercase tracking-[.2em] text-cyan-200">Admin settings</p><h1 className="mt-2 text-3xl font-black">Change admin password</h1><p className="mt-3 text-sm leading-6 text-slate-400">For this static preview, the changed password is stored in this browser. It will be moved to secure server-side authentication when we add the backend.</p><form onSubmit={save} className="mt-8 space-y-5"><label className="block text-sm font-bold">Current password<input required value={current} onChange={(e) => setCurrent(e.target.value)} type="password" className="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"/></label><label className="block text-sm font-bold">New password<input required value={next} onChange={(e) => setNext(e.target.value)} type="password" className="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"/></label><label className="block text-sm font-bold">Confirm new password<input required value={confirm} onChange={(e) => setConfirm(e.target.value)} type="password" className="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"/></label>{message && <div className="rounded-xl bg-white/5 p-4 text-sm text-cyan-100">{message}</div>}<button className="w-full rounded-xl bg-cyan-400 px-5 py-3.5 font-black text-slate-950">Save new password</button></form><div className="mt-7 flex gap-3 rounded-2xl border border-amber-500/20 bg-amber-500/5 p-4 text-xs leading-5 text-slate-400"><ShieldCheck className="shrink-0 text-amber-200" size={17}/><span><strong className="text-amber-200">Preview security notice:</strong> because GitHub Pages is static, this is not secure authentication yet. We will replace it with a real protected admin account when the backend is added.</span></div></div></div></main>;
}
