'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, BarChart3, Bot, Globe2, RefreshCw, Users, UserPlus, MapPin, CreditCard } from 'lucide-react';
import { collection, getDocs, getDoc, doc } from 'firebase/firestore';
import { onAuthStateChanged } from 'firebase/auth';
import { auth, db } from '@/lib/firebase';

const BASE = '/eduwills';
const OWNER_UID = 'A45uD8Cu27dI0y0iSWla4CZJBhn1';
type Visitor = { visitorId?: string; source?: string; firstSeenAt?: string; language?: string; path?: string; region?: string; timezone?: string };
type Day = { day: string; visitors: number; sources: Record<string, number>; locations: Record<string, number> };
type User = { uid?: string; activated?: boolean; activationStatus?: string; williTokenActive?: boolean; activationExpiresAt?: any };
type WilliToken = { userId?: string; uid?: string; expiresAt?: any; createdAt?: any; durationMs?: number; revoked?: boolean; cancelled?: boolean };
type Funnel = { registrations: number; quizUsers: number; activatedUsers: number; payingUsers: number; revenue: Record<string, number>; chatgptVisitors: number };

function dateKey(offset: number) { const d = new Date(); d.setDate(d.getDate() - offset); return d.toISOString().slice(0, 10); }
function toMs(v: any) { if (!v) return 0; if (typeof v?.toMillis === 'function') return v.toMillis(); if (v?.seconds) return Number(v.seconds) * 1000; const n = Date.parse(String(v)); return Number.isFinite(n) ? n : 0; }
function locationLabel(region?: string, timezone?: string) { const code = (region || '').toUpperCase(); let country = code; try { if (code && code !== 'UNKNOWN') country = new Intl.DisplayNames(['en'], { type: 'region' }).of(code) || code; } catch {} if (!country || country.toLowerCase() === 'unknown') country = 'Unknown region'; return timezone && timezone !== 'unknown' ? `${country} · ${timezone}` : country; }
function pct(a: number, b: number) { return b ? `${((a / b) * 100).toFixed(1)}%` : '0%'; }
function tokenExpiry(token: WilliToken): Date | null { const explicit = token.expiresAt?.toDate?.(); if (explicit instanceof Date) return explicit; const created = token.createdAt?.toDate?.(); if (created instanceof Date && typeof token.durationMs === 'number') return new Date(created.getTime() + token.durationMs); return null; }
function userActivationExpiry(user: User): Date | null { const v = user.activationExpiresAt; if (!v) return null; if (typeof v?.toDate === 'function') return v.toDate(); if (v?.seconds) return new Date(Number(v.seconds) * 1000); const d = new Date(String(v)); return Number.isFinite(d.getTime()) ? d : null; }
function isUserActive(user: User, tokens: WilliToken[]): boolean { const uid = user.uid || ''; const explicitActive = user.activated === true || user.activationStatus === 'active' || user.williTokenActive === true; const userExpiry = userActivationExpiry(user); if (explicitActive && (!userExpiry || userExpiry.getTime() > Date.now())) return true; return tokens.some(token => { const owner = token.userId || token.uid; const expiry = tokenExpiry(token); return owner === uid && token.revoked !== true && token.cancelled !== true && !!expiry && expiry.getTime() > Date.now(); }); }

export default function AdminAnalyticsPage() {
  const [days, setDays] = useState<Day[]>([]); const [funnel, setFunnel] = useState<Funnel>({ registrations: 0, quizUsers: 0, activatedUsers: 0, payingUsers: 0, revenue: {}, chatgptVisitors: 0 }); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState('');
  async function load() {
    setError(''); setRefreshing(true);
    try {
      const current = auth.currentUser; if (!current) { window.location.replace(`${BASE}/admin/login/`); return; }
      const admin = await getDoc(doc(db, 'admins', current.uid)); if (!admin.exists() && current.uid !== OWNER_UID) { window.location.replace(`${BASE}/admin/login/`); return; }
      const [userSnap, historySnap, tokenSnap, ...dayResults] = await Promise.all([
        getDocs(collection(db, 'users')),
        getDocs(collection(db, 'quizHistory')),
        getDocs(collection(db, 'williTokens')),
        ...Array.from({ length: 14 }, (_, i) => (async () => { const day = dateKey(i); const snap = await getDocs(collection(db, 'siteAnalytics', day, 'visitors')); const sources: Record<string, number> = {}; const locations: Record<string, number> = {}; snap.forEach(d => { const v = d.data() as Visitor; const source = v.source || 'unknown'; sources[source] = (sources[source] || 0) + 1; const location = locationLabel(v.region, v.timezone); locations[location] = (locations[location] || 0) + 1; }); return { day, visitors: snap.size, sources, locations }; })())
      ]);
      setDays(dayResults);
      const fourteenStart = Date.now() - 14 * 86400000;
      const registrations = userSnap.docs.filter(d => { const x = d.data(); const t = toMs(x.createdAt || x.registeredAt || x.created_at); return t >= fourteenStart; }).length;
      const quizUsers = new Set(historySnap.docs.map(d => String(d.data()?.userId || '')).filter(Boolean)).size;
      const tokenData = tokenSnap.docs.map(d => d.data() as WilliToken);
      const activated = userSnap.docs.filter(d => isUserActive({ uid: d.id, ...(d.data() as User) }, tokenData)).length;
      const paidUsers = new Set<string>(); const revenue: Record<string, number> = {};
      tokenSnap.docs.forEach(d => { const x = d.data(); if (String(x.paymentStatus || '').toLowerCase() === 'success' || x.source === 'paystack') { const uid = String(x.userId || x.uid || ''); if (uid) paidUsers.add(uid); const currency = String(x.paymentCurrency || x.currency || 'NGN').toUpperCase(); const amount = Number(x.paymentAmount ?? x.amount ?? 0); if (Number.isFinite(amount) && amount > 0) revenue[currency] = (revenue[currency] || 0) + amount; } });
      const chatgptVisitors = dayResults.reduce((n, d) => n + (d.sources.chatgpt || 0), 0);
      setFunnel({ registrations, quizUsers, activatedUsers: activated, payingUsers: paidUsers.size, revenue, chatgptVisitors });
    } catch (e: any) { setError(e?.code === 'permission-denied' ? 'Firebase denied analytics access. Make sure the latest Firestore rules are published.' : 'Could not load analytics.'); }
    finally { setLoading(false); setRefreshing(false); }
  }
  useEffect(() => onAuthStateChanged(auth, user => { if (!user) window.location.replace(`${BASE}/admin/login/`); else load(); }), []);
  const today = days[0];
  const fourteenTotal = useMemo(() => days.reduce((sum, d) => sum + d.visitors, 0), [days]);
  const topSources = useMemo(() => { const map: Record<string, number> = {}; days.forEach(d => Object.entries(d.sources).forEach(([s,c]) => { map[s]=(map[s]||0)+c; })); return Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,8); }, [days]);
  const topLocations = useMemo(() => { const map: Record<string, number> = {}; days.forEach(d => Object.entries(d.locations).forEach(([l,c]) => { map[l]=(map[l]||0)+c; })); return Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,10); }, [days]);
  const max = Math.max(1, ...days.map(d => d.visitors));
  const revenueText = Object.entries(funnel.revenue).map(([c,a]) => `${c} ${a.toLocaleString(undefined,{maximumFractionDigits:2})}`).join(' · ') || 'No payments recorded';
  const cards: Array<[string, string | number, any]> = [['Today', today?.visitors || 0, Users], ['14-day visitors', fourteenTotal, Globe2], ['Registrations (14d)', funnel.registrations, UserPlus], ['ChatGPT visitors (14d)', funnel.chatgptVisitors, Bot]];
  if (loading) return <main className="grid min-h-screen place-items-center bg-slate-950 text-white">Loading Analytics…</main>;
  return <main className="min-h-screen bg-slate-950 px-4 py-6 text-white sm:px-6"><div className="mx-auto max-w-6xl">
    <div className="flex flex-wrap items-center justify-between gap-3"><a href={`${BASE}/admin/`} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm font-bold hover:bg-white/10"><ArrowLeft size={16}/> Admin</a><button onClick={load} disabled={refreshing} className="inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-4 py-2 text-sm font-black text-slate-950 disabled:opacity-50"><RefreshCw size={16} className={refreshing?'animate-spin':''}/> Refresh</button></div>
    <div className="mt-7"><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-300">EDUWILLS analytics</p><h1 className="mt-2 text-3xl font-black tracking-tight">Visitors, acquisition, funnel & revenue</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Visitor location is a coarse estimate from browser region/language and timezone. No IP address or precise GPS location is collected.</p></div>
    {error && <div className="mt-5 rounded-2xl border border-red-400/20 bg-red-500/10 p-4 text-sm text-red-200">{error}</div>}
    <section className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label,value,Icon])=><div key={label} className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><Icon size={19} className="text-cyan-300"/><p className="mt-4 text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 text-2xl font-black break-words">{value}</p></div>)}</section>
    <section className="mt-6 rounded-2xl border border-cyan-400/20 bg-cyan-400/5 p-5 sm:p-7"><div className="flex items-center gap-3"><BarChart3 size={19} className="text-cyan-300"/><h2 className="font-black">Conversion funnel</h2></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['Visitors','14-day',fourteenTotal],['Registrations','14-day',funnel.registrations],['Quiz users','all recorded',funnel.quizUsers],['Activated','current',funnel.activatedUsers],['Paying users','recorded',funnel.payingUsers]].map(([label,sub,value])=><div key={String(label)} className="rounded-2xl bg-white/5 p-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 text-2xl font-black">{value}</p><p className="mt-1 text-[11px] text-slate-500">{sub}</p></div>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-white/5 p-4 text-sm"><span className="text-slate-500">Visitor → signup</span><strong className="ml-2">{pct(funnel.registrations, fourteenTotal)}</strong></div><div className="rounded-xl bg-white/5 p-4 text-sm"><span className="text-slate-500">Signup → activation</span><strong className="ml-2">{pct(funnel.activatedUsers, funnel.registrations)}</strong></div><div className="rounded-xl bg-white/5 p-4 text-sm"><span className="text-slate-500">Activation → payment</span><strong className="ml-2">{pct(funnel.payingUsers, funnel.activatedUsers)}</strong></div></div></section>
    <section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[.04] p-5 sm:p-7"><div className="flex items-center gap-3"><CreditCard size={19} className="text-cyan-300"/><h2 className="font-black">Monetization</h2></div><p className="mt-2 text-xs text-slate-500">Successful activation payments recorded in WilliTokens.</p><div className="mt-5 text-2xl font-black">{revenueText}</div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-white/5 p-4"><p className="text-xs text-slate-500">Paying users</p><p className="mt-1 text-xl font-black">{funnel.payingUsers}</p></div><div className="rounded-xl bg-white/5 p-4"><p className="text-xs text-slate-500">Activated users</p><p className="mt-1 text-xl font-black">{funnel.activatedUsers}</p></div></div></div><div className="rounded-2xl border border-cyan-400/20 bg-cyan-400/5 p-5 sm:p-7"><div className="flex items-center gap-3"><Bot size={19} className="text-cyan-300"/><h2 className="font-black">ChatGPT performance</h2></div><p className="mt-2 text-xs leading-5 text-slate-500">Current attribution is based on the first acquisition source retained by the visitor tracker.</p><div className="mt-5 text-4xl font-black text-cyan-300">{funnel.chatgptVisitors}</div><p className="mt-1 text-xs font-bold uppercase tracking-wider text-slate-500">ChatGPT-sourced visitors · last 14 days</p><p className="mt-4 text-xs text-slate-400">As user-to-visitor identity is not yet retroactively linked, ChatGPT revenue attribution will become available after signup attribution is connected.</p></div></section>
    <section className="mt-6 rounded-2xl border border-white/10 bg-white/[.04] p-5 sm:p-7"><div className="flex items-center justify-between"><div><h2 className="text-lg font-black">Last 14 days</h2><p className="mt-1 text-xs text-slate-500">Unique visitors by UTC day</p></div><BarChart3 className="text-cyan-300"/></div><div className="mt-7 space-y-3">{days.map(d=><div key={d.day} className="grid grid-cols-[86px_1fr_42px] items-center gap-3 text-sm"><span className="font-bold text-slate-400">{d.day.slice(5)}</span><div className="h-3 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full bg-cyan-400" style={{width:`${Math.max(2,(d.visitors/max)*100)}%`}}/></div><span className="text-right font-black">{d.visitors}</span></div>)}</div></section>
    <section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[.04] p-5 sm:p-7"><div className="flex items-center gap-3"><UserPlus size={19} className="text-cyan-300"/><h2 className="font-black">Traffic sources</h2></div><div className="mt-5 space-y-3">{topSources.length?topSources.map(([source,count])=><div key={source} className="flex items-center justify-between rounded-xl bg-white/5 px-4 py-3"><span className="font-semibold text-slate-300">{source}</span><span className="font-black">{count}</span></div>):<p className="text-sm text-slate-500">No visitor data yet.</p>}</div></div><div className="rounded-2xl border border-white/10 bg-white/[.04] p-5 sm:p-7"><div className="flex items-center gap-3"><MapPin size={19} className="text-cyan-300"/><h2 className="font-black">Visitor locations</h2></div><p className="mt-2 text-xs leading-5 text-slate-500">Estimated country/region and timezone for the last 14 days.</p><div className="mt-5 space-y-3">{topLocations.length?topLocations.map(([location,count])=><div key={location} className="flex items-center justify-between gap-3 rounded-xl bg-white/5 px-4 py-3"><span className="font-semibold text-slate-300 break-words">{location}</span><span className="shrink-0 font-black">{count}</span></div>):<p className="text-sm text-slate-500">No location data yet.</p>}</div></div></section>
  </div></main>;
}
