name = "eduwills-payments"
main = "src/entry.js"
compatibility_date = "2026-08-28"

[vars]
FIREBASE_PROJECT_ID = "eduwills"
FIREBASE_WEB_API_KEY = "AIzaSyBS9zmc9SZolJZqNr4kTwQpWCNv26ECly0"
CALLBACK_URL = "https://chineduwilliams739-commits.github.io/eduwills/dashboard/activation/index.html"
