import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'WAEC Practice Questions & Study Tips | EDUWILLS',
  description: 'Practical WAEC study tips, active recall strategies and book-focused practice for Nigerian students.',
};

export default function WAECBlog() {
  return <main className="min-h-screen bg-paper text-ink"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-4xl items-center justify-between px-5 py-5"><Link href="/eduwills/" className="font-black">EDUWILLS</Link><Link href="/eduwills/study-guides/" className="font-black text-eduBlue">Study Guides</Link></div></header><article className="mx-auto max-w-4xl px-5 py-12"><p className="text-xs font-black uppercase tracking-[.2em] text-eduBlue">WAEC preparation</p><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">WAEC Practice Questions: How to Study Smarter</h1><p className="mt-6 text-lg leading-8 text-slate-600">Prepare for WAEC with active recall, focused revision and regular practice instead of relying on rereading alone.</p><section className="mt-10 space-y-8"><div><h2 className="text-2xl font-black">Use your books actively</h2><p className="mt-3 leading-7 text-slate-600">Study the topics and set books you actually need, then close the book and recall the important ideas from memory.</p></div><div><h2 className="text-2xl font-black">Practise questions regularly</h2><p className="mt-3 leading-7 text-slate-600">Turn each chapter into practice questions and review every mistake. Understanding why an answer is correct is more valuable than simply chasing a score.</p></div><div><h2 className="text-2xl font-black">Use EDUWILLS for book-focused quizzes</h2><p className="mt-3 leading-7 text-slate-600">Search for the book you are studying and generate a focused quiz using your own instructions.</p></div></section><Link href="/eduwills/signup/" className="mt-12 inline-flex rounded-xl bg-ink px-6 py-3 font-black text-white">Practise with EDUWILLS →</Link></article><footer className="border-t border-slate-200 bg-white px-5 py-8 text-center text-sm text-slate-500">EDUWILLS is independent and is not affiliated with WAEC.</footer></main>;
}
