'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Clock3, KeyRound, LayoutDashboard, Plus, ShieldCheck, Users, Settings, Copy, Check, Search, UserCheck } from 'lucide-react';

const BASE = '/eduwills';
const durations = [
  { label: '30 minutes', ms: 30 * 60 * 1000 }, { label: '1 hour', ms: 60 * 60 * 1000 },
  { label: '6 hours', ms: 6 * 60 * 60 * 1000 }, { label: '12 hours', ms: 12 * 60 * 60 * 1000 },
  { label: '1 day', ms: 24 * 60 * 60 * 1000 }, { label: '7 days', ms: 7 * 24 * 60 * 60 * 1000 },
  { label: '14 days', ms: 14 * 24 * 60 * 60 * 1000 }, { label: '30 days', ms: 30 * 24 * 60 * 60 * 1000 },
  { label: '90 days', ms: 90 * 24 * 60 * 60 * 1000 }, { label: '180 days', ms: 180 * 24 * 60 * 60 * 1000 },
  { label: '1 year', ms: 365 * 24 * 60 * 60 * 1000 },
];
const makeToken = () => { const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; return Array.from({ length: 10 }, () => chars[Math.floor(Math.random() * chars.length)]).join(''); };
const readUsers = () => { try { const raw = localStorage.getItem('eduwills_users'); return raw ? JSON.parse(raw) : []; } catch { return []; } };

export default function AdminPage() {
  const [users, setUsers] = useState<any[]>([]); const [selectedUser, setSelectedUser] = useState(''); const [duration, setDuration] = useState('30 minutes'); const [custom, setCustom] = useState(''); const [token, setToken] = useState(''); const [search, setSearch] = useState(''); const [copied, setCopied] = useState(false);
  useEffect(() => { if (sessionStorage.getItem('eduwills_admin_auth') !== 'true') { window.location.replace(`${BASE}/admin/login/`); return; } setUsers(readUsers()); }, []);
  const filtered = useMemo(() => users.filter(u => `${u.name || ''} ${u.username || ''} ${u.phone || ''}`.toLowerCase().includes(search.toLowerCase())), [users, search]);
  const createToken = () => {
    const selected = users.find(u => u.username === selectedUser); if (!selected) { alert('Select a user first.'); return; }
    const preset = durations.find(d => d.label === duration); let ms = preset?.ms;
    if (!ms && custom.trim()) { const m = custom.match(/^(\d+(?:\.\d+)?)\s*(minute|minutes|hour|hours|day|days|week|weeks|month|months|year|years)$/i); if (!m) { alert('Use a duration such as 45 minutes, 3 days, or 2 months.'); return; } const n = Number(m[1]); const unit = m[2].toLowerCase(); const factors: Record<string, number> = { minute: 60000, minutes: 60000, hour: 3600000, hours: 3600000, day: 86400000, days: 86400000, week: 604800000, weeks: 604800000, month: 30 * 86400000, months: 30 * 86400000, year: 365 * 86400000, years: 365 * 86400000 }; ms = n * factors[unit]; }
    if (!ms || ms < 30 * 60000 || ms > 365 * 86400000) { alert('Duration must be between 30 minutes and 1 year.'); return; }
    const next = makeToken(); const expiresAt = new Date(Date.now() + ms).toISOString(); const record = { token: next, username: selected.username, duration: custom.trim() || duration, createdAt: new Date().toISOString(), expiresAt };
    const tokens = JSON.parse(localStorage.getItem('eduwills_tokens') || '[]'); tokens.push(record); localStorage.setItem('eduwills_tokens', JSON.stringify(tokens)); localStorage.setItem('eduwills_last_token', JSON.stringify(record)); setToken(next); setCopied(false); alert(`WilliToken generated for ${selected.username}: ${next}`);
  };
  const copy = async () => { if (!token) return; await navigator.clipboard?.writeText(token); setCopied(true); setTimeout(() => setCopied(false), 1800); };
  return <main className="min-h-screen bg-slate-950 px-4 py-5 text-white sm:px-8"><div className="mx-auto max-w-7xl"><a href={`${BASE}/`} className="inline-flex items-center gap-2 text-sm font-bold text-slate-300"><ArrowLeft size={17}/> EDUWILLS</a><div className="mt-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-black uppercase tracking-wider text-cyan-200"><ShieldCheck size={14}/> Admin console</div><h1 className="mt-3 text-3xl font-black">EDUWILLS Administration</h1><p className="mt-2 text-sm text-slate-400">Manage users, activation status and WilliTokens.</p></div><a href={`${BASE}/admin/settings/`} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-bold"><Settings size={17}/> Admin settings</a></div>
  <div className="mt-7 grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><section className="rounded-3xl border border-white/10 bg-white/5 p-5 sm:p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="font-black">All EDUWILLS users</h2><p className="text-xs text-slate-400">Users stored on this browser in the current free version.</p></div><div className="flex items-center gap-2 rounded-xl border border-white/10 bg-slate-900 px-3"><Search size={16} className="text-slate-500"/><input value={search} onChange={e=>setSearch(e.target.value)} className="w-full bg-transparent py-2.5 text-sm outline-none" placeholder="Search users"/></div></div><div className="mt-5 space-y-2">{filtered.length ? filtered.map(u => { const active = u.activation?.expiresAt && new Date(u.activation.expiresAt).getTime() > Date.now(); return <button key={u.username} onClick={()=>setSelectedUser(u.username)} className={`w-full rounded-2xl border p-4 text-left ${selectedUser===u.username?'border-cyan-300 bg-cyan-400/10':'border-white/10 bg-black/10 hover:bg-white/5'}`}><div className="flex items-center justify-between gap-3"><div><div className="font-black">{u.name || 'Unnamed user'}</div><div className="mt-1 text-xs text-slate-400">@{u.username} · +234{u.phone || ''}</div></div><span className={`rounded-full px-2.5 py-1 text-[11px] font-black ${active?'bg-emerald-400/10 text-emerald-300':'bg-slate-400/10 text-slate-400'}`}>{active?'Active':'Inactive'}</span></div>{active && <div className="mt-2 text-[11px] text-slate-500">Expires {new Date(u.activation.expiresAt).toLocaleString()}</div>}</button> }) : <div className="rounded-2xl border border-dashed border-white/10 p-8 text-center text-sm text-slate-500">No registered users found on this browser yet.</div>}</div></section>
  <section className="rounded-3xl border border-white/10 bg-white/5 p-5 sm:p-6"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-400/10 text-cyan-200"><KeyRound size={19}/></div><div><h2 className="font-black">Generate WilliToken</h2><p className="text-xs text-slate-400">Assign a token directly to a user.</p></div></div><label className="mt-6 block text-sm font-bold">User<select value={selectedUser} onChange={e=>setSelectedUser(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 text-sm outline-none"><option value="">Select a user</option>{users.map(u=><option key={u.username} value={u.username}>{u.name || u.username} (@{u.username})</option>)}</select></label><label className="mt-4 block text-sm font-bold">Duration<select value={duration} onChange={e=>setDuration(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 text-sm outline-none">{durations.map(d=><option key={d.label}>{d.label}</option>)}<option value="custom">Custom duration</option></select></label>{duration==='custom'&&<input value={custom} onChange={e=>setCustom(e.target.value)} className="mt-3 w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 text-sm outline-none" placeholder="e.g. 45 minutes, 3 days, 2 months"/>}<button onClick={createToken} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-cyan-400 px-5 py-3.5 font-black text-slate-950"><Plus size={17}/> Generate WilliToken</button>{token&&<div className="mt-5 rounded-2xl border border-emerald-400/20 bg-emerald-400/5 p-4"><p className="text-xs font-bold text-emerald-300">Token generated</p><div className="mt-2 flex items-center gap-2"><code className="min-w-0 flex-1 break-all rounded-lg bg-black/20 px-3 py-2 text-lg font-black tracking-widest">{token}</code><button onClick={copy} className="rounded-lg border border-white/10 p-2" title="Copy token">{copied?<Check size={17}/>:<Copy size={17}/>}</button></div></div>}</section></div>
  <div className="mt-5 rounded-2xl border border-amber-500/20 bg-amber-500/5 p-4 text-xs leading-5 text-slate-400"><strong className="text-amber-200">Free-version limitation:</strong> GitHub Pages has no shared database. The admin can see users registered in this browser only. A production admin panel that sees every user's account across devices requires a backend/database. This version is intended for your free prototype.</div></div></main>;
}
