'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, BookOpen, Check, Copy, KeyRound, Search, ShieldCheck, Trash2 } from 'lucide-react';
import { collection, deleteDoc, doc, getDoc, getDocs, serverTimestamp, setDoc } from 'firebase/firestore';
import { onAuthStateChanged } from 'firebase/auth';
import { auth, db } from '@/lib/firebase';

const BASE='/eduwills';
const durations=[['30 minutes',1800000],['1 hour',3600000],['6 hours',21600000],['12 hours',43200000],['1 day',86400000],['7 days',604800000],['30 days',2592000000],['1 year',31536000000]] as const;
const token=()=>Array.from({length:10},()=> 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[Math.floor(Math.random()*32)]).join('');
type User={id:string;uid?:string;fullName?:string;username?:string;phone?:string;activated?:boolean;activationExpiresAt?:any};
type Slot={id:string;userId:string;slot:number;title:string;author:string;createdAt?:any};

export default function AdminPage(){
 const [users,setUsers]=useState<User[]>([]),[slots,setSlots]=useState<Slot[]>([]),[selectedUser,setSelectedUser]=useState(''),[duration,setDuration]=useState('30 minutes'),[search,setSearch]=useState(''),[generated,setGenerated]=useState(''),[copied,setCopied]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{const [u,s]=await Promise.all([getDocs(collection(db,'users')),getDocs(collection(db,'bookSlots'))]);setUsers(u.docs.map(d=>({id:d.id,...d.data()} as User)));setSlots(s.docs.map(d=>({id:d.id,...d.data()} as Slot)).sort((a,b)=>a.slot-b.slot));};
 useEffect(()=>onAuthStateChanged(auth,async u=>{if(!u){window.location.replace(`${BASE}/admin/login/`);return}try{const a=await getDoc(doc(db,'admins',u.uid));if(!a.exists()){await auth.signOut();window.location.replace(`${BASE}/admin/login/`);return}await load()}catch(e:any){setError(e?.code==='permission-denied'?'Firebase denied Admin access. Verify this UID exists under admins/.':'Could not load Admin data.')}finally{setLoading(false)}}),[]);
 const filtered=useMemo(()=>users.filter(u=>`${u.fullName||''} ${u.username||''} ${u.phone||''}`.toLowerCase().includes(search.toLowerCase())),[users,search]);
 const userName=(uid:string)=>users.find(u=>(u.uid||u.id)===uid)?.fullName||users.find(u=>(u.uid||u.id)===uid)?.username||uid;
 const createToken=async()=>{const u=users.find(x=>(x.username||'')===selectedUser);if(!u)return alert('Select a user first.');const ms=durations.find(x=>x[0]===duration)?.[1];if(!ms)return;const t=token();try{await setDoc(doc(db,'williTokens',t),{token:t,userId:u.uid||u.id,username:u.username||'',duration,durationMs:ms,createdAt:serverTimestamp(),used:false});setGenerated(t);setCopied(false)}catch{alert('Could not create the token.')}};
 const removeBook=async(b:Slot)=>{if(!confirm(`Delete “${b.title}” by ${b.author} from ${userName(b.userId)}? This frees slot ${b.slot}.`))return;setBusy(true);try{await deleteDoc(doc(db,'bookSlots',b.id));setSlots(v=>v.filter(x=>x.id!==b.id))}catch(e:any){alert(e?.code==='permission-denied'?'Only an authenticated Admin can delete saved books.':'Could not delete this book.')}finally{setBusy(false)}};
 const copy=async()=>{if(generated){await navigator.clipboard?.writeText(generated);setCopied(true);setTimeout(()=>setCopied(false),1500)}};
 if(loading)return <main className="grid min-h-screen place-items-center bg-slate-950 text-white">Loading Admin…</main>;
 return <main className="min-h-screen bg-slate-950 px-4 py-6 text-white"><div className="mx-auto max-w-7xl"><a href={`${BASE}/`} className="inline-flex items-center gap-2 text-sm font-bold text-slate-300"><ArrowLeft size={17}/> EDUWILLS</a><div className="mt-6 flex items-center gap-3"><ShieldCheck className="text-cyan-300"/><div><h1 className="text-3xl font-black">EDUWILLS Administration</h1><p className="text-sm text-slate-400">Admin-only user, token and saved-book management.</p></div></div>{error&&<p className="mt-4 rounded-xl bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}
 <div className="mt-7 grid gap-6 lg:grid-cols-2"><section className="rounded-3xl border border-white/10 bg-white/5 p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 text-xl font-black"><BookOpen size={20}/> Saved books</h2><p className="mt-1 text-xs text-slate-400">Only Admins can remove books. Deleting one immediately frees its slot.</p></div><div className="flex items-center gap-2 rounded-xl border border-white/10 bg-slate-900 px-3"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Filter users" className="w-32 bg-transparent py-2 outline-none"/></div></div><div className="mt-5 space-y-3">{slots.filter(b=>{const u=userName(b.userId).toLowerCase();return !search||`${u} ${b.title} ${b.author}`.toLowerCase().includes(search.toLowerCase())}).map(b=><div key={b.id} className="flex items-center justify-between gap-3 rounded-2xl border border-white/10 bg-black/20 p-4"><div className="min-w-0"><div className="text-xs font-black uppercase tracking-wider text-cyan-300">Slot {b.slot} · {userName(b.userId)}</div><div className="mt-1 truncate font-black">{b.title}</div><div className="text-sm text-slate-400">{b.author}</div></div><button disabled={busy} onClick={()=>removeBook(b)} className="shrink-0 rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-red-300"><Trash2 size={18}/></button></div>)}{!slots.length&&<p className="py-10 text-center text-sm text-slate-500">No saved books found.</p>}</div></section>
 <section className="rounded-3xl border border-white/10 bg-white/5 p-5"><h2 className="flex items-center gap-2 text-xl font-black"><KeyRound size={20}/> Generate WilliToken</h2><label className="mt-5 block text-sm font-bold">User<select value={selectedUser} onChange={e=>setSelectedUser(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 p-3"><option value="">Select a user</option>{filtered.map(u=><option key={u.id} value={u.username||''}>{u.fullName||u.username} @{u.username}</option>)}</select></label><label className="mt-4 block text-sm font-bold">Duration<select value={duration} onChange={e=>setDuration(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 p-3">{durations.map(x=><option key={x[0]} value={x[0]}>{x[0]}</option>)}</select></label><button onClick={createToken} className="mt-5 w-full rounded-xl bg-cyan-400 px-5 py-3 font-black text-slate-950">Generate WilliToken</button>{generated&&<div className="mt-4 rounded-2xl bg-emerald-400/10 p-4"><div className="flex items-center gap-2"><code className="flex-1 break-all font-black tracking-widest">{generated}</code><button onClick={copy} className="rounded-lg border border-white/10 p-2">{copied?<Check size={16}/>:<Copy size={16}/>}</button></div></div>}</section></div></div></main>;
}
