'use client';

import { useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, Clock3, Loader2, Send } from 'lucide-react';
import { getCachedQuestions, type BankQuestion } from '@/lib/studentQuestionBank';
import { collection, addDoc, serverTimestamp } from 'firebase/firestore';
import { auth, db } from '@/lib/firebase';

export default function StudentTestPage() {
  const [questions,setQuestions]=useState<BankQuestion[]>([]),[answers,setAnswers]=useState<Record<number,string>>({}),[idx,setIdx]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[submitted,setSubmitted]=useState(false),[seconds,setSeconds]=useState(0);
  const [meta,setMeta]=useState<{level:string;className:string;examType:any;objective:number;subjective:number;duration:number;subjects:string[];year:any;topics:string[]}>();

  useEffect(()=>{const p=new URLSearchParams(location.search);const m={level:p.get('level')||'jss',className:p.get('className')||'JSS 3',examType:p.get('examType')||'normal',objective:Number(p.get('objective')||20),subjective:Number(p.get('subjective')||1),duration:Math.max(5,Number(p.get('duration')||30)),subjects:(p.get('subjects')||'English Studies').split(',').filter(Boolean),year:p.get('year')||'all',topics:(p.get('topics')||'').split(',').filter(Boolean)};setMeta(m);setSeconds(m.duration*60);(async()=>{try{const bank=await getCachedQuestions({...m,level:m.level as any,examType:m.examType as any,year:m.year==='all'?'all':Number(m.year)});if(bank.questions.length<m.objective+m.subjective){setError(`This test is not ready offline yet. The cached bank contains ${bank.questions.length} questions for this exact selection. No AI request was made.`);}else setQuestions(bank.questions.slice(0,m.objective+m.subjective));}catch{setError('Could not load the cached question bank. No AI generation was started.');}finally{setLoading(false);}})();},[]);
  useEffect(()=>{if(loading||submitted||!questions.length)return;const t=setInterval(()=>setSeconds(s=>{if(s<=1){clearInterval(t);return 0}return s-1}),1000);return()=>clearInterval(t)},[loading,submitted,questions.length]);
  const submit=async()=>{setSubmitted(true);try{if(auth.currentUser)await addDoc(collection(db,'studentExamRecords'),{userId:auth.currentUser.uid,level:meta?.level,className:meta?.className,examType:meta?.examType,subjects:meta?.subjects,answers,questionIds:questions.map(q=>q.id),createdAt:serverTimestamp()});}catch{}}
  if(loading)return <main className="min-h-screen bg-slate-950 p-8 text-white"><Loader2 className="animate-spin text-cyan-300"/><p className="mt-3 font-black">Loading from the cached question bank…</p></main>;
  return <main className="min-h-screen bg-slate-950 px-4 py-6 text-white sm:px-8"><div className="mx-auto max-w-4xl"><a href="/eduwills/dashboard/students/" className="inline-flex items-center gap-2 text-sm font-black text-cyan-300"><ArrowLeft size={16}/>Back to exam builder</a><div className="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-3xl border border-white/10 bg-white/[.04] p-5"><div><p className="text-xs font-black uppercase tracking-widest text-cyan-300">{meta?.examType}</p><h1 className="text-2xl font-black">{meta?.className}</h1></div><div className="flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2 font-black"><Clock3 size={16} className="text-cyan-300"/>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</div></div>{error?<div className="mt-6 rounded-3xl border border-amber-300/20 bg-amber-300/5 p-6 text-amber-100"><p className="font-black">Test not ready</p><p className="mt-2 text-sm leading-6">{error}</p></div>:submitted?<div className="mt-6 rounded-3xl border border-emerald-300/20 bg-emerald-300/5 p-8 text-center"><CheckCircle2 className="mx-auto text-emerald-300" size={44}/><h2 className="mt-4 text-2xl font-black">Attempt saved</h2><p className="mt-2 text-sm text-slate-300">Your answers are stored in Academic Records for marking and progress tracking.</p></div>:<><div className="mt-6 rounded-3xl border border-white/10 bg-white/[.04] p-6"><p className="text-xs font-black uppercase tracking-wider text-slate-500">Question {idx+1} of {questions.length}</p><h2 className="mt-3 text-xl font-black leading-8">{questions[idx]?.question}</h2>{questions[idx]?.type==='objective'?<div className="mt-6 space-y-3">{(questions[idx]?.options||[]).map((o,i)=><button key={o} onClick={()=>setAnswers(v=>({...v,[idx]:String(i)}))} className={`w-full rounded-2xl border p-4 text-left text-sm font-bold ${answers[idx]===String(i)?'border-cyan-300/50 bg-cyan-300/10':'border-white/10 bg-slate-900'}`}>{String.fromCharCode(65+i)}. {o}</button>)}</div>:<textarea value={answers[idx]||''} onChange={e=>setAnswers(v=>({...v,[idx]:e.target.value}))} placeholder="Write your answer…" className="mt-6 min-h-40 w-full rounded-2xl border border-white/10 bg-slate-900 p-4 text-sm outline-none"/>}</div><div className="mt-4 flex justify-between gap-3"><button disabled={idx===0} onClick={()=>setIdx(i=>i-1)} className="rounded-xl border border-white/10 px-4 py-3 font-black disabled:opacity-30">Previous</button>{idx<questions.length-1?<button onClick={()=>setIdx(i=>i+1)} className="rounded-xl bg-cyan-400 px-5 py-3 font-black text-slate-950">Next</button>:<button onClick={submit} className="inline-flex items-center gap-2 rounded-xl bg-emerald-400 px-5 py-3 font-black text-slate-950"><Send size={16}/>Submit</button>}</div></>}</div></main>;
}
