import {NextRequest,NextResponse} from 'next/server';

type Hit={title:string;authors:string[];description?:string};
const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
const clean=(s:any)=>String(s||'').replace(/\s+/g,' ').trim();
async function json(url:string){const r=await fetch(url,{cache:'no-store',headers:{Accept:'application/json'}});if(!r.ok)throw new Error(String(r.status));return r.json()}
function mergeAuthors(names:Set<string>, values:any[]){for(const v of values||[]){const n=clean(v);if(n)names.add(n)}}
export async function POST(req:NextRequest){try{const b=await req.json(),title=clean(b.title),author=clean(b.author);if(!title&&!author)return NextResponse.json({authors:[],books:[]});const names=new Set<string>(),books:Hit[]=[],add=(t:any,a:any[],d?:any)=>{const aa=(a||[]).map(clean).filter(Boolean);mergeAuthors(names,aa);if(clean(t))books.push({title:clean(t),authors:aa,description:clean(d)})};
if(title){const q=encodeURIComponent(title);try{const d=await json(`https://openlibrary.org/search.json?title=${q}&limit=100`);for(const x of d.docs||[])add(x.title,x.author_name,x.first_sentence?.join?.(' '));}catch{}try{const d=await json(`https://www.googleapis.com/books/v1/volumes?q=intitle:${q}&maxResults=40`);for(const x of d.items||[]){const v=x.volumeInfo||{};add(v.title,v.authors,v.description)}}catch{}try{const d=await json(`https://openlibrary.org/search.json?q=${q}&limit=100`);for(const x of d.docs||[])add(x.title,x.author_name,x.first_sentence?.join?.(' '));}catch{}}
if(author){const q=encodeURIComponent(author);try{const d=await json(`https://openlibrary.org/search.json?author=${q}&limit=100`);for(const x of d.docs||[])add(x.title,x.author_name)}catch{}try{const d=await json(`https://www.googleapis.com/books/v1/volumes?q=inauthor:${q}&maxResults=40`);for(const x of d.items||[]){const v=x.volumeInfo||{};add(v.title,v.authors,v.description)}}catch{}}
const requested=norm(author);let filtered=[...names];if(requested)filtered=filtered.filter(n=>norm(n).includes(requested)||requested.includes(norm(n)));return NextResponse.json({authors:filtered.slice(0,80),books:books.slice(0,100),found:books.length>0||filtered.length>0});}catch(e:any){return NextResponse.json({error:e?.message||'Book search unavailable.',authors:[],books:[],found:false},{status:200})}}
