'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, BookOpen, CalendarDays, Loader2, Trophy } from 'lucide-react';
import { onAuthStateChanged } from 'firebase/auth';
import { collection, doc, getDoc, getDocs, query, where } from 'firebase/firestore';
import { auth, db } from '@/lib/firebase';

const BASE='/eduwills';
const LABELS:Record<string,string>={primary:'Primary',junior:'Junior Secondary','junior-secondary':'Junior Secondary',senior:'Senior Secondary','senior-secondary':'Senior Secondary',book:'Book Learner','book-learner':'Book Learner'};
const normalize=(v:any)=>LABELS[String(v||'').trim().toLowerCase()]||String(v||'').trim();
const time=(v:any)=>{if(!v)return 0;if(typeof v.toMillis==='function')return v.toMillis();if(v.seconds)return v.seconds*1000;const n=Date.parse(String(v));return Number.isFinite(n)?n:0};
const recordCategory=(x:any)=>normalize(x.category||x.learningCategory||x.educationLevel||x.level||x.track||x.profileCategory||((x.books||[]).length?'Book Learner':''));

export default function CategoryRecordsPage(){
 const [category,setCategory]=useState('Book Learner'),[items,setItems]=useState<any[]>([]),[active,setActive]=useState(false),[loading,setLoading]=useState(true);
 useEffect(()=>onAuthStateChanged(auth,async u=>{if(!u){location.replace(`${BASE}/login/`);return}try{const params=new URLSearchParams(location.search);const wanted=normalize(params.get('category')||'Book Learner');setCategory(wanted);const user=await getDoc(doc(db,'users',u.uid));const d:any=user.data()||{};const e=time(d.activationExpiresAt);setActive((d.activationStatus==='active'||d.activated===true||d.williTokenActive===true||d.activationActive===true)&&(!e||e>Date.now()));const snap=await getDocs(query(collection(db,'quizHistory'),where('userId','==',u.uid)));const rows=snap.docs.map(s=>({id:s.id,...s.data()})).filter((x:any)=>{const c=recordCategory(x);return c&&c.toLowerCase()===wanted.toLowerCase()&&x.status!=='failed'&&x.status!=='generating'}).sort((a:any,b:any)=>time(b.completedAt||b.createdAt)-time(a.completedAt||a.createdAt));setItems(rows);}catch(e){console.error(e)}finally{setLoading(false)}}),[]);
 const summary=useMemo(()=>{let correct=0,total=0;for(const x of items){const qs=Array.isArray(x.questionsData)?x.questionsData.length:0;const t=Number(x.total||x.questions||qs);const s=Number(x.score||0);if(Number.isFinite(t)&&t>0){total+=t;correct+=Number.isFinite(s)?s:0}}return{tests:items.length,average:total?Math.round(correct/total*100):0}},[items]);
 if(loading)return <main className="grid min-h-screen place-items-center bg-paper"><Loader2 className="animate-spin text-cyan-600"/></main>;
 if(!active)return <main className="grid min-h-screen place-items-center bg-ink p-5 text-white"><section className="max-w-md rounded-[2rem] border border-white/10 bg-white/5 p-8 text-center"><Trophy className="mx-auto text-cyan-300" size={34}/><h1 className="mt-4 text-2xl font-black">{category} records are protected</h1><p className="mt-2 text-sm leading-6 text-slate-300">Activate EDUWILLS to save and review your category-specific learning record.</p><a href={`${BASE}/dashboard/activation/`} className="mt-5 inline-flex rounded-xl bg-white px-5 py-3 font-black text-ink">Activate</a></section></main>;
 return <main className="min-h-screen bg-paper pb-10 text-ink"><header className="border-b border-slate-200 bg-white/90 px-5 py-4"><div className="mx-auto flex max-w-4xl items-center justify-between"><a href={`${BASE}/dashboard/`} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2 text-sm font-black"><ArrowLeft size={17}/> Dashboard</a><span className="font-black">{category} Records</span></div></header><div className="mx-auto max-w-4xl px-5 py-7"><section className="rounded-[2rem] bg-ink p-7 text-white shadow-xl"><p className="text-[10px] font-black uppercase tracking-[.2em] text-cyan-200">CATEGORY RECORD</p><h1 className="mt-3 text-3xl font-black">{category}</h1><p className="mt-2 text-sm leading-6 text-slate-300">Only results belonging to this learning category are shown here, even when the same account studies other categories.</p><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-slate-400">Tests</p><p className="mt-1 text-2xl font-black">{summary.tests}</p></div><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-slate-400">Overall accuracy</p><p className="mt-1 text-2xl font-black">{summary.average}%</p></div></div></section><section className="mt-6 space-y-3">{items.map(x=>{const total=Number(x.total||x.questions||(Array.isArray(x.questionsData)?x.questionsData.length:0));const score=Number(x.score||0);const pct=total?Math.round(score/total*100):Number(x.percentage||0);return <a key={x.id} href={`${BASE}/dashboard/history/?id=${x.id}`} className="block rounded-2xl border border-slate-200 bg-white p-5 shadow-sm hover:border-cyan-300"><div className="flex items-start gap-4"><span className="grid h-11 w-11 place-items-center rounded-xl bg-cyan-50 text-cyan-700"><Trophy size={19}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-black">{pct}% · {score}/{total}</h2><span className="inline-flex items-center gap-1 text-xs font-bold text-slate-400"><CalendarDays size={14}/>{time(x.completedAt||x.createdAt)?new Date(time(x.completedAt||x.createdAt)).toLocaleDateString():'Date unavailable'}</span></div><p className="mt-1 text-xs text-slate-500">{(x.books||[]).map((b:any)=>b.title).join(', ')||'Quiz session'} · {x.difficulty||'Mixed'}</p></div></div></a>})}{!items.length&&<div className="rounded-3xl border border-dashed border-slate-300 bg-white p-10 text-center"><BookOpen className="mx-auto text-slate-300" size={34}/><h2 className="mt-3 font-black">No {category} records yet</h2><p className="mt-1 text-sm text-slate-500">Complete a quiz in this category and it will appear here.</p><a href={`${BASE}/dashboard/category/?category=${encodeURIComponent(category.toLowerCase().replace(/\s+/g,'-'))}`} className="mt-5 inline-flex rounded-xl bg-ink px-5 py-3 text-sm font-black text-white">Start learning</a></div>}</section></div></main>;
}
