'use client';
import { useState } from 'react';
import { ArrowLeft, BookOpen, Bot, Send, Sparkles } from 'lucide-react';
const BASE='/eduwills';
export default function AIPage(){
 const [messages,setMessages]=useState<{role:string,text:string}[]>([]); const [input,setInput]=useState('');
 const send=()=>{if(!input.trim())return; const q=input.trim(); setMessages(m=>[...m,{role:'user',text:q},{role:'ai',text:'EDUWILLS AI is ready for your book-learning request. In the next AI connection phase, I will search the selected book information, identify the author, answer book questions and generate quizzes from the available material.'}]);setInput('')};
 return <main className="min-h-screen bg-paper text-ink"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 sm:px-8"><a href={`${BASE}/dashboard/`} className="inline-flex items-center gap-2 text-sm font-bold text-slate-600"><ArrowLeft size={17}/> Dashboard</a><div className="flex items-center gap-2 font-black"><Bot className="text-eduBlue"/> EDUWILLS AI</div></div></header><div className="mx-auto max-w-5xl px-5 py-8 sm:px-8"><div className="rounded-[2rem] bg-ink p-7 text-white sm:p-10"><div className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-black uppercase tracking-wider text-cyan-200"><Sparkles size={13}/> Intelligent learning assistant</div><h1 className="mt-5 text-3xl font-black sm:text-4xl">Ask EDUWILLS AI</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">Ask about a book, author, chapter, character or quiz. The production AI connection will use verified book information to generate useful learning material.</p></div><div className="mt-6 overflow-hidden rounded-3xl border border-slate-200 bg-white"><div className="min-h-[330px] space-y-4 p-6 sm:p-8">{messages.length===0?<div className="grid h-[260px] place-items-center text-center"><div><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-blue-50 text-eduBlue"><BookOpen/></div><h2 className="mt-4 text-lg font-black">Your AI study partner</h2><p className="mt-2 max-w-md text-sm leading-6 text-slate-500">Try “Who wrote Things Fall Apart?” or “Create 10 questions about my selected book.”</p></div></div>:messages.map((m,i)=><div key={i} className={`flex ${m.role==='user'?'justify-end':'justify-start'}`}><div className={`max-w-[85%] rounded-2xl px-4 py-3 text-sm leading-6 ${m.role==='user'?'bg-eduBlue text-white':'bg-paper text-slate-700'}`}>{m.text}</div></div>)}</div><div className="border-t border-slate-100 p-4"><div className="flex gap-2"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-paper px-4 py-3 outline-none focus:border-eduBlue" placeholder="Ask EDUWILLS AI..."/><button onClick={send} className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-ink text-white"><Send size={17}/></button></div></div></div></div></main>;
}
