'use client';

import { useEffect, useMemo, useState } from 'react';
import { addDoc, collection, doc, getDoc, getDocs, query, serverTimestamp, where } from 'firebase/firestore';
import { ArrowLeft, BookOpen, Bot, Check, Clock3, Plus, Sparkles, Trash2 } from 'lucide-react';
import { auth, db } from '../../../lib/firebase';

const BASE='/eduwills';
const MAX_INSTRUCTIONS=100;

type Book={id:string;slot:number;title:string;author:string;cover?:string;createdAt?:unknown};

export default function AIPage(){
 const [books,setBooks]=useState<Book[]>([]); const [loading,setLoading]=useState(true); const [title,setTitle]=useState(''); const [authors,setAuthors]=useState<string[]>([]); const [author,setAuthor]=useState(''); const [slot,setSlot]=useState<number|''>(''); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('');
 const [selected,setSelected]=useState<string[]>([]); const [questions,setQuestions]=useState(10); const [duration,setDuration]=useState('20'); const [difficulty,setDifficulty]=useState('Mixed'); const [instructions,setInstructions]=useState('');
 const slots=useMemo(()=>Array.from({length:5},(_,i)=>books.find(b=>b.slot===i+1)),[books]);
 const load=async()=>{ if(!auth.currentUser)return; setLoading(true); const snap=await getDocs(query(collection(db,'bookSlots'),where('userId','==',auth.currentUser.uid))); setBooks(snap.docs.map(d=>({id:d.id,...d.data()} as Book)).sort((a,b)=>a.slot-b.slot)); setLoading(false); };
 useEffect(()=>{load()},[]);
 const findBook=async()=>{ setMessage(''); if(!title.trim())return; setAuthors([]); setAuthor(''); setSlot('');
   // Free metadata lookup: Open Library public search endpoint. It returns candidate authors without requiring an API key.
   try { const r=await fetch(`https://openlibrary.org/search.json?title=${encodeURIComponent(title.trim())}&limit=8`); const data=await r.json(); const names=Array.from(new Set((data.docs||[]).flatMap((d:any)=>d.author_name||[]).filter(Boolean))) as string[]; setAuthors(names.slice(0,6)); if(!names.length)setMessage('No author candidates were found. Check the title and try again.'); }
   catch { setMessage('Book search is temporarily unavailable. Try again.'); }
 };
 const saveBook=async()=>{ if(!auth.currentUser||!author||!slot)return; setSaving(true); setMessage(''); try { const existing=slots[Number(slot)-1]; if(existing){setMessage('That slot is already permanently occupied. Choose an empty slot.'); return;} await addDoc(collection(db,'bookSlots'),{userId:auth.currentUser.uid,slot:Number(slot),title:title.trim(),author,createdAt:serverTimestamp()}); setTitle('');setAuthors([]);setAuthor('');setSlot('');setMessage('Book saved to your permanent slot.'); await load(); } catch(e:any){setMessage(e?.message||'Could not save this book.');} finally{setSaving(false);} };
 const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 const generate=async()=>{ if(!selected.length){setMessage('Select at least one saved book.');return;} if(instructions.length>MAX_INSTRUCTIONS){setMessage('Instructions must be 100 characters or fewer.');return;} const chosen=books.filter(b=>selected.includes(b.id)); const quiz={userId:auth.currentUser?.uid||'',books:chosen.map(b=>({title:b.title,author:b.author})),questions,duration:duration==='none'?null:Number(duration),difficulty,instructions,createdAt:serverTimestamp()}; try { await addDoc(collection(db,'quizHistory'),{...quiz,status:'generated'}); sessionStorage.setItem('eduwills_pending_quiz',JSON.stringify({...quiz,createdAt:Date.now()})); window.location.href=`${BASE}/dashboard/quiz/`; } catch { setMessage('Unable to save the quiz setup. Please try again.'); } };
 return <main className="min-h-screen bg-paper text-ink"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 sm:px-8"><a href={`${BASE}/dashboard/`} className="inline-flex items-center gap-2 text-sm font-bold text-slate-600"><ArrowLeft size={17}/> Dashboard</a><div className="flex items-center gap-2 font-black"><Bot className="text-eduBlue"/> EDUWILLS AI</div></div></header>
 <div className="mx-auto max-w-6xl px-5 py-8 sm:px-8"><section className="rounded-[2rem] bg-ink p-7 text-white sm:p-10"><div className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-black uppercase tracking-wider text-cyan-200"><Sparkles size={13}/> Book Learner AI</div><h1 className="mt-5 text-3xl font-black sm:text-4xl">Build your five-book library</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300">Add a book, choose the author EDUWILLS finds, save it permanently, then use one or more books to create a personalized quiz.</p></section>
 <div className="mt-7 grid gap-7 lg:grid-cols-[1fr_1.2fr]"><section className="rounded-3xl border border-slate-200 bg-white p-6 sm:p-8"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-eduBlue">My Books</p><h2 className="mt-1 text-2xl font-black">Five permanent slots</h2></div><BookOpen className="text-eduBlue"/></div><div className="mt-6 space-y-3">{slots.map((b,i)=><div key={i} className="rounded-2xl border border-slate-200 p-4">{b?<div className="flex items-center gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-blue-50 text-eduBlue"><BookOpen size={18}/></div><div className="min-w-0"><p className="text-[11px] font-black uppercase tracking-wider text-slate-400">Slot {i+1}</p><p className="truncate font-black">{b.title}</p><p className="text-sm text-slate-500">{b.author} <span className="ml-1 text-emerald-600">✓ Saved</span></p></div></div>:<div className="flex items-center gap-3 text-slate-400"><div className="grid h-10 w-10 place-items-center rounded-xl bg-paper"><Plus size={18}/></div><div><p className="text-[11px] font-black uppercase tracking-wider">Slot {i+1}</p><p className="font-bold">Empty — add a book</p></div></div>}</div>)}</div></section>
 <section className="rounded-3xl border border-slate-200 bg-white p-6 sm:p-8"><p className="text-xs font-black uppercase tracking-wider text-eduBlue">Add a book</p><h2 className="mt-1 text-2xl font-black">Find your book</h2><p className="mt-2 text-sm text-slate-500">Search public book metadata, review the author candidates, then save your choice.</p><div className="mt-5 flex gap-2"><input value={title} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>e.key==='Enter'&&findBook()} className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-paper px-4 py-3 outline-none focus:border-eduBlue" placeholder="Book name"/><button onClick={findBook} className="rounded-xl bg-ink px-5 py-3 font-black text-white">Find</button></div>{authors.length>0&&<div className="mt-5"><p className="text-sm font-black">Choose an author</p><div className="mt-2 space-y-2">{authors.map(a=><button key={a} onClick={()=>setAuthor(a)} className={`flex w-full items-center justify-between rounded-xl border px-4 py-3 text-left text-sm font-bold ${author===a?'border-eduBlue bg-blue-50':'border-slate-200'}`}>{a}{author===a&&<Check size={17}/>}</button>)}</div><div className="mt-5"><label className="text-sm font-black">Save to slot</label><select value={slot} onChange={e=>setSlot(e.target.value?Number(e.target.value):'')} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3"><option value="">Select empty slot</option>{slots.map((b,i)=>!b&&<option key={i} value={i+1}>Slot {i+1}</option>)}</select></div><button disabled={saving||!author||!slot} onClick={saveBook} className="mt-4 w-full rounded-xl bg-eduBlue px-5 py-3.5 font-black text-white disabled:opacity-40">{saving?'Saving...':'Save book permanently'}</button></div>}{message&&<p className="mt-4 rounded-xl bg-blue-50 p-3 text-sm font-bold text-slate-700">{message}</p>}</section></div>
 <section className="mt-7 rounded-3xl border border-slate-200 bg-white p-6 sm:p-8"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-eduBlue"><Sparkles size={19}/></div><div><p className="text-xs font-black uppercase tracking-wider text-eduBlue">Take Quiz</p><h2 className="text-2xl font-black">Tell EDUWILLS AI what you want</h2></div></div><div className="mt-6 grid gap-6 md:grid-cols-2"><div><p className="text-sm font-black">Select book/s</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{books.map(b=><button key={b.id} onClick={()=>toggle(b.id)} className={`rounded-xl border p-3 text-left text-sm font-bold ${selected.includes(b.id)?'border-eduBlue bg-blue-50':'border-slate-200'}`}>{selected.includes(b.id)?'✓ ':''}{b.title}</button>)}</div>{!books.length&&!loading&&<p className="mt-2 text-sm text-slate-500">Add a book above before creating a quiz.</p>}</div><div><label className="block text-sm font-black">Number of questions <span className="font-normal text-slate-400">(max 100)</span><input type="number" min={1} max={100} value={questions} onChange={e=>setQuestions(Math.min(100,Math.max(1,Number(e.target.value)||1)))} className="mt-2 w-full rounded-xl border border-slate-200 bg-paper px-4 py-3"/></label><label className="mt-4 block text-sm font-black">Duration<select value={duration} onChange={e=>setDuration(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3"><option value="10">10 minutes</option><option value="20">20 minutes</option><option value="30">30 minutes</option><option value="45">45 minutes</option><option value="60">60 minutes</option><option value="none">No time limit</option></select></label><label className="mt-4 block text-sm font-black">Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3"><option>Easy</option><option>Medium</option><option>Hard</option><option>Mixed</option></select></label></div></div><div className="mt-6"><label className="text-sm font-black">Instructions for EDUWILLS AI <span className="font-normal text-slate-400">(max 100 characters)</span><textarea maxLength={MAX_INSTRUCTIONS} value={instructions} onChange={e=>setInstructions(e.target.value)} className="mt-2 min-h-24 w-full rounded-xl border border-slate-200 bg-paper px-4 py-3 outline-none focus:border-eduBlue" placeholder="e.g. Focus on chapter 2 and questions about Okonkwo."/><span className="mt-1 block text-right text-xs text-slate-400">{instructions.length}/{MAX_INSTRUCTIONS}</span></label></div><button onClick={generate} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-ink px-5 py-4 font-black text-white"><Clock3 size={18}/> Create my quiz</button></section></div></main>;
}
