import Link from 'next/link';

const guides=[
 {title:'WAEC Practice Questions: How to Study Smarter',description:'Practical guidance for Senior Secondary learners preparing for WAEC, with book-focused practice and self-testing strategies.',slug:'waec-practice-questions'},
 {title:'JAMB and UTME Practice: Build a Better Study Routine',description:'A simple study approach for JAMB and UTME preparation, including timed practice and active recall.',slug:'jamb-utme-practice'},
 {title:'NECO Exam Preparation Guide for Nigerian Students',description:'Study planning ideas for NECO learners, from choosing topics to reviewing mistakes after practice tests.',slug:'neco-exam-preparation'},
 {title:'Turn Any Book Into a Practice Quiz',description:'Learn how EDUWILLS can turn a book you are studying into focused multiple-choice practice.',slug:'book-quiz-generator'},
];
const base='/eduwills';
export default function StudyGuides(){return <main className="min-h-screen bg-paper text-ink"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 sm:px-8"><Link href={base+'/'} className="font-black">EDUWILLS</Link><Link href={base+'/signup/'} className="rounded-xl bg-eduBlue px-4 py-2.5 text-sm font-black text-white">Try EDUWILLS</Link></div></header><div className="mx-auto max-w-6xl px-5 py-12 sm:px-8"><p className="text-xs font-black uppercase tracking-[.2em] text-eduBlue">Study guides</p><h1 className="mt-3 max-w-3xl text-4xl font-black tracking-tight sm:text-5xl">WAEC, JAMB & NECO study resources for Nigerian learners</h1><p className="mt-5 max-w-3xl text-base leading-7 text-slate-600">Free study guidance for Nigerian students preparing for WAEC, JAMB, NECO and school assessments. EDUWILLS is an independent learning platform and is not affiliated with or endorsed by any examination body.</p><div className="mt-10 grid gap-5 md:grid-cols-2">{guides.map(g=><article key={g.slug} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><h2 className="text-xl font-black">{g.title}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{g.description}</p><Link href={`${base}/study-guides/${g.slug}/`} className="mt-5 inline-flex font-black text-eduBlue">Read guide →</Link></article>)}</div><section className="mt-12 rounded-[2rem] bg-ink p-8 text-white"><h2 className="text-2xl font-black">Practice what you study</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">Search for a book and use EDUWILLS to generate focused quiz questions, review your results and keep practising.</p><Link href={base+'/signup/'} className="mt-6 inline-flex rounded-xl bg-white px-5 py-3 font-black text-ink">Create a quiz</Link></section></div></main>}
