'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,LockKeyhole,MessageCircle,Plus,School,Search,Users} from 'lucide-react';
import {onAuthStateChanged} from 'firebase/auth';
import {addDoc,arrayUnion,collection,doc,getDoc,onSnapshot,query,serverTimestamp,setDoc,where,limit} from 'firebase/firestore';
import {auth,db} from '@/lib/firebase';
const BASE='/eduwills';
const active=(d:any)=>{const e=d?.activationExpiresAt?.toMillis?.()||Date.parse(String(d?.activationExpiresAt||''))||0;return(d?.activationStatus==='active'||d?.activated===true||d?.williTokenActive===true||d?.activationActive===true||d?.isActive===true)&&(!e||e>Date.now())};
const initials=(g:any)=>String(g?.name||'G').trim().slice(0,1).toUpperCase();
type CommunityGroup={id:string;deleted?:boolean;[key:string]:any};
export default function Community(){
 const[user,setUser]=useState<any>(null),[profile,setProfile]=useState<any>({}),[ok,setOk]=useState(false),[loading,setLoading]=useState(true),[tab,setTab]=useState('groups'),[groups,setGroups]=useState<CommunityGroup[]>([]),[mine,setMine]=useState<CommunityGroup[]>([]),[q,setQ]=useState(''),[name,setName]=useState(''),[desc,setDesc]=useState(''),[notice,setNotice]=useState(''),[creating,setCreating]=useState(false);
 useEffect(()=>onAuthStateChanged(auth,async u=>{if(!u){location.replace(BASE+'/login/');return}setUser(u);const s=await getDoc(doc(db,'users',u.uid));const d=s.data()||{};setProfile(d);setOk(active(d));setLoading(false)}),[]);
 useEffect(()=>{if(!user||!ok)return;return onSnapshot(query(collection(db,'communityGroups'),where('visibility','==','public'),limit(100)),s=>setGroups(s.docs.map(x=>({id:x.id,...x.data()} as CommunityGroup)).filter(x=>!x.deleted)) )},[user,ok]);
 useEffect(()=>{if(!user||!ok)return;return onSnapshot(query(collection(db,'communityGroups'),where('memberIds','array-contains',user.uid),limit(100)),s=>setMine(s.docs.map(x=>({id:x.id,...x.data()} as CommunityGroup)).filter(x=>!x.deleted)))},[user,ok]);
 const shown=useMemo(()=>{const x=q.trim().toLowerCase();return(x?groups.filter(g=>String(g.name||'').toLowerCase().includes(x)):groups).slice(0,50)},[groups,q]);
 async function create(){if(!user||!ok||!name.trim())return;setCreating(true);setNotice('');try{const r=await addDoc(collection(db,'communityGroups'),{name:name.trim(),description:desc.trim(),ownerId:user.uid,adminIds:[user.uid],memberIds:[user.uid],visibility:'public',type:'study',creatorRulesAccepted:false,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),memberCount:1});setName('');setDesc('');location.assign(BASE+'/dashboard/community/group/?id='+r.id)}catch(e:any){setNotice(e?.message||'Could not create group.')}finally{setCreating(false)}}
 if(loading)return <main className="grid min-h-screen place-items-center bg-paper font-bold text-slate-500">Loading community…</main>;
 return <main className="min-h-screen bg-paper pb-28 text-ink"><header className="sticky top-0 z-40 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><a href={BASE+'/dashboard/'} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-black"><ArrowLeft size={17}/> Dashboard</a><a href={BASE+'/dashboard/personal/'} className="grid h-10 w-10 overflow-hidden rounded-full bg-ink text-white place-items-center font-black">{profile.photoURL||profile.avatarUrl?<img src={profile.photoURL||profile.avatarUrl} className="h-full w-full object-cover"/>:String(profile.fullName||profile.username||'L')[0]}</a></div></header>
 <div className="mx-auto max-w-6xl px-5 py-7"><section className="rounded-[2rem] bg-ink p-7 text-white shadow-2xl sm:p-10"><p className="text-[10px] font-black uppercase tracking-[.2em] text-cyan-200">COMMUNITY</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">Learn together. Build your circle.</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-300">Find learners, join focused groups, communicate and build academic communities.</p></section>
 {!ok&&<section className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-950"><LockKeyhole className="mr-2 inline" size={17}/>Community requires activation. <a className="underline" href={BASE+'/dashboard/activation/'}>Activate your account</a>.</section>}
 {notice&&<div className="mt-5 rounded-2xl bg-cyan-50 p-4 text-sm font-bold text-cyan-950">{notice}</div>}
 <div className="mt-6 grid grid-cols-3 gap-2 rounded-2xl border border-slate-200 bg-white p-1.5"><button onClick={()=>setTab('groups')} className={tab==='groups'?'rounded-xl bg-ink p-3 text-xs font-black text-white':'rounded-xl p-3 text-xs font-black text-slate-500'}><Users className="mx-auto mb-1" size={18}/>GROUPS</button><button onClick={()=>setTab('chat')} className={tab==='chat'?'rounded-xl bg-ink p-3 text-xs font-black text-white':'rounded-xl p-3 text-xs font-black text-slate-500'}><MessageCircle className="mx-auto mb-1" size={18}/>CHAT</button><button onClick={()=>setTab('schools')} className={tab==='schools'?'rounded-xl bg-ink p-3 text-xs font-black text-white':'rounded-xl p-3 text-xs font-black text-slate-500'}><School className="mx-auto mb-1" size={18}/>SCHOOLS</button></div>
 {tab==='groups'&&<div className="mt-5 space-y-6"><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><div className="flex flex-1 items-center gap-2 rounded-2xl border border-slate-200 bg-paper px-4 py-3"><Search size={18} className="text-slate-400"/><input disabled={!ok} value={q} onChange={e=>setQ(e.target.value)} placeholder="Search groups by name…" className="min-w-0 flex-1 bg-transparent text-sm font-bold outline-none"/></div><button disabled={!ok} onClick={()=>document.getElementById('create-group')?.scrollIntoView({behavior:'smooth'})} className="inline-flex items-center justify-center gap-2 rounded-xl bg-ink px-4 py-3 text-xs font-black text-white disabled:opacity-40"><Plus size={15}/>Create group</button></div></section>
 <section><div className="mb-3 flex items-end justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-700">YOUR GROUPS</p><h2 className="text-2xl font-black">Your communities</h2></div><span className="rounded-full bg-ink px-3 py-1.5 text-xs font-black text-white">{mine.length}</span></div>{mine.length?<div className="grid gap-4 sm:grid-cols-2">{mine.map(g=><GroupCard key={g.id} g={g} mine onOpen={()=>location.assign(BASE+'/dashboard/community/group/?id='+g.id)}/>)}</div>:<div className="rounded-3xl border border-dashed border-slate-300 bg-white p-8 text-center text-sm font-bold text-slate-500">You have no groups yet. Create one and it will appear here immediately.</div>}</section>
 <section><div className="mb-3"><p className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-700">DISCOVER</p><h2 className="text-2xl font-black">Suggested groups</h2></div>{shown.length?<div className="grid gap-4 sm:grid-cols-2">{shown.map(g=><GroupCard key={g.id} g={g} onOpen={()=>location.assign(BASE+'/dashboard/community/group/?id='+g.id)}/>)}</div>:<div className="rounded-3xl border border-slate-200 bg-white p-8 text-center text-sm font-bold text-slate-500">No group matches that name.</div>}</section>
 <section id="create-group" className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-700">CREATE</p><h2 className="mt-1 text-2xl font-black">Start a study group</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><input disabled={!ok} value={name} onChange={e=>setName(e.target.value)} placeholder="Group name" className="rounded-xl border border-slate-200 bg-paper px-4 py-3 text-sm font-bold"/><input disabled={!ok} value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Short description" className="rounded-xl border border-slate-200 bg-paper px-4 py-3 text-sm font-bold"/></div><button disabled={!ok||creating} onClick={create} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-cyan-700 px-5 py-3 text-sm font-black text-white disabled:opacity-40">{creating?'Creating…':'Create group'} <ArrowRight size={16}/></button></section></div>}
 {tab==='chat'&&<section className="mt-5 rounded-3xl border border-slate-200 bg-white p-8 text-center shadow-sm"><MessageCircle className="mx-auto text-cyan-600" size={34}/><h2 className="mt-3 text-2xl font-black">Academic Chat</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-slate-500">Search learners by their unique username from the chat workspace and start an academic conversation.</p><a href={BASE+'/dashboard/community/chat/'} className="mt-5 inline-flex rounded-xl bg-ink px-5 py-3 text-sm font-black text-white">Open chat</a></section>}
 {tab==='schools'&&<section className="mt-5 rounded-3xl border border-slate-200 bg-white p-8 text-center shadow-sm"><School className="mx-auto text-cyan-600" size={34}/><h2 className="mt-3 text-2xl font-black">School Communities</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-slate-500">Create a school community after the server verifies the required ₦2,000 payment.</p><a href={BASE+'/dashboard/community/schools/'} className="mt-5 inline-flex rounded-xl bg-ink px-5 py-3 text-sm font-black text-white">Open schools</a></section>}
 </div></main>
}
function GroupCard({g,onOpen,mine=false}:{g:CommunityGroup;onOpen:()=>void;mine?:boolean}){const photo=g.avatarUrl||g.photoURL;return <button onClick={onOpen} className="w-full rounded-3xl border border-slate-200 bg-white p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-cyan-300 hover:shadow-md"><div className="flex gap-4"><div className="grid h-16 w-16 shrink-0 place-items-center overflow-hidden rounded-2xl bg-cyan-50 text-cyan-700">{photo?<img src={photo} className="h-full w-full object-cover"/>:<span className="text-xl font-black">{initials(g)}</span>}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><h3 className="truncate text-base font-black">{g.name}</h3>{mine&&<span className="rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-black text-emerald-700">YOUR GROUP</span>}</div><p className="mt-1 line-clamp-2 text-xs leading-5 text-slate-500">{g.description||'Focused EDUWILLS study community.'}</p><div className="mt-3 flex flex-wrap gap-2 text-[10px] font-black text-slate-400"><span>{Array.isArray(g.memberIds)?g.memberIds.length:(g.memberCount||0)} members</span><span>•</span><span>{Array.isArray(g.adminIds)?g.adminIds.length:1} admins</span><span>•</span><span>{g.type||'study'}</span></div></div></div></button>}
