'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2, GraduationCap, LockKeyhole, MessageCircle, MoreHorizontal, Plus, School, Search, Send, ShieldCheck, Users } from 'lucide-react';
import { onAuthStateChanged } from 'firebase/auth';
import { addDoc, collection, doc, getDoc, getDocs, limit, onSnapshot, orderBy, query, runTransaction, serverTimestamp, setDoc, where } from 'firebase/firestore';
import { auth, db } from '@/lib/firebase';

const BASE='/eduwills';
type Section='chat'|'groups'|'schools';
const normalize=(v:any)=>String(v||'').trim().toLowerCase();
function active(d:any){const e=d?.activationExpiresAt?.toMillis?.()||Date.parse(String(d?.activationExpiresAt||''))||0;return (d?.activationStatus==='active'||d?.activated===true||d?.williTokenActive===true||d?.activationActive===true||d?.isActive===true)&&(!e||e>Date.now());}
function pair(a:string,b:string){return [a,b].sort().join('_');}

export default function CommunityHub(){
 const [section,setSection]=useState<Section>('chat'),[user,setUser]=useState<any>(null),[profile,setProfile]=useState<any>({}),[activated,setActivated]=useState(false),[loading,setLoading]=useState(true),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[results,setResults]=useState<any[]>([]),[groups,setGroups]=useState<any[]>([]),[myGroups,setMyGroups]=useState<any[]>([]),[selectedChat,setSelectedChat]=useState<any>(null),[messages,setMessages]=useState<any[]>([]),[draft,setDraft]=useState(''),[groupOpen,setGroupOpen]=useState(false),[groupName,setGroupName]=useState(''),[groupDescription,setGroupDescription]=useState(''),[schoolName,setSchoolName]=useState(''),[schoolDescription,setSchoolDescription]=useState(''),[creating,setCreating]=useState(false),[paying,setPaying]=useState(false);
 useEffect(()=>onAuthStateChanged(auth,async u=>{if(!u){location.replace(`${BASE}/login/`);return}setUser(u);try{const s=await getDoc(doc(db,'users',u.uid));const d=s.data()||{};setProfile(d);setActivated(active(d));}catch(e){console.error(e)}finally{setLoading(false)}}),[]);
 useEffect(()=>{if(!user||!activated){setGroups([]);return;}return onSnapshot(query(collection(db,'communityGroups'),where('visibility','==','public'),limit(50)),s=>setGroups(s.docs.map(d=>({id:d.id,...d.data()}))),()=>setGroups([]))},[user,activated]);
 useEffect(()=>{if(!user||!activated){setMyGroups([]);return;}return onSnapshot(query(collection(db,'communityGroups'),where('memberIds','array-contains',user.uid),limit(50)),s=>setMyGroups(s.docs.map(d=>({id:d.id,...d.data()}))),()=>setMyGroups([]))},[user,activated]);
 useEffect(()=>{if(!selectedChat)return;return onSnapshot(query(collection(db,'communityChats',selectedChat.id,'messages'),orderBy('createdAt','asc'),limit(100)),s=>setMessages(s.docs.map(d=>({id:d.id,...d.data()}))),()=>setMessages([]))},[selectedChat]);
 useEffect(()=>{const q=normalize(search);if(!q||!activated||!user){setResults([]);return}let cancelled=false;(async()=>{try{const out:any[]=[];const exact=await getDoc(doc(db,'usernameIndex',q));if(exact.exists()&&exact.data().uid!==user.uid)out.push(exact.data());const names=await getDocs(query(collection(db,'usernameIndex'),where('fullNameLower','>=',q),where('fullNameLower','<=',q+'\uf8ff'),limit(20)));names.forEach(s=>{const d=s.data();if(d.uid!==user.uid&&!out.some(x=>x.uid===d.uid))out.push(d)});if(!cancelled)setResults(out.slice(0,20));}catch(e){if(!cancelled)setResults([])}})();return()=>{cancelled=true}},[search,activated,user?.uid]);
 const suggested=useMemo(()=>{if(!activated)return[];const interest=normalize(profile?.activeCategory||profile?.category||profile?.educationLevel||'');return [...groups].sort((a,b)=>{const aa=normalize(`${a.name} ${a.description}`),bb=normalize(`${b.name} ${b.description}`);return Number(bb.includes(interest))-Number(aa.includes(interest));}).slice(0,8)},[groups,profile,activated]);
 const guard=(fn:()=>void)=>{if(!activated){setNotice('Chat, group creation, joining and school-community access require an activated EDUWILLS account.');return}fn()};
 async function startChat(other:any){guard(async()=>{if(!user)return;setCreating(true);try{const id=`dm_${pair(user.uid,String(other.uid))}`;const ref=doc(db,'communityChats',id);await runTransaction(db,async tx=>{const old=await tx.get(ref);if(!old.exists())tx.set(ref,{type:'direct',participantIds:[user.uid,other.uid],participantProfiles:{[user.uid]:{username:profile.username||'',fullName:profile.fullName||''},[other.uid]:{username:other.username||'',fullName:other.fullName||''}},createdAt:serverTimestamp(),updatedAt:serverTimestamp()})});const s=await getDoc(ref);setSelectedChat({id,...s.data()});setSearch('');}catch(e:any){setNotice(e?.message||'Could not start chat.')}finally{setCreating(false)}})}
 async function send(){if(!user||!selectedChat||!draft.trim())return;const text=draft.trim();setDraft('');try{await addDoc(collection(db,'communityChats',selectedChat.id,'messages'),{senderId:user.uid,senderUsername:profile.username||'',text,createdAt:serverTimestamp()});await setDoc(doc(db,'communityChats',selectedChat.id),{updatedAt:serverTimestamp()},{merge:true})}catch{setNotice('Message could not be sent.')}}
 async function createGroup(){guard(async()=>{if(!user||!groupName.trim())return;setCreating(true);try{const ref=await addDoc(collection(db,'communityGroups'),{name:groupName.trim(),description:groupDescription.trim(),ownerId:user.uid,adminIds:[user.uid],memberIds:[user.uid],visibility:'public',type:'study',creatorRulesAccepted:false,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});setGroupName('');setGroupDescription('');setGroupOpen(false);location.assign(`${BASE}/dashboard/community/group/?id=${ref.id}`);}catch(e){setNotice(e?.message||'Could not create the group. Please try again.')}finally{setCreating(false)}})}
 async function join(g:any){guard(async()=>{try{await setDoc(doc(db,'communityJoinRequests',`${g.id}_${user.uid}`),{groupId:g.id,groupName:g.name,userId:user.uid,username:profile.username||'',groupOwnerId:g.ownerId,status:'pending',createdAt:serverTimestamp()},{merge:true});setNotice(`Join request sent to ${g.name}.`)}catch{setNotice('Could not send the join request.')}})}
 async function paySchool(){if(!user||!schoolName.trim())return;guard(async()=>{setPaying(true);setNotice('');try{const jwt=await user.getIdToken(true);const r=await fetch('https://us-central1-eduwills.cloudfunctions.net/schoolCommunityPayment',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${jwt}`},body:JSON.stringify({schoolName:schoolName.trim(),description:schoolDescription.trim()})});const data=await r.json().catch(()=>({}));if(!r.ok||!data.authorization_url)throw new Error(data.error||'Could not open school payment.');await setDoc(doc(db,'schoolCommunityPayments',String(data.reference)),{ownerId:user.uid,schoolName:schoolName.trim(),description:schoolDescription.trim(),amountNaira:2000,status:'pending',createdAt:serverTimestamp()},{merge:true});location.assign(data.authorization_url);}catch(e:any){setNotice(e?.message||'School payment could not be started.')}finally{setPaying(false)}})}
 if(loading)return <main className="grid min-h-screen place-items-center bg-paper text-slate-500">Loading community…</main>;
 return <main className="min-h-screen bg-paper pb-28 text-ink"><header className="sticky top-0 z-40 border-b border-slate-200/80 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><a href={`${BASE}/dashboard/`} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-black"><ArrowLeft size={17}/> Dashboard</a><div className="flex items-center gap-2 font-black"><span className="grid h-9 w-9 place-items-center rounded-xl bg-ink text-white"><BookOpen size={17}/></span>EDUWILLS</div></div></header>
 <div className="mx-auto max-w-6xl px-5 py-7 sm:px-8 sm:py-10"><section className="relative overflow-hidden rounded-[2rem] bg-ink p-7 text-white shadow-2xl sm:p-10"><p className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-[10px] font-black uppercase tracking-[.2em] text-cyan-200"><GraduationCap size={13}/>COMMUNITY</p><h1 className="mt-4 text-3xl font-black sm:text-5xl">Learn together. Connect intelligently.</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-300">Academic chat, suggested study groups and school communities in one organized space.</p></section>
 {!activated&&<section className="mt-5 flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-amber-950"><LockKeyhole className="shrink-0" size={19}/><div><b>Community is activation-only.</b><p className="mt-1 text-xs leading-5">Activate to search learners, start chats, create or join groups and access school communities.</p><a href={`${BASE}/dashboard/activation/`} className="mt-3 inline-flex rounded-xl bg-amber-950 px-4 py-2.5 text-xs font-black text-white">Activate account</a></div></section>}
 {notice&&<div className="mt-5 rounded-2xl border border-cyan-100 bg-cyan-50 p-4 text-sm font-bold text-cyan-950">{notice}</div>}
 <div className="mt-6 grid grid-cols-3 gap-2 rounded-[1.4rem] border border-slate-200 bg-white p-1.5 shadow-sm"><button onClick={()=>setSection('chat')} className={`rounded-xl px-3 py-3 text-xs font-black ${section==='chat'?'bg-ink text-white':'text-slate-500'}`}><MessageCircle className="mx-auto mb-1" size={18}/>CHAT</button><button onClick={()=>setSection('groups')} className={`rounded-xl px-3 py-3 text-xs font-black ${section==='groups'?'bg-ink text-white':'text-slate-500'}`}><Users className="mx-auto mb-1" size={18}/>GROUPS</button><button onClick={()=>setSection('schools')} className={`rounded-xl px-3 py-3 text-xs font-black ${section==='schools'?'bg-ink text-white':'text-slate-500'}`}><School className="mx-auto mb-1" size={18}/>SCHOOLS</button></div>
 {section==='chat'&&<section className="mt-5 grid gap-5 lg:grid-cols-[.85fr_1.15fr]"><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2 rounded-2xl border border-slate-200 bg-paper px-4 py-3"><Search size={18} className="text-slate-400"/><input disabled={!activated} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name or unique username…" className="min-w-0 flex-1 bg-transparent text-sm font-bold outline-none"/></div>{activated&&search&&<div className="mt-3 space-y-2">{results.map(r=><button key={r.uid} onClick={()=>startChat(r)} className="flex w-full items-center gap-3 rounded-2xl border border-slate-200 p-3 text-left"><span className="grid h-10 w-10 place-items-center rounded-full bg-ink text-white text-xs font-black">{String(r.fullName||r.username||'?')[0]}</span><span className="min-w-0 flex-1"><b className="block truncate text-sm">{r.fullName||'Learner'}</b><small className="text-slate-500">@{r.username}</small></span><ArrowRight size={16}/></button>)}{!results.length&&<p className="rounded-xl bg-slate-50 p-4 text-xs font-bold text-slate-500">No learner found.</p>}</div>}<div className="mt-5 rounded-2xl bg-slate-50 p-4"><p className="font-black">Username rule</p><p className="mt-1 text-xs leading-5 text-slate-500">Usernames are intended to be unique account handles. The registration system must reject a handle already reserved by another account.</p></div></div><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black">{selectedChat?'Academic conversation':'Start a conversation'}</h2>{selectedChat?<><div className="mt-4 h-80 space-y-3 overflow-y-auto rounded-2xl bg-slate-50 p-4">{messages.map(m=><div key={m.id} className={`max-w-[85%] rounded-2xl px-4 py-3 text-sm ${m.senderId===user.uid?'ml-auto bg-ink text-white':'border border-slate-200 bg-white'}`}><small className="opacity-60">@{m.senderUsername||'learner'}</small><p className="mt-1 whitespace-pre-wrap">{m.text}</p></div>)}{!messages.length&&<p className="py-20 text-center text-xs font-bold text-slate-400">No messages yet.</p>}</div><div className="mt-3 flex gap-2"><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Write an academic message…" className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-paper px-4 py-3 text-sm font-bold"/><button onClick={send} className="grid h-12 w-12 place-items-center rounded-xl bg-ink text-white"><Send size={17}/></button></div></>:<div className="grid h-96 place-items-center rounded-2xl bg-slate-50 text-center p-8"><div><MessageCircle className="mx-auto text-slate-300" size={35}/><p className="mt-3 font-black">Search for a learner above.</p></div></div>}</div></section>}
 {section==='groups'&&<section className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-700">DISCOVER</p><h2 className="text-xl font-black">Suggested study groups</h2></div><button disabled={!activated} onClick={()=>setGroupOpen(v=>!v)} className="inline-flex items-center gap-2 rounded-xl bg-ink px-4 py-3 text-xs font-black text-white disabled:opacity-40"><Plus size={15}/>Create</button></div>{groupOpen&&<div className="mt-4 space-y-3 rounded-2xl bg-slate-50 p-4"><input value={groupName} onChange={e=>setGroupName(e.target.value)} placeholder="Group name" className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold"/><textarea value={groupDescription} onChange={e=>setGroupDescription(e.target.value)} placeholder="Purpose / subjects" className="min-h-24 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold"/><button disabled={creating} onClick={createGroup} className="rounded-xl bg-cyan-700 px-4 py-3 text-xs font-black text-white">{creating?'Creating…':'Create group'}</button></div>}<div className="mt-5 space-y-3">{suggested.map(g=><div key={g.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-cyan-50 text-cyan-700"><Users size={19}/></span><div className="min-w-0 flex-1"><b className="block">{g.name}</b><p className="mt-1 text-xs leading-5 text-slate-500">{g.description||'Study together.'}</p><small className="font-black text-slate-400">{Array.isArray(g.memberIds)?g.memberIds.length:0} members · {Array.isArray(g.adminIds)?g.adminIds.length:1} admins</small></div><button disabled={!activated||g.memberIds?.includes(user.uid)} onClick={()=>join(g)} className="self-center rounded-xl border border-slate-200 px-3 py-2 text-xs font-black disabled:opacity-40">{g.memberIds?.includes(user.uid)?'Joined':'Join'}</button></div></div>)}{!suggested.length&&<p className="rounded-2xl bg-slate-50 p-8 text-center text-xs font-bold text-slate-400">No groups yet. Create the first study group.</p>}</div></div><div className="rounded-3xl border border-cyan-100 bg-cyan-50 p-5"><ShieldCheck className="text-cyan-700" size={22}/><h3 className="mt-3 font-black">Group administration</h3><p className="mt-2 text-xs leading-6 text-slate-600">Every group has at least one admin. The creator is the first admin and can appoint additional admins.</p><p className="mt-5 text-xs font-black">Your groups: {myGroups.length}</p></div></section>}
 {section==='schools'&&<section className="mt-5 grid gap-5 lg:grid-cols-2"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><School className="text-cyan-700" size={24}/><p className="mt-4 text-[10px] font-black uppercase tracking-[.18em] text-cyan-700">SCHOOL COMMUNITY</p><h2 className="mt-1 text-2xl font-black">Open a school space</h2><p className="mt-3 text-sm leading-6 text-slate-500">A school community has a fixed opening fee of <b>₦2,000</b>. Pay securely through Paystack; the school is created only after the verified payment webhook succeeds.</p>{activated?<div className="mt-5 space-y-3"><input value={schoolName} onChange={e=>setSchoolName(e.target.value)} placeholder="School name" className="w-full rounded-xl border border-slate-200 bg-paper px-4 py-3 text-sm font-bold"/><textarea value={schoolDescription} onChange={e=>setSchoolDescription(e.target.value)} placeholder="School community description" className="min-h-24 w-full rounded-xl border border-slate-200 bg-paper px-4 py-3 text-sm font-bold"/><button disabled={paying} onClick={paySchool} className="flex w-full items-center justify-center gap-2 rounded-xl bg-ink px-4 py-3.5 text-sm font-black text-white disabled:opacity-50">{paying?'Opening secure checkout…':'Pay ₦2,000 & open school community'} <ArrowRight size={16}/></button></div>:null}</div><div className="rounded-3xl border border-amber-100 bg-amber-50 p-6"><CheckCircle2 className="text-amber-700" size={23}/><h3 className="mt-3 font-black">School rules</h3><ul className="mt-3 space-y-2 text-xs leading-6 text-slate-700"><li>• ₦2,000 one-time opening fee.</li><li>• Owner becomes the first administrator.</li><li>• Admins can appoint additional administrators.</li><li>• Payment status is verified server-side before activation.</li><li>• School membership and school administration remain separate from ordinary study groups.</li></ul></div></section>}
 </div><nav className="fixed bottom-0 left-0 right-0 z-50 px-3 pb-[max(8px,env(safe-area-inset-bottom))] pt-2"><div className="mx-auto flex max-w-lg items-center gap-1 rounded-[1.5rem] border border-slate-200/80 bg-white/95 p-1.5 shadow-2xl backdrop-blur"><a href={`${BASE}/dashboard/`} className="flex min-w-0 flex-1 flex-col items-center gap-1 rounded-2xl py-2 text-[9px] font-black text-slate-500"><GraduationCap size={18}/><span>HOME</span></a><button onClick={()=>setSection('chat')} className={`flex min-w-0 flex-1 flex-col items-center gap-1 rounded-2xl py-2 text-[9px] font-black ${section==='chat'?'bg-ink text-white':'text-slate-500'}`}><MessageCircle size={18}/><span>CHAT</span></button><button onClick={()=>setSection('groups')} className={`flex min-w-0 flex-1 flex-col items-center gap-1 rounded-2xl py-2 text-[9px] font-black ${section==='groups'?'bg-ink text-white':'text-slate-500'}`}><Users size={18}/><span>GROUPS</span></button><button onClick={()=>setSection('schools')} className={`flex min-w-0 flex-1 flex-col items-center gap-1 rounded-2xl py-2 text-[9px] font-black ${section==='schools'?'bg-ink text-white':'text-slate-500'}`}><School size={18}/><span>SCHOOLS</span></button><a href={`${BASE}/dashboard/personal/`} className="flex min-w-0 flex-1 flex-col items-center gap-1 rounded-2xl py-2 text-[9px] font-black text-slate-500"><MoreHorizontal size={18}/><span>MORE</span></a></div></nav></main>;
}
