import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Study Guide & Exam Prep Tips | EDUWILLS',
  description: 'Free practical study tips, WAEC, JAMB, NECO and book-learning guidance for Nigerian students.',
  alternates: { canonical: 'https://chineduwilliams739-commits.github.io/eduwills/blog/' },
};

const posts = [
  {title:'How to Prepare for JAMB in 30 Days',tag:'JAMB / UTME',description:'A practical 30-day routine for focused revision, CBT practice, error review and book-based quizzes.',sections:['Start with a diagnostic quiz','Build a daily revision timetable','Practise under CBT-style time pressure','Review mistakes instead of only chasing scores']},
  {title:'WAEC Study Tips: How to Stop Forgetting What You Read',tag:'WAEC',description:'Use active recall, spaced review and question practice to turn reading into durable learning.',sections:['Read in focused blocks','Close the book and recall key ideas','Turn chapters into questions','Revisit difficult material later']},
  {title:'NECO Exam Preparation: A Smarter Revision Plan',tag:'NECO',description:'Simple ways to organise subjects, identify weak areas and practise consistently before NECO.',sections:['Map your syllabus','Prioritise weak topics','Mix old and new revision','Track your quiz performance']},
  {title:'How to Turn Any Book into a Practice Quiz',tag:'Book Learning',description:'A guide to studying novels, textbooks and set books by testing yourself on actual content.',sections:['Choose the exact book','Give precise quiz instructions','Focus on events, characters and details','Use scores to decide what to revise next']},
];

export default function BlogPage(){return <main className="min-h-screen bg-paper text-ink"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5"><Link href="/eduwills/" className="text-xl font-black">EDUWILLS</Link><Link href="/eduwills/" className="rounded-xl bg-eduBlue px-4 py-2 text-sm font-black text-white">Try the Quiz Generator</Link></div></header><section className="mx-auto max-w-6xl px-5 pb-10 pt-14"><p className="text-sm font-black uppercase tracking-wider text-eduBlue">EDUWILLS Study Guide</p><h1 className="mt-3 max-w-3xl text-4xl font-black tracking-tight sm:text-5xl">Study smarter for WAEC, JAMB, NECO and beyond.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-600">Free practical study strategies for Nigerian students, from book-based revision to CBT practice and active recall.</p></section><section className="mx-auto grid max-w-6xl gap-5 px-5 pb-16 sm:grid-cols-2">{posts.map(post=><article key={post.title} className="rounded-[2rem] border border-slate-200 bg-white p-7 shadow-soft"><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-black text-indigo-700">{post.tag}</span><h2 className="mt-5 text-2xl font-black">{post.title}</h2><p className="mt-3 leading-7 text-slate-600">{post.description}</p><ul className="mt-4 space-y-2 text-slate-600">{post.sections.map(section=><li key={section}>• {section}</li>)}</ul><Link href="/eduwills/" className="mt-6 inline-flex font-black text-eduBlue">Practise with EDUWILLS →</Link></article>)}</section><footer className="border-t border-slate-200 bg-white px-5 py-8 text-center text-sm text-slate-500">EDUWILLS is an independent study tool and is not affiliated with WAEC, JAMB or NECO.</footer></main>}
