'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,Check,ImagePlus,MessageCircle,Search,Send,UserRound,X} from 'lucide-react';
import {onAuthStateChanged} from 'firebase/auth';
import {addDoc,collection,doc,getDoc,getDocs,limit,onSnapshot,orderBy,query,serverTimestamp,setDoc,where} from 'firebase/firestore';
import {auth,db} from '@/lib/firebase';
import DeviceImageUpload from '@/components/DeviceImageUpload';
const BASE='/eduwills';
const active=(d:any)=>{const e=d?.activationExpiresAt?.toMillis?.()||Date.parse(String(d?.activationExpiresAt||''))||0;return(d?.activationStatus==='active'||d?.activated===true||d?.williTokenActive===true||d?.activationActive===true||d?.isActive===true)&&(!e||e>Date.now())};
const display=(d:any)=>({uid:String(d?.uid||''),username:String(d?.username||''),fullName:String(d?.fullName||d?.name||d?.username||'Learner'),photoURL:String(d?.photoURL||d?.avatarUrl||'')});
function chatId(a:string,b:string){return[a,b].sort().join('_')}
export default function Chat(){
 const[user,setUser]=useState<any>(null),[profile,setProfile]=useState<any>({}),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[results,setResults]=useState<any[]>([]),[chats,setChats]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[messages,setMessages]=useState<any[]>([]),[draft,setDraft]=useState(''),[image,setImage]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>onAuthStateChanged(auth,async u=>{if(!u){location.replace(BASE+'/login/');return}const s=await getDoc(doc(db,'users',u.uid));const p=s.data()||{};if(!active(p)){location.replace(BASE+'/dashboard/activation/');return}setUser(u);setProfile(p);setLoading(false)}),[]);
 useEffect(()=>{if(!user)return;return onSnapshot(query(collection(db,'communityChats'),where('participantIds','array-contains',user.uid),limit(100)),s=>{const list=s.docs.map(x=>({id:x.id,...x.data()}));list.sort((a,b)=>{const ta=a.updatedAt?.toMillis?.()||0,tb=b.updatedAt?.toMillis?.()||0;return tb-ta});setChats(list)})},[user?.uid]);
 useEffect(()=>{if(!selected||!user)return;return onSnapshot(query(collection(db,'communityChats',selected.id,'messages'),orderBy('createdAt','asc'),limit(300)),s=>setMessages(s.docs.map(x=>({id:x.id,...x.data()}))))},[selected?.id,user?.uid]);
 useEffect(()=>{let cancelled=false;async function find(){const term=search.trim().toLowerCase();if(!term){setResults([]);return}try{const exact=await getDoc(doc(db,'usernameIndex',term));const out:any[]=[];if(exact.exists()){const d=exact.data();if(d.uid!==user?.uid)out.push(display({...d,username:d.username||term}))}if(!out.length){const snap=await getDocs(query(collection(db,'usernameIndex'),limit(200)));for(const x of snap.docs){const d=x.data();const name=String(d.fullName||'').toLowerCase(),un=String(d.username||x.id).toLowerCase();if(d.uid!==user?.uid&&(un.includes(term)||name.includes(term)))out.push(display({...d,uid:d.uid,username:d.username||x.id}));if(out.length>=20)break}}if(!cancelled)setResults(out)}catch(e:any){if(!cancelled)setNotice(e?.message||'User search failed.')}}find();return()=>{cancelled=true}},[search,user?.uid]);
 const chatRows=useMemo(()=>chats.map(c=>{const ids=Array.isArray(c.participantIds)?c.participantIds:[];const other=ids.find((x:string)=>x!==user?.uid);return {...c,otherId:other,person:display(c.participantProfiles?.[other]||{uid:other,username:c.otherUsername,fullName:c.otherName,photoURL:c.otherPhotoURL})}}),[chats,user?.uid]);
 async function openPerson(person:any){const id=chatId(user.uid,person.uid);const ref=doc(db,'communityChats',id);await setDoc(ref,{participantIds:[user.uid,person.uid],ownerId:user.uid,participantProfiles:{[user.uid]:display({...profile,uid:user.uid,username:profile.username}) ,[person.uid]:person},otherName:person.fullName,otherUsername:person.username,otherPhotoURL:person.photoURL,updatedAt:serverTimestamp()},{merge:true});setSelected({id,person});setSearch('');setResults([])}
 async function send(){if((!draft.trim()&&!image)||!selected||busy)return;const text=draft.trim(),imageUrl=image;setDraft('');setImage('');setBusy(true);try{await addDoc(collection(db,'communityChats',selected.id,'messages'),{senderId:user.uid,senderName:profile.fullName||'Learner',senderUsername:profile.username||'',senderPhotoURL:profile.photoURL||profile.avatarUrl||'',text,imageUrl,createdAt:serverTimestamp()});await setDoc(doc(db,'communityChats',selected.id),{lastMessage:text||'📷 Image',lastSenderId:user.uid,updatedAt:serverTimestamp()},{merge:true})}catch(e:any){setDraft(text);setImage(imageUrl);setNotice(e?.message||'Message could not be sent.')}finally{setBusy(false)}}
 if(loading)return <main className="grid min-h-screen place-items-center bg-paper font-bold text-slate-500">Loading chat…</main>;
 return <main className="min-h-screen bg-[#eef3f7] text-ink pb-24"><header className="sticky top-0 z-40 border-b bg-white/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-6xl items-center gap-3 px-4"><a href={BASE+'/dashboard/community/'} className="grid h-10 w-10 place-items-center rounded-full hover:bg-slate-100"><ArrowLeft size={20}/></a><div className="flex-1"><p className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-700">EDUWILLS CHAT</p><h1 className="text-lg font-black">Academic conversations</h1></div><a href={BASE+'/dashboard/personal/'} className="grid h-10 w-10 place-items-center overflow-hidden rounded-full bg-ink text-white">{profile.photoURL||profile.avatarUrl?<img src={profile.photoURL||profile.avatarUrl} className="h-full w-full object-cover"/>:<UserRound size={18}/>}</a></div></header>
 <div className="mx-auto grid max-w-6xl gap-4 p-3 sm:p-5 lg:grid-cols-[340px_1fr]"><aside className={`rounded-3xl border bg-white shadow-sm ${selected?'hidden lg:block':''}`}><div className="border-b p-4"><div className="flex items-center gap-2 rounded-2xl bg-slate-100 px-4 py-3"><Search size={18} className="text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by name or username…" className="min-w-0 flex-1 bg-transparent text-sm font-bold outline-none"/>{search&&<button onClick={()=>setSearch('')}><X size={16}/></button>}</div></div>{results.length>0&&<div className="border-b p-2">{results.map(p=><button key={p.uid} onClick={()=>openPerson(p)} className="flex w-full items-center gap-3 rounded-2xl p-3 text-left hover:bg-slate-50"><Avatar p={p}/><span className="min-w-0"><b className="block truncate text-sm">{p.fullName}</b><small className="text-xs text-slate-400">@{p.username}</small></span></button>)}</div>}<div className="p-3"><div className="mb-2 flex items-center justify-between"><p className="text-[10px] font-black uppercase tracking-[.18em] text-slate-400">Recent chats</p><span className="rounded-full bg-cyan-50 px-2 py-1 text-[10px] font-black text-cyan-700">{chatRows.length}</span></div>{chatRows.length?chatRows.map(c=><button key={c.id} onClick={()=>setSelected({id:c.id,person:c.person})} className="flex w-full items-center gap-3 rounded-2xl p-3 text-left hover:bg-slate-50"><Avatar p={c.person}/><span className="min-w-0 flex-1"><b className="block truncate text-sm">{c.person.fullName}</b><small className="block truncate text-xs text-slate-400">{c.lastMessage||'Start a conversation'}</small></span>{c.unreadCount>0&&<span className="grid h-6 min-w-6 place-items-center rounded-full bg-cyan-600 px-1 text-[9px] font-black text-white">{c.unreadCount>99?'99+':c.unreadCount}</span>}</button>):<div className="rounded-2xl border border-dashed p-6 text-center"><MessageCircle className="mx-auto text-slate-300" size={30}/><p className="mt-2 text-sm font-black">No previous chats</p><p className="mt-1 text-xs leading-5 text-slate-400">Search for a learner above to start your first conversation.</p></div>}</div></aside>
 <section className={`flex min-h-[72vh] flex-col overflow-hidden rounded-3xl border bg-white shadow-sm ${!selected?'hidden lg:flex':''}`}>{selected?<><div className="flex items-center gap-3 border-b p-4"><button onClick={()=>setSelected(null)} className="grid h-9 w-9 place-items-center rounded-full hover:bg-slate-100 lg:hidden"><ArrowLeft size={18}/></button><Avatar p={selected.person}/><div className="min-w-0"><h2 className="truncate font-black">{selected.person.fullName}</h2><p className="text-xs text-slate-400">@{selected.person.username}</p></div></div><div className="flex-1 space-y-3 overflow-y-auto bg-[#f7f9fb] p-4">{messages.length?messages.map(m=><div key={m.id} className={'flex '+(m.senderId===user.uid?'justify-end':'')}><div className={'max-w-[82%] rounded-2xl px-3 py-2 '+(m.senderId===user.uid?'bg-ink text-white':'border bg-white')} >{m.imageUrl&&<img src={m.imageUrl} className="mb-2 max-h-72 rounded-xl object-cover"/>}{m.text&&<p className="whitespace-pre-wrap text-sm leading-6">{m.text}</p>}<div className="mt-1 flex justify-end gap-1 text-[9px] opacity-60">{m.createdAt?.toDate?m.createdAt.toDate().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'Sending…'}</div></div></div>):<div className="grid h-full place-items-center text-center"><div><MessageCircle className="mx-auto text-slate-300" size={42}/><p className="mt-3 font-black">Start your academic conversation</p><p className="mt-1 text-xs text-slate-400">Keep it respectful, useful and educational.</p></div></div>}</div><div className="border-t bg-white p-3"><div className="mb-2 flex items-center gap-2">{image&&<div className="relative"><img src={image} className="h-16 w-16 rounded-xl object-cover"/><button onClick={()=>setImage('')} className="absolute -right-2 -top-2 rounded-full bg-ink p-1 text-white"><X size={12}/></button></div>}<DeviceImageUpload uid={user.uid} path="chatImages" label="Image" onUploaded={setImage}/></div><div className="flex gap-2"><textarea value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Write a message…" rows={1} className="min-h-11 flex-1 resize-none rounded-2xl border bg-slate-50 px-4 py-3 text-sm font-semibold outline-none"/><button disabled={busy||(!draft.trim()&&!image)} onClick={send} className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-ink text-white disabled:opacity-40"><Send size={17}/></button></div></div></>:<div className="grid flex-1 place-items-center p-10 text-center"><MessageCircle className="text-cyan-600" size={48}/><h2 className="mt-4 text-2xl font-black">Your chats</h2><p className="mt-2 max-w-md text-sm leading-6 text-slate-500">Search for a learner to start a conversation, or select one of your previous chats from the list.</p></div>}</section></div></main>;
}
function Avatar({p}:{p:any}){return <div className="grid h-11 w-11 shrink-0 place-items-center overflow-hidden rounded-full bg-ink text-white font-black">{p?.photoURL?<img src={p.photoURL} className="h-full w-full object-cover"/>:String(p?.fullName||p?.username||'L')[0]}</div>}
