'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, Check, CheckCircle2, FileText, GraduationCap, Search, Sparkles } from 'lucide-react';
import { onAuthStateChanged } from 'firebase/auth';
import { doc, getDoc } from 'firebase/firestore';
import { auth, db } from '@/lib/firebase';

const BASE='/eduwills';
const SUBJECTS={
 primary:['English Studies','Mathematics','Basic Science','Social Studies','Civic Education'],
 junior:['English Studies','Mathematics','Basic Science','Basic Technology','Social Studies','Civic Education','Computer Studies','Business Studies','French','Agricultural Science','Home Economics'],
 senior:['English Language','Mathematics','Biology','Chemistry','Physics','Economics','Government','Literature in English','Civic Education','Computer Studies','Geography','Commerce','Accounting','Agricultural Science','Christian Religious Studies','Islamic Studies','French','History','Further Mathematics'],
} as const;
const EXAMS:Record<'primary'|'junior'|'senior',string[]>={primary:['Normal Test'],junior:['BECE','NECO','Normal Test'],senior:['JAMB','WAEC','NECO','Normal Test']};
function categoryId(v:string|null):'primary'|'junior'|'senior'{const x=String(v||'').toLowerCase();if(x==='primary')return'primary';if(x==='junior'||x==='jss'||x==='junior-secondary')return'junior';return'senior'}
export default function CategoryQuizPage(){const[category,setCategory]=useState<'primary'|'junior'|'senior'>('senior');const[mode,setMode]=useState('WAEC');const[selected,setSelected]=useState<string[]>([]);const[search,setSearch]=useState('');const[allowed,setAllowed]=useState(false);const[loading,setLoading]=useState(true);const[message,setMessage]=useState('');
 useEffect(()=>{const p=new URLSearchParams(window.location.search);const id=categoryId(p.get('category'));const requested=(p.get('mode')||'waec').toUpperCase().replace(/-/g,' ');const exams=EXAMS[id];setCategory(id);setMode(exams.find(x=>x.toUpperCase()===requested)||exams[0]);const passed=(p.get('subjects')||'').split('|').filter(Boolean);setSelected(passed.length?passed:[SUBJECTS[id][0]]);const off=onAuthStateChanged(auth,async u=>{if(!u){window.location.replace(`${BASE}/login/`);return}try{const s=await getDoc(doc(db,'users',u.uid));const d=s.data()||{};const values=[...(Array.isArray(d.categories)?d.categories:[]),...(Array.isArray(d.educationLevels)?d.educationLevels:[]),...(Array.isArray(d.schoolLevels)?d.schoolLevels:[]),d.category,d.educationLevel,d.schoolLevel].map(x=>String(x||'').toLowerCase());setAllowed(values.some(v=>v===id||v.includes(id)));}catch{setAllowed(false)}finally{setLoading(false)}});return()=>off()},[]);
 const subjects=SUBJECTS[category];const filtered=useMemo(()=>subjects.filter(s=>s.toLowerCase().includes(search.trim().toLowerCase())),[subjects,search]);
 useEffect(()=>{const valid=selected.filter(s=>subjects.includes(s as never));setSelected(valid.length?valid:[subjects[0]])},[mode,category]);
 function toggle(s:string){setSelected(v=>v.includes(s)?v.filter(x=>x!==s):[...v,s])}
 function begin(){if(!selected.length){setMessage('Select at least one subject.');return}const p=new URLSearchParams({category,mode,subjects:selected.join('|')});window.location.assign(`${BASE}/dashboard/category-quiz/test/?${p.toString()}`)}
 if(loading)return <main className="min-h-screen bg-paper p-8 text-center font-bold text-slate-500">Loading exam setup…</main>;
 if(!allowed)return <main className="min-h-screen bg-paper p-6"><div className="mx-auto max-w-xl rounded-3xl border border-amber-200 bg-amber-50 p-7 text-amber-950"><h1 className="text-xl font-black">Category not assigned</h1><p className="mt-2 text-sm">This learning category is not currently assigned to your account.</p><a href={`${BASE}/dashboard/personal/`} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-amber-950 px-4 py-3 text-sm font-black text-white">Switch category <ArrowRight size={16}/></a></div></main>;
 return <main className="min-h-screen bg-paper pb-10 text-ink"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-4 sm:px-8"><a href={`${BASE}/dashboard/category/?category=${category}`} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2 text-sm font-black"><ArrowLeft size={17}/> Category</a><span className="inline-flex items-center gap-2 font-black"><BookOpen size={18}/> EDUWILLS</span></div></header><div className="mx-auto max-w-5xl px-5 py-8 sm:px-8"><section className="rounded-[2rem] bg-gradient-to-br from-slate-950 via-indigo-950 to-cyan-900 p-7 text-white sm:p-10"><div className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-[10px] font-black uppercase tracking-[.2em] text-cyan-200"><GraduationCap size={13}/> EXAM CENTRE</div><h1 className="mt-4 text-3xl font-black sm:text-4xl">Choose your examination and subjects.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">You can switch between the examinations available to your learning level and select more than one subject.</p></section>
 <section className="mt-6 rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex items-center gap-3"><FileText className="text-cyan-600" size={22}/><div><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-700">1. Examination</p><h2 className="mt-1 text-xl font-black">What are you writing?</h2></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{EXAMS[category].map(x=><button key={x} type="button" onClick={()=>setMode(x)} className={`rounded-2xl border p-4 text-left ${mode===x?'border-cyan-500 bg-cyan-50 shadow-sm':'border-slate-200 hover:border-cyan-300'}`}><div className="flex items-center justify-between gap-2"><span className="font-black">{x}</span>{mode===x&&<CheckCircle2 className="text-cyan-600" size={18}/>}</div></button>)}</div></section>
 <section className="mt-6 rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-700">2. Subjects</p><h2 className="mt-1 text-xl font-black">Select one or more</h2><p className="mt-1 text-sm text-slate-500">{selected.length} selected · {subjects.length} available for {mode}</p></div><div className="relative w-full sm:w-72"><Search className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search subjects…" className="w-full rounded-xl border border-slate-200 bg-paper py-3 pl-10 pr-4 text-sm font-bold outline-none focus:border-cyan-400"/></div></div><div className="mt-5 grid max-h-[30rem] gap-2 overflow-y-auto pr-1 sm:grid-cols-2">{filtered.map(s=><button key={s} type="button" onClick={()=>toggle(s)} className={`flex items-center justify-between gap-3 rounded-xl border p-3.5 text-left text-sm font-black ${selected.includes(s)?'border-cyan-400 bg-cyan-50 text-cyan-950':'border-slate-200 hover:border-cyan-300'}`}><span>{s}</span><span className={`grid h-6 w-6 shrink-0 place-items-center rounded-md border ${selected.includes(s)?'border-cyan-600 bg-cyan-600 text-white':'border-slate-300 bg-white'}`}>{selected.includes(s)&&<Check size={14}/>}</span></button>)}</div><div className="mt-5 flex flex-wrap gap-2">{selected.map(s=><span key={s} className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-black">{s}</span>)}</div>{message&&<p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm font-bold text-amber-800">{message}</p>}<button type="button" onClick={begin} className="mt-6 flex w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-indigo-600 to-cyan-500 px-5 py-4 text-sm font-black text-white shadow-lg">Continue with {selected.length} subject{selected.length===1?'':'s'} <Sparkles size={17}/><ArrowRight size={17}/></button></section></div></main>;
}
