import Link from 'next/link';
import {notFound} from 'next/navigation';
const BASE='/eduwills';
const data:Record<string,{title:string;intro:string;sections:[string,string][]}>={
 'waec-practice-questions':{title:'WAEC Practice Questions: How to Study Smarter',intro:'WAEC preparation is stronger when you combine reading, active recall and timed practice instead of rereading notes alone.',sections:[['Start with the books and topics you actually need','List the subjects, books and topics you are preparing for. Use a realistic weekly plan and revisit difficult areas after each practice session.'],['Use practice questions actively','After studying a chapter, close the book and answer questions from memory. Review every mistake and write down why the correct answer is correct.'],['Use EDUWILLS for book-focused practice','EDUWILLS can generate quizzes from the books you study, helping you turn reading into active practice. It is an independent learning tool, not an official WAEC service.']]},
 'jamb-utme-practice':{title:'JAMB and UTME Practice: Build a Better Study Routine',intro:'JAMB and UTME preparation benefits from short, regular practice sessions, careful review of mistakes and timed tests.',sections:[['Practise under time pressure','Use timed sessions as your preparation develops. Record which question types take the longest and return to those topics.'],['Review mistakes instead of only chasing scores','A wrong answer is useful when you understand the reason behind it. Keep a simple mistake log and revisit it regularly.'],['Mix reading with quizzes','Use your textbooks and class materials for learning, then use practice questions to test whether you can recall and apply what you studied.']]},
 'neco-exam-preparation':{title:'NECO Exam Preparation Guide for Nigerian Students',intro:'A steady revision routine can make NECO preparation more manageable. Focus on coverage, recall and repeated practice.',sections:[['Make a topic checklist','Break each subject into topics and mark what you understand, what needs revision and what still feels difficult.'],['Practise after every study block','A short quiz after reading helps expose gaps that passive rereading can hide.'],['Keep reviewing older material','Return to previous topics instead of studying only the newest chapter. Spaced review helps you remember more over time.']]},
 'book-quiz-generator':{title:'Turn Any Book Into a Practice Quiz',intro:'A book quiz generator can help learners turn reading into active recall and make revision more interactive.',sections:[['Find the book','Start with the title and author of the book you are studying.'],['Give clear instructions','Tell the quiz generator the number of questions, difficulty, question type and any chapter or topic restrictions you want.'],['Review your results','Use explanations and mistakes to decide what to study next. AI-generated questions should be checked against your book when accuracy is especially important.']]}
};
export function generateStaticParams(){return Object.keys(data).map(slug=>({slug}));}
export default async function Guide({params}:{params:{slug:string}}){const g=data[params.slug];if(!g)notFound();return <main className="min-h-screen bg-paper text-ink"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-4xl items-center justify-between px-5 py-5"><Link href={`${BASE}/study-guides/`} className="font-black">EDUWILLS Study Guides</Link><Link href={`${BASE}/signup/`} className="rounded-xl bg-eduBlue px-4 py-2.5 text-sm font-black text-white">Try EDUWILLS</Link></div></header><article className="mx-auto max-w-4xl px-5 py-12"><p className="text-xs font-black uppercase tracking-[.2em] text-eduBlue">Nigerian exam & study guide</p><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">{g.title}</h1><p className="mt-6 text-lg leading-8 text-slate-600">{g.intro}</p><div className="mt-10 space-y-7">{g.sections.map(([h,p])=><section key={h}><h2 className="text-2xl font-black">{h}</h2><p className="mt-3 leading-7 text-slate-600">{p}</p></section>)}</div><div className="mt-12 rounded-[2rem] bg-ink p-8 text-white"><h2 className="text-2xl font-black">Ready to practise?</h2><p className="mt-3 text-sm leading-6 text-slate-300">Use EDUWILLS to turn the books you study into focused quizzes.</p><Link href={`${BASE}/signup/`} className="mt-5 inline-flex rounded-xl bg-white px-5 py-3 font-black text-ink">Start learning</Link></div></article></main>}
