import { getAI, getGenerativeModel, GoogleAIBackend, Schema } from 'firebase/ai';
import app from '@/lib/firebase';

export type QuizBook={title:string;author:string};
export type QuizQuestion={question:string;options:string[];answer:number;explanation?:string;evidence?:string};
export type BookSearchResult={title:string;authors:string[];source:string};
const ai=getAI(app,{backend:new GoogleAIBackend()});
const schema=Schema.object({properties:{questions:Schema.array({items:Schema.object({properties:{question:Schema.string(),options:Schema.array({items:Schema.string()}),answer:Schema.integer(),evidence:Schema.string()}})})}});
const grounded=getGenerativeModel(ai,{model:'gemini-3.6-flash',generationConfig:{responseMimeType:'application/json',responseSchema:schema,temperature:.65,maxOutputTokens:10000},tools:[{googleSearch:{}}]});
const fallback=getGenerativeModel(ai,{model:'gemini-3.5-flash-lite',generationConfig:{responseMimeType:'application/json',responseSchema:schema,temperature:.55,maxOutputTokens:9000},tools:[{googleSearch:{}}]});
const plain=getGenerativeModel(ai,{model:'gemini-3.6-flash',generationConfig:{temperature:.3,maxOutputTokens:500}});
const CACHE='v11-diverse-content';
const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
const clean=(s:string)=>String(s||'').replace(/```[\s\S]*?```/g,'').replace(/`([^`]+)`/g,'$1').replace(/\*\*(.*?)\*\*/g,'$1').replace(/__(.*?)__/g,'$1').replace(/^\s*#{1,6}\s*/gm,'').replace(/^\s*[-*]\s+/gm,'').replace(/\s+/g,' ').trim();
const getCache=<T,>(k:string):T|null=>{try{const x=JSON.parse(localStorage.getItem(k)||'null');return x&&x.e>Date.now()?x.v:null}catch{return null}};
const setCache=(k:string,v:any,ttl:number)=>{try{localStorage.setItem(k,JSON.stringify({e:Date.now()+ttl,v}))}catch{}};
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function aiCall(m:any,p:string,ms=60000){return Promise.race([m.generateContent(p),new Promise((_,rej)=>setTimeout(()=>rej(new Error('AI timeout')),ms))]) as Promise<any>}
function json(text:string){const s=String(text||'').replace(/^```json\s*/i,'').replace(/\s*```$/,'').trim();try{return JSON.parse(s)}catch{const a=s.indexOf('{'),b=s.lastIndexOf('}');if(a>=0&&b>a)return JSON.parse(s.slice(a,b+1));throw new Error('Invalid AI response')}}
const SCARS={title:'SCARS: Nigeria’s Journey and the Boko Haram Conundrum',author:'Gen. Lucky Irabor'};
const SANYA={title:'Sànyà',author:'Oyin Olugbile'};
const scars=(s:string)=>{const n=norm(s);return n.includes('scars')||n.includes('irabor')};
const sanya=(b:QuizBook)=>norm(b.title)==='sanya'||norm(b.author).includes('oyin olugbile');

export async function searchBookAuthors(kind:'title'|'author',value:string):Promise<BookSearchResult[]>{
 const q=value.trim(),n=norm(q);if(!q)return[];
 if(scars(q))return[{title:SCARS.title,authors:[SCARS.author],source:'EDUWILLS verified catalogue'}];
 if(n.includes('sanya')||n.includes('oyin olugbile'))return[{title:SANYA.title,authors:[SANYA.author],source:'EDUWILLS verified catalogue'}];
 const k=`eduwills:${CACHE}:search:${kind}:${n}`,old=getCache<BookSearchResult[]>(k);if(old)return old;
 const e=encodeURIComponent(q);const urls=kind==='title'?[`https://openlibrary.org/search.json?title=${e}&limit=80&fields=title,author_name`,`https://www.googleapis.com/books/v1/volumes?q=intitle:${e}&maxResults=40`,`https://archive.org/advancedsearch.php?q=title:%28${e}%29&fl[]=title&fl[]=creator&rows=50&output=json`,`https://www.loc.gov/books/?q=${e}&fo=json&c=40`]:[`https://openlibrary.org/search.json?author=${e}&limit=80&fields=title,author_name`,`https://www.googleapis.com/books/v1/volumes?q=inauthor:${e}&maxResults=40`,`https://www.loc.gov/books/?q=${e}&fo=json&c=40`,`https://archive.org/advancedsearch.php?q=creator:%28${e}%29&fl[]=title&fl[]=creator&rows=50&output=json`];
 const out:BookSearchResult[]=[];const seen=new Set<string>();
 for(const u of urls){try{const r=await fetch(u,{cache:'no-store'});if(!r.ok)continue;const d=await r.json();for(const x of d.docs||[]){const t=String(x.title||'').trim(),a=(x.author_name||[]).map(String);if(!t||!a.length)continue;const id=norm(t)+'|'+a.map(norm).join('|');if(!seen.has(id)){seen.add(id);out.push({title:t,authors:a,source:u.includes('openlibrary')?'Open Library':u.includes('googleapis')?'Google Books':u.includes('archive')?'Internet Archive':'Library of Congress'})}}for(const x of d.items||[]){const t=String(x.volumeInfo?.title||'').trim(),a=(x.volumeInfo?.authors||[]).map(String);if(t&&a.length){const id=norm(t)+'|'+a.map(norm).join('|');if(!seen.has(id)){seen.add(id);out.push({title:t,authors:a,source:'Google Books'})}}}}catch{}}
 const result=out.slice(0,160);setCache(k,result,21600000);return result;
}

export async function researchBooks(books:QuizBook[]):Promise<string>{
 const fixed=books.map(b=>scars(b.title)?SCARS:sanya(b)?SANYA:b),k=`eduwills:${CACHE}:research:${fixed.map(b=>norm(b.title+'|'+b.author)).join(';')}`,old=getCache<string>(k);if(old)return old;const all:string[]=[];
 for(const b of fixed){const guard=sanya(b)?'This is the Nigerian novel Sànyà by Oyin Olugbile. Ignore Sanya Mountain, Sanya Bay, Sanya Island and every geography/travel result.':scars(b.title)?'This is SCARS: Nigeria’s Journey and the Boko Haram Conundrum by Gen. Lucky Irabor. Ignore unrelated books or places named Scars.':'';const p=`Research the exact book "${b.title}" by ${b.author}. ${guard} Build a factual study dossier for quiz generation. Prioritize actual book CONTENT: named people or characters, exact dates and years, chronology, specific events/incidents, places, organizations, decisions, actions, causes, consequences, conflicts, chapter-specific facts, numbers and documented details. Broad themes and title/author/publication metadata are secondary. Never invent facts. Use Google Search grounding to identify reliable book-specific sources and distinguish similarly named works.`;try{const r=await aiCall(grounded,p);const t=clean(r.response.text());if(t)all.push(`${b.title}: ${t}`)}catch{try{const r=await aiCall(fallback,p);const t=clean(r.response.text());if(t)all.push(`${b.title}: ${t}`)}catch{}}}
 const result=all.join('\n\n').slice(0,120000);setCache(k,result,86400000);return result;
}
function focus(s:string){const n=norm(s),f:string[]=[];if(/date|year|when|chronolog/.test(n))f.push('dates, years and chronology');if(/event|incident|battle|occur|happen|crisis/.test(n))f.push('specific events and incidents');if(/name|people|person|character/.test(n))f.push('named people, characters and organizations');if(/place|location/.test(n))f.push('places and locations');if(/cause|effect|consequence|result/.test(n))f.push('causes, consequences and effects');if(/chapter|part|section/.test(n))f.push('chapter or section details');return f}
function bad(q:string){return /\b(main|major)\s+(challenge|theme|problem|topic)|what\s+(is|was)\s+the\s+(main|major)\s+theme|what is the book about/i.test(q)}
function meta(q:string){return /\b(author|title|publisher|publication|isbn|edition|written by)\b/i.test(q)}
function valid(q:any){return q&&typeof q.question==='string'&&q.question.length>18&&!bad(q.question)&&Array.isArray(q.options)&&q.options.length===4&&q.options.every((x:any)=>typeof x==='string'&&x.trim())&&Number.isInteger(q.answer)&&q.answer>=0&&q.answer<4}

export async function generateQuiz(books:QuizBook[],count:number,difficulty:string,instructions:string,recent:string[]=[],research=''):Promise<QuizQuestion[]>{
 const fixed=books.map(b=>scars(b.title)?SCARS:sanya(b)?SANYA:b),f=focus(instructions),need=Math.ceil(count*.8);let avoid=[...recent].slice(-80);
 for(let attempt=1;attempt<=5;attempt++){
  const p=`Generate EXACTLY ${count} multiple-choice questions for these exact books: ${fixed.map(b=>`"${b.title}" by ${b.author}`).join('; ')}. Difficulty ${difficulty}. USER INSTRUCTION: "${instructions||'Create a diverse quiz based on the actual book content.'}". ${f.length?`The requested focus is ${f.join(', ')}. At least ${Math.max(need,Math.ceil(count*.7))} questions must directly test those focus areas.`:''} HARD RULES: At least 80% must test concrete book content. Ask about specific dates/years, events/incidents, names, places, chronology, actions, decisions, causes/effects, chapter-specific details and documented facts. Do NOT fill the quiz with title, author, publisher, number of chapters, number of parts or broad-theme questions. Metadata questions are allowed for at most 15% of the set. Do not repeat one fact in different wording. For Sànyà use only Oyin Olugbile's Nigerian novel and never Sanya Mountain/Bay/Island/geography. For SCARS use only Gen. Lucky Irabor's book. Every answer must be supported by the research dossier. Return JSON only with questions, four options, answer index and evidence. Research dossier:\n${research.slice(0,110000)}\nAvoid these prior questions:\n${avoid.join('\n')}`;
  try{const r=await aiCall(attempt===1?grounded:fallback,p);const d=json(r.response.text()),arr=(Array.isArray(d.questions)?d.questions:[]).map((q:any)=>({question:clean(q.question),options:q.options.map((x:any)=>clean(x)),answer:Number(q.answer),evidence:clean(q.evidence||'')})).filter(valid);const seen=new Set<string>();const unique=arr.filter((q:any)=>{const k=norm(q.question);if(seen.has(k))return false;seen.add(k);return true});const substantive=unique.filter((q:any)=>!meta(q.question)).length;const focusHit=f.length?unique.filter((q:any)=>{const x=norm(q.question);return (f.some(z=>z.includes('dates')&&(/\b(19|20)\d{2}\b|\bwhen\b|\bdate\b/.test(x))))||(f.some(z=>z.includes('events')&&/event|incident|battle|crisis|occur|happen/.test(x)))||(f.some(z=>z.includes('names')&&/who|name|person|organization|character/.test(x)))||(f.some(z=>z.includes('places')&&/where|place|location/.test(x)))||(f.some(z=>z.includes('causes')&&/why|cause|result|consequence/.test(x)))||(f.some(z=>z.includes('chapter')&&/chapter|part|section/.test(x)))}).length:substantive;
   if(unique.length>=count&&substantive>=need&&(!f.length||focusHit>=Math.ceil(count*.7)))return unique.slice(0,count);avoid=unique.map(q=>q.question);await wait(500)}catch{await wait(500)}}
 throw new Error('Gemini could not produce a complete, diverse book-content quiz after automatic retries.');
}
export async function explainFailure(book:string,question:string,chosen:string,correct:string){try{const r=await aiCall(plain,`In plain text only, with no Markdown, code fences, backticks, asterisks or headings, briefly explain why "${correct}" is correct for this question from ${book}: ${question}. The learner chose: ${chosen}.`,20000);return clean(r.response.text())}catch{return `The correct answer is ${correct}. Review the relevant passage or event in ${book}.`}}
export async function generateRemarks(books:QuizBook[],score:number,total:number,percentage:number,difficulty:string,elapsed:number){try{const r=await aiCall(plain,`Write one short plain-text performance remark for a learner who scored ${score}/${total} (${percentage}%) on a ${difficulty} quiz about ${books.map(b=>b.title).join(', ')}. Mention one strength and one useful next step. No Markdown or code symbols.`,20000);return clean(r.response.text())}catch{return percentage>=80?'Excellent work. Your result shows strong understanding of the selected book content.':percentage>=60?'Good progress. Review the questions you missed and revisit those sections.':'Keep practising. Re-read the relevant events and details, then try another quiz.'}}
