'use client';

import { useEffect, useState } from 'react';
import { Mail, RefreshCw, ShieldCheck } from 'lucide-react';
import { onAuthStateChanged } from 'firebase/auth';
import { collection, getDocs } from 'firebase/firestore';
import { auth, db } from '@/lib/firebase';

const BASE='/eduwills';
type User={id:string;uid?:string;fullName?:string;username?:string;email?:string};
type Token={id:string;code?:string;token?:string;userId?:string;email?:string;username?:string;categories?:string[];paymentAmount?:number;paymentCurrency?:string;paymentReference?:string;paymentStatus?:string;codeExpiresAt?:any;expiresAt?:any;used?:boolean;redeemed?:boolean;lastEmailedAt?:any};
function date(v:any){const d=v?.toDate?.()||new Date(v);return d instanceof Date&&!Number.isNaN(d.getTime())?d.toLocaleString('en-NG'): '—'}

export default function ActivationAdmin(){
 const [users,setUsers]=useState<User[]>([]);const [tokens,setTokens]=useState<Token[]>([]);const [loading,setLoading]=useState(true);const [message,setMessage]=useState('');const [sending,setSending]=useState('');
 async function load(){setLoading(true);try{const [u,t]=await Promise.all([getDocs(collection(db,'users')),getDocs(collection(db,'williTokens'))]);setUsers(u.docs.map(x=>({id:x.id,...x.data()} as User)));setTokens(t.docs.map(x=>({id:x.id,...x.data()} as Token)).filter(x=>x.paymentStatus==='success'||x.paymentReference));}finally{setLoading(false)}}
 useEffect(()=>onAuthStateChanged(auth,async user=>{if(!user){window.location.replace(`${BASE}/admin/login/`);return}const admin=await getDocs(collection(db,'admins'));if(!admin.docs.some(x=>x.id===user.uid)){window.location.replace(`${BASE}/admin/login/`);return}load()}),[]);
 async function resend(token:Token){setSending(token.id);setMessage('');try{const id=token.userId||'';const jwt=await auth.currentUser?.getIdToken();const r=await fetch('https://us-central1-eduwills.cloudfunctions.net/adminSendActivationCode',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${jwt}`},body:JSON.stringify({uid:id,code:token.code||token.token})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not send email.');setMessage(`Activation email sent to ${d.sentTo}.`);await load()}catch(e:any){setMessage(e?.message||'Could not send activation email.')}finally{setSending('')}}
 return <main className="min-h-screen bg-slate-950 px-4 py-7 text-white sm:px-8"><div className="mx-auto max-w-6xl"><a href={`${BASE}/admin/`} className="text-sm font-bold text-slate-300">← Admin dashboard</a><header className="mt-6 flex flex-wrap items-center justify-between gap-3"><div className="flex gap-3"><ShieldCheck className="text-cyan-300"/><div><h1 className="text-3xl font-black">Activation & Payment Management</h1><p className="text-sm text-slate-400">Payment records, activation codes, expiry and email delivery.</p></div></div><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm font-black"><RefreshCw size={16}/> Refresh</button></header>{message&&<p className="mt-5 rounded-xl border border-cyan-300/20 bg-cyan-400/10 p-4 text-sm text-cyan-100">{message}</p>}
 <section className="mt-6 overflow-hidden rounded-3xl border border-white/10 bg-white/5"><div className="overflow-x-auto">{loading?<p className="p-8 text-center text-slate-400">Loading…</p>:<table className="min-w-[1050px] w-full text-left text-sm"><thead className="bg-slate-900/80 text-xs uppercase tracking-wider text-slate-400"><tr><th className="p-4">User</th><th className="p-4">Email</th><th className="p-4">Category</th><th className="p-4">Payment</th><th className="p-4">Activation code</th><th className="p-4">Code expiry</th><th className="p-4">1-year expiry</th><th className="p-4">Action</th></tr></thead><tbody>{tokens.map(t=>{const u=users.find(x=>(x.uid||x.id)===t.userId);const code=t.code||t.token||t.id;return <tr key={t.id} className="border-t border-white/10"><td className="p-4 font-bold">{u?.fullName||t.username||'User'}</td><td className="p-4 text-slate-300">{u?.email||t.email||'—'}</td><td className="p-4 text-slate-300">{t.categories?.join(', ')||'—'}</td><td className="p-4 text-slate-300">{t.paymentCurrency||'—'} {t.paymentAmount??'—'}<div className="text-[10px] text-slate-500">{t.paymentReference||''}</div></td><td className="p-4"><code className="rounded bg-slate-900 px-2 py-1 font-black text-cyan-200">{code}</code><div className="mt-1 text-[10px] text-slate-500">{t.used||t.redeemed?'Redeemed':'Not redeemed'}</div></td><td className="p-4 text-slate-300">{date(t.codeExpiresAt)}</td><td className="p-4 text-slate-300">{date(t.expiresAt)}</td><td className="p-4"><button disabled={sending===t.id} onClick={()=>resend(t)} className="inline-flex items-center gap-2 rounded-lg bg-cyan-400 px-3 py-2 text-xs font-black text-slate-950 disabled:opacity-50"><Mail size={14}/>{sending===t.id?'Sending…':'Send to email'}</button></td></tr>})}</tbody></table>}</div>{!loading&&!tokens.length&&<p className="p-8 text-center text-slate-500">No successful activation payments yet.</p>}</section>
 </div></main>
}
