'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, Check, CheckCircle2, FileText, GraduationCap, Search, Sparkles } from 'lucide-react';
import { onAuthStateChanged } from 'firebase/auth';
import { doc, getDoc } from 'firebase/firestore';
import { auth, db } from '@/lib/firebase';

const BASE='/eduwills';
const EXAM_SUBJECTS: Record<string,string[]> = {
  JAMB: ['Use of English','Mathematics','Biology','Chemistry','Physics','Economics','Government','Literature in English','Geography','Commerce','Accounting','Agricultural Science','Computer Science','Christian Religious Studies','Islamic Studies','History','French','Music','Fine Art','Home Economics','Arabic','Yoruba','Igbo','Hausa'],
  WAEC: ['English Language','Mathematics','Agricultural Science','Animal Husbandry','Arabic','Biology','Chemistry','Christian Religious Studies','Civic Education','Commerce','Computer Studies','Economics','Financial Accounting','Food and Nutrition','French','Further Mathematics','Geography','Government','Hausa','Health Education','History','Home Management','Igbo','Insurance','Islamic Studies','Literature in English','Marketing','Music','Physical Education','Physics','Technical Drawing','Visual Art','Yoruba'],
  NECO: ['English Language','Mathematics','Agricultural Science','Animal Husbandry','Arabic','Biology','Chemistry','Christian Religious Studies','Civic Education','Commerce','Computer Studies','Economics','Financial Accounting','French','Further Mathematics','Geography','Government','Hausa','Health Education','History','Home Economics','Igbo','Islamic Studies','Literature in English','Marketing','Physics','Technical Drawing','Visual Art','Yoruba'],
  BECE: ['English Studies','Mathematics','Basic Science','Basic Technology','Business Studies','Civic Education','Computer Studies','Cultural and Creative Arts','French','Hausa','Igbo','Islamic Religious Studies','Christian Religious Studies','Physical and Health Education','Social Studies','Yoruba','Agricultural Science','Home Economics'],
};
const EXAMS: Record<'primary'|'junior'|'senior',string[]>={primary:['Normal Test'],junior:['BECE','NECO'],senior:['JAMB','WAEC','NECO']};
function levelId(v:string|null):'primary'|'junior'|'senior'{const x=String(v||'').toLowerCase();if(x==='primary')return'primary';if(x==='junior'||x==='jss'||x==='junior-secondary')return'junior';return'senior'}
function slug(v:string){return v.toLowerCase().replace(/\s+/g,'-')}
export default function ExamPage(){
 const [level,setLevel]=useState<'primary'|'junior'|'senior'>('senior');const [exam,setExam]=useState('WAEC');const [selected,setSelected]=useState<string[]>([]);const [query,setQuery]=useState('');const [loading,setLoading]=useState(true);const [message,setMessage]=useState('');
 useEffect(()=>{const requested=levelId(new URLSearchParams(window.location.search).get('level'));setLevel(requested);setExam(EXAMS[requested][0]||'WAEC');const off=onAuthStateChanged(auth,async u=>{if(!u){window.location.replace(`${BASE}/login/`);return}try{const s=await getDoc(doc(db,'users',u.uid));const d=s.data()||{};const values=[...(Array.isArray(d.categories)?d.categories:[]),...(Array.isArray(d.educationLevels)?d.educationLevels:[]),...(Array.isArray(d.schoolLevels)?d.schoolLevels:[]),d.category,d.educationLevel,d.schoolLevel].map(x=>String(x||'').toLowerCase());setLevel(requested);if(!values.some(v=>v===requested||v.includes(requested)))setMessage('This exam pathway is not assigned to your account.');}catch{setMessage('Could not load your learning access. Please refresh.')}finally{setLoading(false)}});return()=>off()},[]);
 useEffect(()=>{const first=EXAM_SUBJECTS[exam]?.[0];setSelected(first?[first]:[])},[exam]);
 const subjects=EXAM_SUBJECTS[exam]||[];const filtered=useMemo(()=>subjects.filter(s=>s.toLowerCase().includes(query.trim().toLowerCase())),[subjects,query]);
 function toggle(s:string){setSelected(v=>v.includes(s)?v.filter(x=>x!==s):[...v,s])}
 function begin(){if(!selected.length){setMessage('Select at least one subject.');return}const p=new URLSearchParams({category:level,mode:slug(exam),subjects:selected.join('|')});window.location.assign(`${BASE}/dashboard/category-quiz/?${p.toString()}`)}
 if(loading)return <main className="min-h-screen bg-paper p-8 text-center font-bold text-slate-500">Loading exam centre…</main>;
 return <main className="min-h-screen bg-paper pb-10 text-ink"><header className="sticky top-0 z-40 border-b border-slate-200/80 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 sm:px-8"><a href={`${BASE}/dashboard/`} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2 text-sm font-black"><ArrowLeft size={17}/> Dashboard</a><div className="flex items-center gap-2 font-black"><span className="grid h-9 w-9 place-items-center rounded-xl bg-ink text-white"><BookOpen size={17}/></span> EDUWILLS</div></div></header>
 <div className="mx-auto max-w-6xl px-5 py-7 sm:px-8 sm:py-10"><section className="relative overflow-hidden rounded-[2rem] bg-ink p-7 text-white shadow-2xl sm:p-10"><div className="pointer-events-none absolute -right-16 -top-20 h-72 w-72 rounded-full bg-cyan-400/10 blur-3xl"/><p className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-[10px] font-black uppercase tracking-[.2em] text-cyan-200"><GraduationCap size={13}/> EXAM CENTRE</p><h1 className="mt-4 text-3xl font-black sm:text-5xl">Choose your examination.</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-300">Select the examination you are preparing for, then choose one or more verified subjects. You are not locked into WAEC.</p></section>
 <section className="mt-6 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-700">1. Examination</p><h2 className="mt-1 text-xl font-black">Select the paper</h2></div><FileText className="text-cyan-600" size={23}/></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{EXAMS[level].map(x=><button type="button" key={x} onClick={()=>setExam(x)} className={`rounded-2xl border p-4 text-left transition ${exam===x?'border-cyan-500 bg-cyan-50 shadow-sm':'border-slate-200 hover:border-cyan-300'}`}><div className="flex items-center justify-between gap-2"><span className="font-black">{x}</span>{exam===x&&<CheckCircle2 className="text-cyan-600" size={19}/>}</div><p className="mt-1 text-xs text-slate-500">{x==='JAMB'?'UTME preparation':x==='WAEC'?'Senior School Certificate':x==='NECO'?'National Senior School Certificate':'Junior secondary examination'}</p></button>)}</div></section>
 <section className="mt-6 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-700">2. Subjects</p><h2 className="mt-1 text-xl font-black">Choose one or more</h2><p className="mt-1 text-sm text-slate-500">{selected.length} selected · {subjects.length} available for {exam}</p></div><div className="relative w-full sm:w-72"><Search className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search subjects…" className="w-full rounded-xl border border-slate-200 bg-paper py-3 pl-10 pr-4 text-sm font-bold outline-none focus:border-cyan-400"/></div></div><div className="mt-5 grid max-h-[28rem] gap-2 overflow-y-auto pr-1 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(s=><button type="button" key={s} onClick={()=>toggle(s)} className={`flex items-center justify-between gap-3 rounded-xl border p-3.5 text-left text-sm font-black transition ${selected.includes(s)?'border-cyan-400 bg-cyan-50 text-cyan-950':'border-slate-200 hover:border-cyan-300'}`}><span>{s}</span><span className={`grid h-6 w-6 shrink-0 place-items-center rounded-md border ${selected.includes(s)?'border-cyan-600 bg-cyan-600 text-white':'border-slate-300 bg-white'}`}>{selected.includes(s)&&<Check size={14}/>}</span></button>)}</div><div className="mt-5 flex flex-wrap gap-2">{selected.map(s=><span key={s} className="inline-flex items-center gap-2 rounded-full bg-slate-100 px-3 py-1.5 text-xs font-black">{s}</span>)}</div>{message&&<p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm font-bold text-amber-800">{message}</p>}<button type="button" onClick={begin} className="mt-6 flex w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-indigo-600 to-cyan-500 px-5 py-4 text-sm font-black text-white shadow-lg">Continue with {selected.length} subject{selected.length===1?'':'s'} <Sparkles size={17}/><ArrowRight size={17}/></button></section>
 </div></main>;
}
