import app from './index.js';

const b64 = a => btoa(String.fromCharCode(...new Uint8Array(a))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const cors = origin => ({'access-control-allow-origin':origin||'*','access-control-allow-headers':'authorization,content-type','access-control-allow-methods':'GET,POST,OPTIONS','access-control-max-age':'86400','vary':'Origin'});
const json = (body,status=200,origin='*') => new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8',...cors(origin)}});
function pemToDer(pem){const s=pem.replace(/-----BEGIN PRIVATE KEY-----|-----END PRIVATE KEY-----|\s/g,'');const bin=atob(s);const out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out.buffer;}
async function googleAccessToken(env){const sa=JSON.parse(env.FIREBASE_SERVICE_ACCOUNT_JSON);const header=b64(new TextEncoder().encode(JSON.stringify({alg:'RS256',typ:'JWT'})));const now=Math.floor(Date.now()/1000);const claim=b64(new TextEncoder().encode(JSON.stringify({iss:sa.client_email,scope:'https://www.googleapis.com/auth/datastore https://www.googleapis.com/auth/cloud-platform',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600})));const key=await crypto.subtle.importKey('pkcs8',pemToDer(sa.private_key.replace(/\\n/g,'\n')),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(`${header}.${claim}`));const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:`grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion=${encodeURIComponent(`${header}.${claim}.${b64(sig)}`)}`});if(!r.ok)throw new Error('GOOGLE_AUTH_FAILED');return(await r.json()).access_token;}
async function fsGet(env,path){const token=await googleAccessToken(env);const r=await fetch(`https://firestore.googleapis.com/v1/projects/${env.FIREBASE_PROJECT_ID}/databases/(default)/documents/${path}`,{headers:{Authorization:`Bearer ${token}`}});if(r.status===404)return null;if(!r.ok)throw new Error('FIRESTORE_READ_FAILED');return r.json();}
async function authLookup(env,idToken){if(!idToken)throw new Error('AUTH_REQUIRED');const r=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=${env.FIREBASE_WEB_API_KEY}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({idToken})});if(!r.ok)throw new Error('AUTH_REQUIRED');return(await r.json()).users?.[0];}
async function hmac(secret,raw){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-512'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(raw));return [...new Uint8Array(sig)].map(b=>b.toString(16).padStart(2,'0')).join('');}
async function paystackGet(env,ref){if(!env.PAYSTACK_SECRET_KEY)throw new Error('PAYSTACK_NOT_CONFIGURED');const r=await fetch(`https://api.paystack.co/transaction/verify/${encodeURIComponent(ref)}`,{headers:{Authorization:`Bearer ${env.PAYSTACK_SECRET_KEY}`}});const d=await r.json().catch(()=>({}));if(!r.ok||!d.status)throw new Error(d.message||`PAYSTACK_HTTP_${r.status}`);return d.data;}
export default {async fetch(req,env,ctx){const origin=req.headers.get('origin')||'*';if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(origin)});const url=new URL(req.url);if(req.method==='GET'&&url.pathname==='/paystack/verify'){try{const u=await authLookup(env,(req.headers.get('authorization')||'').replace(/^Bearer /,''));if(!u?.localId)return json({error:'Authentication required.'},401,origin);const reference=String(url.searchParams.get('reference')||'').trim();if(!reference)return json({error:'Payment reference is required.'},400,origin);const tx=await paystackGet(env,reference);if(String(tx?.customer?.email||'').toLowerCase()!==String(u.email||'').toLowerCase())return json({error:'This payment does not belong to your account.'},403,origin);if(tx.status!=='success')return json({error:'Payment has not been confirmed yet. Please wait a moment and refresh.'},409,origin);const raw=JSON.stringify({event:'charge.success',data:tx});const signature=await hmac(env.PAYSTACK_SECRET_KEY,raw);const internal=new Request(new URL('/paystack/webhook',req.url).toString(),{method:'POST',headers:{'content-type':'application/json','x-paystack-signature':signature},body:raw});const webhookResponse=await app.fetch(internal,env,ctx);if(!webhookResponse.ok){const detail=await webhookResponse.text();return json({error:detail||'Payment was verified but activation could not be completed.'},502,origin);}const userDoc=await fsGet(env,`users/${u.localId}`);const fields=userDoc?.fields||{};return json({ok:true,reference,emailSent:fields.activationCodeEmailSent?.booleanValue===true,codeReady:Boolean(fields.pendingActivationCode?.stringValue),categories:JSON.parse(fields.pendingActivationCategories?.stringValue||'[]'),activationExpiresAt:fields.activationExpiresAt?.stringValue||''},200,origin);}catch(e){return json({error:e?.message||'PAYMENT_VERIFICATION_FAILED'},500,origin);}}return app.fetch(req,env,ctx);}};
