const ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const PRICES = { Primary: 2000, 'Junior Secondary': 3000, 'Senior Secondary': 3000, 'Book Learner': 4000 };
const COUNTRY_CURRENCY = { NG: 'NGN', US: 'USD', GB: 'GBP', GH: 'GHS', KE: 'KES', ZA: 'ZAR', CI: 'XOF' };
const PAYSTACK_CURRENCIES = new Set(['NGN', 'USD', 'GHS', 'KES', 'ZAR', 'XOF']);
const FALLBACK_USD_PER_NGN = 1 / 1550;
const FALLBACK_USD_RATES = { USD: 1, GBP: 0.75, EUR: 0.86, GHS: 11.2, KES: 129, ZAR: 17.8, XOF: 560, NGN: 1550 };
const cors = origin => ({ 'access-control-allow-origin': origin || '*', 'access-control-allow-headers': 'authorization,content-type', 'access-control-allow-methods': 'GET,POST,OPTIONS', 'access-control-max-age': '86400', vary: 'Origin' });
const json = (body, status = 200, origin = '*') => new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json; charset=utf-8', ...cors(origin) } });
const cleanCategories = c => [...new Set((Array.isArray(c) ? c : []).map(String).filter(x => Object.hasOwn(PRICES, x)))];
const baseTotal = c => cleanCategories(c).reduce((s, x) => s + PRICES[x], 0);
const makeCode = () => Array.from({ length: 10 }, () => ALPHABET[Math.floor(Math.random() * ALPHABET.length)]).join('');
const b64 = a => btoa(String.fromCharCode(...new Uint8Array(a))).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/,'');
async function googleAccessToken(env) { const sa = JSON.parse(env.FIREBASE_SERVICE_ACCOUNT_JSON); const header = b64(new TextEncoder().encode(JSON.stringify({ alg: 'RS256', typ: 'JWT' }))); const now = Math.floor(Date.now()/1000); const claim = b64(new TextEncoder().encode(JSON.stringify({ iss: sa.client_email, scope: 'https://www.googleapis.com/auth/datastore https://www.googleapis.com/auth/cloud-platform', aud: 'https://oauth2.googleapis.com/token', iat: now, exp: now + 3600 }))); const keyData = sa.private_key.replace(/\\n/g,'\n'); const key = await crypto.subtle.importKey('pkcs8', pemToDer(keyData), { name: 'RSASSA-PKCS1-v1_5', hash: 'SHA-256' }, false, ['sign']); const sig = await crypto.subtle.sign('RSASSA-PKCS1-v1_5', key, new TextEncoder().encode(`${header}.${claim}`)); const jwt = `${header}.${claim}.${b64(sig)}`; const r = await fetch('https://oauth2.googleapis.com/token', { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body: `grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion=${encodeURIComponent(jwt)}` }); if (!r.ok) throw new Error('GOOGLE_AUTH_FAILED'); return (await r.json()).access_token; }
function pemToDer(pem) { const s = pem.replace(/-----BEGIN PRIVATE KEY-----|-----END PRIVATE KEY-----|\s/g,''); const bin = atob(s); const out = new Uint8Array(bin.length); for (let i=0;i<bin.length;i++) out[i]=bin.charCodeAt(i); return out.buffer; }
async function fsGet(env, path) { const token = await googleAccessToken(env); const r = await fetch(`https://firestore.googleapis.com/v1/projects/${env.FIREBASE_PROJECT_ID}/databases/(default)/documents/${path}`, { headers: { Authorization: `Bearer ${token}` } }); if (r.status === 404) return null; if (!r.ok) throw new Error('FIRESTORE_READ_FAILED'); return r.json(); }
const fsVal = v => typeof v === 'string' ? { stringValue: v } : typeof v === 'number' ? { doubleValue: v } : { booleanValue: v };
async function fsWrite(env, path, fields) { const token = await googleAccessToken(env); const r = await fetch(`https://firestore.googleapis.com/v1/projects/${env.FIREBASE_PROJECT_ID}/databases/(default)/documents/${path}`, { method: 'PATCH', headers: { Authorization: `Bearer ${token}`, 'content-type': 'application/json' }, body: JSON.stringify({ fields: Object.fromEntries(Object.entries(fields).map(([k,v]) => [k, fsVal(v)])) }) }); if (!r.ok) throw new Error('FIRESTORE_WRITE_FAILED'); return r.json(); }
async function authLookup(env, idToken) { if (!idToken) throw new Error('AUTH_REQUIRED'); const r = await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=${env.FIREBASE_WEB_API_KEY}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ idToken }) }); if (!r.ok) throw new Error('AUTH_REQUIRED'); const d = await r.json(); return d.users?.[0]; }
async function fxRate(from,to) { if (from===to) return 1; try { const r=await fetch(`https://open.er-api.com/v6/latest/${from}`); if(r.ok){const d=await r.json();const rate=Number(d?.rates?.[to]);if(rate>0)return rate;}} catch {} const fromUsd=FALLBACK_USD_RATES[from]||1; const toUsd=FALLBACK_USD_RATES[to]||1; return from==='NGN'&&to==='USD'?FALLBACK_USD_PER_NGN:(to==='NGN'&&from==='USD'?FALLBACK_USD_RATES.NGN:(1/fromUsd)*toUsd); }
async function paystackPost(env,path,body) { if(!env.PAYSTACK_SECRET_KEY) throw new Error('PAYSTACK_NOT_CONFIGURED'); const r=await fetch(`https://api.paystack.co/${path}`,{method:'POST',headers:{Authorization:`Bearer ${env.PAYSTACK_SECRET_KEY}`,'content-type':'application/json'},body:JSON.stringify(body)}); const d=await r.json().catch(()=>({})); if(!r.ok||!d.status) throw new Error(d.message||`PAYSTACK_HTTP_${r.status}`); return d.data; }
async function paystackGet(env,path) { if(!env.PAYSTACK_SECRET_KEY) throw new Error('PAYSTACK_NOT_CONFIGURED'); const r=await fetch(`https://api.paystack.co/${path}`,{headers:{Authorization:`Bearer ${env.PAYSTACK_SECRET_KEY}`}}); const d=await r.json().catch(()=>({})); if(!r.ok||!d.status) throw new Error(d.message||`PAYSTACK_HTTP_${r.status}`); return d.data; }
async function sendEmail(env,to,name,code,categories,amount,currency,codeExpires) { if(!env.RESEND_API_KEY) return { sent:false, reason:'RESEND_NOT_CONFIGURED' }; const safe=String(name||'EduWills learner').replace(/[<>]/g,''); const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({from:env.RESEND_FROM_EMAIL||'EduWills <onboarding@resend.dev>',to:[to],subject:'Your EduWills activation code',html:`<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto;padding:32px"><h2>EduWills</h2><p>Hello ${safe},</p><p>Your payment has been confirmed. Your activation code is:</p><div style="font-size:28px;font-weight:800;letter-spacing:5px;text-align:center;padding:20px;background:#f1f5f9">${code}</div><p><b>Category:</b> ${categories.join(', ')}</p><p><b>Payment:</b> ${currency} ${amount}</p><p><b>Redeem by:</b> ${new Date(codeExpires).toLocaleString('en-NG')}</p><p>After redemption, your activation lasts <b>1 year</b>.</p><p>For your security, this code can only be redeemed once.</p><p>Thank you for choosing EduWills.</p></div>`})}); if(!r.ok){const detail=await r.text().catch(()=> ''); return {sent:false,reason:`RESEND_${r.status}`,detail:detail.slice(0,300)};} return {sent:true}; }
async function processPayment(env,tx){ if(tx?.metadata?.product!=='eduwills_activation'||tx.status!=='success') return {processed:false,reason:'IGNORED'}; const uid=String(tx.metadata.uid||''); const categories=cleanCategories(tx.metadata.categories); if(!uid||!categories.length) throw new Error('INVALID_PAYMENT_METADATA'); const paymentReference=String(tx.reference||''); const user=await fsGet(env,`users/${uid}`); if(!user) throw new Error('USER_NOT_FOUND'); const userFields=user.fields||{}; const existingPending=userFields.pendingActivationCode?.stringValue||''; if(existingPending){ const existingToken=await fsGet(env,`williTokens/${existingPending}`); if(existingToken?.fields?.paymentReference?.stringValue===paymentReference){ return {processed:true,code:existingPending,emailSent:existingToken.fields.activationCodeEmailSent?.booleanValue===true,activationExpiresAt:existingToken.fields.expiresAt?.stringValue||'',categories}; } }
 const code=makeCode(); const now=Date.now(); const codeExpires=now+7*86400000; const activationExpires=now+365*86400000; const amount=Number(tx.amount||0)/100; const currency=String(tx.currency||'NGN').toUpperCase(); const path=`williTokens/${code}`; await fsWrite(env,path,{token:code,code,userId:uid,uid,email:userFields.email?.stringValue||'',categories:JSON.stringify(categories),duration:'1 year',durationMs:31536000000,createdAt:new Date(now).toISOString(),expiresAt:new Date(activationExpires).toISOString(),codeExpiresAt:new Date(codeExpires).toISOString(),used:false,redeemed:false,active:false,source:'paystack',paymentReference,paymentCurrency:currency,paymentAmount:amount,paymentId:Number(tx.id||0),paymentStatus:'success'});
 const email=String(userFields.email?.stringValue||'').trim().toLowerCase(); const name=userFields.fullName?.stringValue||userFields.displayName?.stringValue||''; const emailResult=await sendEmail(env,email,name,code,categories,amount,currency,codeExpires); await fsWrite(env,path,{activationCodeEmailSent:emailResult.sent===true,activationCodeEmailError:emailResult.sent?'':String(emailResult.reason||'')}); await fsWrite(env,`users/${uid}`,{pendingActivationCode:code,pendingActivationCodeExpiresAt:new Date(codeExpires).toISOString(),pendingActivationCategories:JSON.stringify(categories),pendingActivationPaymentReference:paymentReference,pendingActivationPaymentStatus:'success',activationPaymentAmount:amount,activationPaymentCurrency:currency,activationCodeEmailSent:emailResult.sent===true}); return {processed:true,code,emailSent:emailResult.sent===true,activationExpiresAt:new Date(activationExpires).toISOString(),categories}; }
async function redeemCode(env,idToken,code){ const u=await authLookup(env,idToken); if(!u?.localId)throw new Error('AUTH_REQUIRED'); const path=`williTokens/${code}`; const token=await fsGet(env,path); if(!token)throw new Error('INVALID_ACTIVATION_CODE'); const f=token.fields||{}; const userId=f.userId?.stringValue||''; if(userId!==u.localId)throw new Error('CODE_NOT_FOR_USER'); if(f.used?.booleanValue===true||f.redeemed?.booleanValue===true)throw new Error('ACTIVATION_CODE_ALREADY_USED'); const codeExpiry=Date.parse(f.codeExpiresAt?.stringValue||''); if(!codeExpiry||codeExpiry<=Date.now())throw new Error('ACTIVATION_CODE_EXPIRED'); const activationExpiry=f.expiresAt?.stringValue||new Date(Date.now()+365*86400000).toISOString(); const categories=JSON.parse(f.categories?.stringValue||'[]'); await fsWrite(env,path,{used:true,redeemed:true,active:true,redeemedAt:new Date().toISOString(),redeemedBy:u.localId}); await fsWrite(env,`users/${u.localId}`,{activated:true,activationStatus:'active',williTokenActive:true,activationExpiresAt:activationExpiry,categories:JSON.stringify(categories),activeCategories:JSON.stringify(categories),pendingActivationCode:'',pendingActivationCodeExpiresAt:''}); return {activationExpiresAt:activationExpiry,categories}; }
async function validHmac(secret,raw,signature){ const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-512'},false,['sign']); const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(raw)); const hex=[...new Uint8Array(sig)].map(b=>b.toString(16).padStart(2,'0')).join(''); return signature.length===hex.length&&signature===hex; }
async function handle(req,env){ const origin=req.headers.get('origin')||'*'; if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(origin)}); const url=new URL(req.url);
 if(req.method==='GET'&&url.pathname==='/health')return json({ok:true,service:'eduwills-payments',paystackConfigured:Boolean(env.PAYSTACK_SECRET_KEY),firebaseConfigured:Boolean(env.FIREBASE_SERVICE_ACCOUNT_JSON&&env.FIREBASE_WEB_API_KEY),resendConfigured:Boolean(env.RESEND_API_KEY),timestamp:new Date().toISOString()},200,origin);
 if(req.method==='GET'&&url.pathname==='/paystack/verify'){ try{const idToken=(req.headers.get('authorization')||'').replace(/^Bearer /,''); const u=await authLookup(env,idToken); if(!u?.emailVerified)return json({error:'Verify your email before confirming payment.'},403,origin); const reference=String(url.searchParams.get('reference')||'').trim(); if(!reference)return json({error:'Missing payment reference.'},400,origin); const tx=await paystackGet(env,`transaction/verify/${encodeURIComponent(reference)}`); if(String(tx?.status||'').toLowerCase()!=='success')return json({error:'Paystack has not confirmed this payment yet.'},409,origin); if(String(tx?.metadata?.product||'')!=='eduwills_activation'||String(tx?.metadata?.uid||'')!==String(u.localId))return json({error:'Payment reference is not linked to this account.'},403,origin); const result=await processPayment(env,tx); const user=await fsGet(env,`users/${u.localId}`); const f=user?.fields||{}; return json({ok:true,reference,categories:result.categories||cleanCategories(tx.metadata.categories),activationExpiresAt:result.activationExpiresAt||'',emailSent:f.activationCodeEmailSent?.booleanValue===true||result.emailSent===true},200,origin); }catch(e){const status=e.message==='AUTH_REQUIRED'?401:(e.message==='PAYSTACK_NOT_CONFIGURED'?503:500);return json({error:e.message||'PAYMENT_VERIFICATION_FAILED'},status,origin);} }
 if(req.method!=='POST')return json({error:'POST required'},405,origin);
 if(url.pathname==='/paystack/webhook'){ const raw=await req.text(); const sig=req.headers.get('x-paystack-signature')||''; if(!(await validHmac(env.PAYSTACK_SECRET_KEY,raw,sig)))return json({error:'Invalid signature'},401,origin); const event=JSON.parse(raw); if(event.event==='charge.success'){try{await processPayment(env,event.data);}catch(e){return json({error:e.message||'Webhook processing failed'},500,origin);}} return new Response('OK',{status:200,headers:cors(origin)}); }
 if(url.pathname==='/paystack/quote'){try{const idToken=(req.headers.get('authorization')||'').replace(/^Bearer /,'');const u=await authLookup(env,idToken);if(!u?.emailVerified)return json({error:'Verify your email before paying for activation.'},403,origin);const body=await req.json();const cats=cleanCategories(body.categories);if(!cats.length)return json({error:'Select at least one category.'},400,origin);const country=String(body.country||'INT').toUpperCase();const requestedCurrency=String(body.currency||COUNTRY_CURRENCY[country]||'USD').toUpperCase();const ngnTotal=baseTotal(cats);if(country==='NG'&&requestedCurrency==='NGN')return json({localCurrency:'NGN',localAmount:ngnTotal,paymentCurrency:'NGN',paymentAmount:ngnTotal,baseAmount:ngnTotal,international:false},200,origin);const usdRate=await fxRate('NGN','USD');const usdAmount=ngnTotal*usdRate+1;const localCurrency=requestedCurrency==='NGN'?'USD':requestedCurrency;const localRate=await fxRate('USD',localCurrency);const localAmount=Math.round(usdAmount*localRate*100)/100;return json({localCurrency,localAmount,paymentCurrency:'USD',paymentAmount:Math.round(usdAmount*100)/100,baseAmount:ngnTotal,international:true},200,origin);}catch(e){return json({error:e.message||'Could not calculate quote.'},500,origin);}}
 if(url.pathname==='/paystack/initialize'){try{const idToken=(req.headers.get('authorization')||'').replace(/^Bearer /,'');const u=await authLookup(env,idToken);if(!u?.emailVerified)return json({error:'Verify your email before paying for activation.'},403,origin);const body=await req.json();const cats=cleanCategories(body.categories);if(!cats.length)return json({error:'Select at least one category.'},400,origin);const amount=Number(body.amount);const currency=String(body.paymentCurrency||body.currency||'NGN').toUpperCase();if(!Number.isFinite(amount)||amount<=0||!PAYSTACK_CURRENCIES.has(currency))return json({error:'Invalid payment amount or currency.'},400,origin);const ref=`EW-${u.localId.slice(0,8)}-${Date.now()}-${crypto.randomUUID().slice(0,8)}`;const data=await paystackPost(env,'transaction/initialize',{email:u.email,amount:Math.round(amount*100),currency,reference:ref,callback_url:env.CALLBACK_URL,metadata:{uid:u.localId,categories:cats,durationMs:31536000000,product:'eduwills_activation',country:body.country||'INT'}});return json({reference:data.reference,authorization_url:data.authorization_url,access_code:data.access_code},200,origin);}catch(e){return json({error:e?.message||'PAYMENT_INITIALIZATION_FAILED'},500,origin);}}
 if(url.pathname==='/redeem'){try{const idToken=(req.headers.get('authorization')||'').replace(/^Bearer /,'');const body=await req.json();const code=String(body.code||'').trim().toUpperCase();if(!/^[A-Z0-9]{10}$/.test(code))return json({error:'Invalid activation code format.'},400,origin);const result=await redeemCode(env,idToken,code);return json(result,200,origin);}catch(e){const map={AUTH_REQUIRED:['Authentication required.',401],INVALID_ACTIVATION_CODE:['That activation code is invalid.',404],CODE_NOT_FOR_USER:['That activation code belongs to another account.',403],ACTIVATION_CODE_ALREADY_USED:['This activation code has already been used.',409],ACTIVATION_CODE_EXPIRED:['This activation code has expired.',410]};const [msg,status]=map[e.message]||[e.message||'Activation failed.',500];return json({error:msg},status,origin);}}
 return json({error:'Not found'},404,origin); }
export default {fetch(req,env){return handle(req,env).catch(e=>json({error:e.message||'Server error'},500,req.headers.get('origin')||'*'));}};