const ALPHABET='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const PRICES={Primary:2000,'Junior Secondary':3000,'Senior Secondary':3000,'Book Learner':4000};
const COUNTRY_CURRENCY={NG:'NGN',US:'USD',GB:'GBP',GH:'GHS',KE:'KES',ZA:'ZAR',CI:'XOF'};
const PAYSTACK_CURRENCIES=new Set(['NGN','USD','GHS','KES','ZAR','XOF']);
const FALLBACK_USD_PER_NGN=1/1550;
const FALLBACK_USD_RATES={USD:1,GBP:.75,EUR:.86,GHS:11.2,KES:129,ZAR:17.8,XOF:560,NGN:1550};
const cors=o=>({'access-control-allow-origin':o||'*','access-control-allow-headers':'authorization,content-type','access-control-allow-methods':'GET,POST,OPTIONS','access-control-max-age':'86400',vary:'Origin'});
const json=(b,s=200,o='*')=>new Response(JSON.stringify(b),{status:s,headers:{'content-type':'application/json; charset=utf-8',...cors(o)}});
const cleanCategories=c=>[...new Set((Array.isArray(c)?c:[]).map(String).filter(x=>Object.hasOwn(PRICES,x)))];
const baseTotal=c=>cleanCategories(c).reduce((s,x)=>s+PRICES[x],0);
const makeCode=()=>Array.from({length:10},()=>ALPHABET[Math.floor(Math.random()*ALPHABET.length)]).join('');
const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
async function googleAccessToken(env){const sa=JSON.parse(env.FIREBASE_SERVICE_ACCOUNT_JSON);const h=b64(new TextEncoder().encode(JSON.stringify({alg:'RS256',typ:'JWT'})));const now=Math.floor(Date.now()/1000);const c=b64(new TextEncoder().encode(JSON.stringify({iss:sa.client_email,scope:'https://www.googleapis.com/auth/datastore https://www.googleapis.com/auth/cloud-platform',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600})));const key=await crypto.subtle.importKey('pkcs8',pemToDer(sa.private_key.replace(/\\n/g,'\n')),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(`${h}.${c}`));const jwt=`${h}.${c}.${b64(sig)}`;const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:`grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion=${encodeURIComponent(jwt)}`});if(!r.ok)throw new Error('GOOGLE_AUTH_FAILED');return(await r.json()).access_token;}
function pemToDer(p){const s=p.replace(/-----BEGIN PRIVATE KEY-----|-----END PRIVATE KEY-----|\s/g,'');const b=atob(s);const o=new Uint8Array(b.length);for(let i=0;i<b.length;i++)o[i]=b.charCodeAt(i);return o.buffer;}
async function fsGet(env,path){const t=await googleAccessToken(env);const r=await fetch(`https://firestore.googleapis.com/v1/projects/${env.FIREBASE_PROJECT_ID}/databases/(default)/documents/${path}`,{headers:{Authorization:`Bearer ${t}`}});if(r.status===404)return null;if(!r.ok)throw new Error('FIRESTORE_READ_FAILED');return r.json();}
const fsVal=v=>typeof v==='string'?{stringValue:v}:typeof v==='number'?{doubleValue:v}:{booleanValue:v};
async function fsWrite(env,path,fields){const t=await googleAccessToken(env);const entries=Object.entries(fields);const mask=entries.map(([k])=>`updateMask.fieldPaths=${encodeURIComponent(k)}`).join('&');const r=await fetch(`https://firestore.googleapis.com/v1/projects/${env.FIREBASE_PROJECT_ID}/databases/(default)/documents/${path}?${mask}`,{method:'PATCH',headers:{Authorization:`Bearer ${t}`,'content-type':'application/json'},body:JSON.stringify({fields:Object.fromEntries(entries.map(([k,v])=>[k,fsVal(v)]))})});if(!r.ok)throw new Error('FIRESTORE_WRITE_FAILED');return r.json();}
async function authLookup(env,idToken){if(!idToken)throw new Error('AUTH_REQUIRED');const r=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=${env.FIREBASE_WEB_API_KEY}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({idToken})});if(!r.ok)throw new Error('AUTH_REQUIRED');return(await r.json()).users?.[0];}
async function fxRate(from,to){if(from===to)return 1;try{const r=await fetch(`https://open.er-api.com/v6/latest/${from}`);if(r.ok){const d=await r.json(),rate=Number(d?.rates?.[to]);if(rate>0)return rate;}}catch{}const a=FALLBACK_USD_RATES[from]||1,b=FALLBACK_USD_RATES[to]||1;return from==='NGN'&&to==='USD'?FALLBACK_USD_PER_NGN:(to==='NGN'&&from==='USD'?FALLBACK_USD_RATES.NGN:(1/a)*b);}
async function paystackPost(env,path,body){if(!env.PAYSTACK_SECRET_KEY)throw new Error('PAYSTACK_NOT_CONFIGURED');const r=await fetch(`https://api.paystack.co/${path}`,{method:'POST',headers:{Authorization:`Bearer ${env.PAYSTACK_SECRET_KEY}`,'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok||!d.status)throw new Error(d.message||`PAYSTACK_HTTP_${r.status}`);return d.data;}
async function paystackGet(env,path){if(!env.PAYSTACK_SECRET_KEY)throw new Error('PAYSTACK_NOT_CONFIGURED');const r=await fetch(`https://api.paystack.co/${path}`,{headers:{Authorization:`Bearer ${env.PAYSTACK_SECRET_KEY}`}});const d=await r.json().catch(()=>({}));if(!r.ok||!d.status)throw new Error(d.message||`PAYSTACK_HTTP_${r.status}`);return d.data;}
async function sendEmail(env,to,name,code,categories,amount,currency,codeExpires){if(!env.RESEND_API_KEY)return{sent:false,reason:'RESEND_NOT_CONFIGURED'};const recipient=String(to||'').trim().toLowerCase();if(!recipient)return{sent:false,reason:'RECIPIENT_EMAIL_MISSING'};const safe=String(name||'EduWills learner').replace(/[<>]/g,'');const from=String(env.RESEND_FROM_EMAIL||'').trim()||'EduWills <onboarding@resend.dev>';const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({from,to:[recipient],subject:'Your EduWills activation code',html:`<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto;padding:32px"><h2>EduWills</h2><p>Hello ${safe},</p><p>Your payment has been confirmed. Your activation code is:</p><div style="font-size:28px;font-weight:800;letter-spacing:5px;text-align:center;padding:20px;background:#f1f5f9">${code}</div><p><b>Category:</b> ${categories.join(', ')}</p><p><b>Payment:</b> ${currency} ${amount}</p><p><b>Redeem by:</b> ${new Date(codeExpires).toLocaleString('en-NG')}</p><p>After redemption, your activation lasts <b>1 year</b>.</p><p>For your security, this code can only be redeemed once.</p><p>Thank you for choosing EduWills.</p></div>`})});if(!r.ok){const detail=await r.text().catch(()=> '');return{sent:false,reason:`RESEND_${r.status}`,detail:detail.slice(0,300)};}return{sent:true};}
const usernameFromEmail=e=>String(e||'').split('@')[0].toLowerCase().replace(/[^a-z0-9._-]/g,'').replace(/^[._-]+|[._-]+$/g,'').slice(0,30);
async function processPayment(env,tx,authUser=null){if(tx?.metadata?.product!=='eduwills_activation'||tx.status!=='success')return{processed:false,reason:'IGNORED'};const uid=String(tx.metadata.uid||'');const categories=cleanCategories(tx.metadata.categories);if(!uid||!categories.length)throw new Error('INVALID_PAYMENT_METADATA');const paymentReference=String(tx.reference||'');const user=await fsGet(env,`users/${uid}`);if(!user)throw new Error('USER_NOT_FOUND');const uf=user.fields||{};const meta=tx.metadata||{};const authEmail=String(authUser?.email||'').trim().toLowerCase();const txEmail=String(tx?.customer?.email||meta.email||'').trim().toLowerCase();const email=authEmail||txEmail||String(uf.email?.stringValue||'').trim().toLowerCase();const name=String(uf.fullName?.stringValue||uf.displayName?.stringValue||meta.fullName||authUser?.displayName||tx?.customer?.first_name||'').trim();const username=String(uf.username?.stringValue||meta.username||'').trim()||usernameFromEmail(email);const identity={};if(email&&(!uf.email?.stringValue||uf.email.stringValue!==email))identity.email=email;if(name&&!uf.fullName?.stringValue)identity.fullName=name;if(username&&!uf.username?.stringValue)identity.username=username;if(Object.keys(identity).length)await fsWrite(env,`users/${uid}`,identity);const pending=uf.pendingActivationCode?.stringValue||'';if(pending){const old=await fsGet(env,`williTokens/${pending}`);if(old?.fields?.paymentReference?.stringValue===paymentReference){let sent=old.fields.activationCodeEmailSent?.booleanValue===true;let error=old.fields.activationCodeEmailError?.stringValue||'';if(!sent){const exp=old.fields.codeExpiresAt?.stringValue||new Date(Date.now()+7*86400000).toISOString();const amount=Number(tx.amount||0)/100;const currency=String(tx.currency||'NGN').toUpperCase();const er=await sendEmail(env,email,name,pending,categories,amount,currency,exp);sent=er.sent===true;error=er.sent?'':String(er.reason||'');await fsWrite(env,`williTokens/${pending}`,{activationCodeEmailSent:sent,activationCodeEmailError:error});await fsWrite(env,`users/${uid}`,{activationCodeEmailSent:sent,activationCodeEmailError:error});}return{processed:true,code:pending,emailSent:sent,emailError:error,activationExpiresAt:old.fields.expiresAt?.stringValue||'',categories};}}
const code=makeCode(),now=Date.now(),codeExpires=now+7*86400000,activationExpires=now+365*86400000,amount=Number(tx.amount||0)/100,currency=String(tx.currency||'NGN').toUpperCase(),path=`williTokens/${code}`;await fsWrite(env,path,{token:code,code,userId:uid,uid,username,email,categories:JSON.stringify(categories),duration:'1 year',durationMs:31536000000,createdAt:new Date(now).toISOString(),expiresAt:new Date(activationExpires).toISOString(),codeExpiresAt:new Date(codeExpires).toISOString(),used:false,redeemed:false,active:false,source:'paystack',paymentReference,paymentCurrency:currency,paymentAmount:amount,paymentId:Number(tx.id||0),paymentStatus:'success',activationCodeEmailSent:false});const er=await sendEmail(env,email,name,code,categories,amount,currency,codeExpires);const sent=er.sent===true,error=sent?'':String(er.reason||'');await fsWrite(env,path,{activationCodeEmailSent:sent,activationCodeEmailError:error});await fsWrite(env,`users/${uid}`,{pendingActivationCode:code,pendingActivationCodeExpiresAt:new Date(codeExpires).toISOString(),pendingActivationCategories:JSON.stringify(categories),pendingActivationPaymentReference:paymentReference,pendingActivationPaymentStatus:'success',activationPaymentAmount:amount,activationPaymentCurrency:currency,activationCodeEmailSent:sent,activationCodeEmailError:error});return{processed:true,code,emailSent:sent,emailError:error,activationExpiresAt:new Date(activationExpires).toISOString(),categories};}
async function redeemCode(env,idToken,code){const u=await authLookup(env,idToken);if(!u?.localId)throw new Error('AUTH_REQUIRED');const token=await fsGet(env,`williTokens/${code}`);if(!token)throw new Error('INVALID_ACTIVATION_CODE');const f=token.fields||{};if((f.userId?.stringValue||'')!==u.localId)throw new Error('CODE_NOT_FOR_USER');if(f.used?.booleanValue===true||f.redeemed?.booleanValue===true)throw new Error('ACTIVATION_CODE_ALREADY_USED');const exp=Date.parse(f.codeExpiresAt?.stringValue||'');if(!exp||exp<=Date.now())throw new Error('ACTIVATION_CODE_EXPIRED');const activationExpiry=f.expiresAt?.stringValue||new Date(Date.now()+365*86400000).toISOString(),categories=JSON.parse(f.categories?.stringValue||'[]');await fsWrite(env,`williTokens/${code}`,{used:true,redeemed:true,active:true,redeemedAt:new Date().toISOString(),redeemedBy:u.localId});await fsWrite(env,`users/${u.localId}`,{activated:true,activationStatus:'active',williTokenActive:true,activationExpiresAt:activationExpiry,categories:JSON.stringify(categories),activeCategories:JSON.stringify(categories),pendingActivationCode:'',pendingActivationCodeExpiresAt:''});return{activationExpiresAt:activationExpiry,categories};}
async function validHmac(secret,raw,sig){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-512'},false,['sign']);const s=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(raw));const h=[...new Uint8Array(s)].map(b=>b.toString(16).padStart(2,'0')).join('');return sig.length===h.length&&sig===h;}
async function handle(req,env){const origin=req.headers.get('origin')||'*';if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(origin)});const url=new URL(req.url);
if(req.method==='GET'&&url.pathname==='/health')return json({ok:true,service:'eduwills-payments',paystackConfigured:Boolean(env.PAYSTACK_SECRET_KEY),firebaseConfigured:Boolean(env.FIREBASE_SERVICE_ACCOUNT_JSON&&env.FIREBASE_WEB_API_KEY),resendConfigured:Boolean(env.RESEND_API_KEY),timestamp:new Date().toISOString()},200,origin);
if(req.method==='GET'&&url.pathname==='/paystack/verify'){try{const idToken=(req.headers.get('authorization')||'').replace(/^Bearer /,'');const u=await authLookup(env,idToken);if(!u?.emailVerified)return json({error:'Verify your email before confirming payment.'},403,origin);const reference=String(url.searchParams.get('reference')||'').trim();if(!reference)return json({error:'Missing payment reference.'},400,origin);const tx=await paystackGet(env,`transaction/verify/${encodeURIComponent(reference)}`);if(String(tx?.status||'').toLowerCase()!=='success')return json({error:'Paystack has not confirmed this payment yet.'},409,origin);if(String(tx?.metadata?.product||'')!=='eduwills_activation'||String(tx?.metadata?.uid||'')!==String(u.localId))return json({error:'Payment reference is not linked to this account.'},403,origin);const result=await processPayment(env,tx,u);const user=await fsGet(env,`users/${u.localId}`);const f=user?.fields||{};return json({ok:true,reference,categories:result.categories||cleanCategories(tx.metadata.categories),activationExpiresAt:result.activationExpiresAt||'',emailSent:f.activationCodeEmailSent?.booleanValue===true||result.emailSent===true,emailError:result.emailError||f.activationCodeEmailError?.stringValue||''},200,origin);}catch(e){const status=e.message==='AUTH_REQUIRED'?401:(e.message==='PAYSTACK_NOT_CONFIGURED'?503:500);return json({error:e.message||'PAYMENT_VERIFICATION_FAILED'},status,origin);}}
if(req.method!=='POST')return json({error:'POST required'},405,origin);
if(url.pathname==='/paystack/webhook'){const raw=await req.text();const sig=req.headers.get('x-paystack-signature')||'';if(!(await validHmac(env.PAYSTACK_SECRET_KEY,raw,sig)))return json({error:'Invalid signature'},401,origin);const event=JSON.parse(raw);if(event.event==='charge.success'){try{await processPayment(env,event.data);}catch(e){return json({error:e.message||'Webhook processing failed'},500,origin);}}return new Response('OK',{status:200,headers:cors(origin)});}
if(url.pathname==='/paystack/quote'){try{const idToken=(req.headers.get('authorization')||'').replace(/^Bearer /,'');const u=await authLookup(env,idToken);if(!u?.emailVerified)return json({error:'Verify your email before paying for activation.'},403,origin);const body=await req.json();const cats=cleanCategories(body.categories);if(!cats.length)return json({error:'Select at least one category.'},400,origin);const country=String(body.country||'INT').toUpperCase(),requestedCurrency=String(body.currency||COUNTRY_CURRENCY[country]||'USD').toUpperCase(),ngnTotal=baseTotal(cats);if(country==='NG'&&requestedCurrency==='NGN')return json({localCurrency:'NGN',localAmount:ngnTotal,paymentCurrency:'NGN',paymentAmount:ngnTotal,baseAmount:ngnTotal,international:false},200,origin);const usdRate=await fxRate('NGN','USD'),usdAmount=ngnTotal*usdRate+1,localCurrency=requestedCurrency==='NGN'?'USD':requestedCurrency,localRate=await fxRate('USD',localCurrency),localAmount=Math.round(usdAmount*localRate*100)/100;return json({localCurrency,localAmount,paymentCurrency:'USD',paymentAmount:Math.round(usdAmount*100)/100,baseAmount:ngnTotal,international:true},200,origin);}catch(e){return json({error:e.message||'Could not calculate quote.'},500,origin);}}
if(url.pathname==='/paystack/initialize'){try{const idToken=(req.headers.get('authorization')||'').replace(/^Bearer /,'');const u=await authLookup(env,idToken);if(!u?.emailVerified)return json({error:'Verify your email before paying for activation.'},403,origin);const body=await req.json(),cats=cleanCategories(body.categories);if(!cats.length)return json({error:'Select at least one category.'},400,origin);const amount=Number(body.amount),currency=String(body.paymentCurrency||body.currency||'NGN').toUpperCase();if(!Number.isFinite(amount)||amount<=0||!PAYSTACK_CURRENCIES.has(currency))return json({error:'Invalid payment amount or currency.'},400,origin);const ref=`EW-${u.localId.slice(0,8)}-${Date.now()}-${crypto.randomUUID().slice(0,8)}`;const data=await paystackPost(env,'transaction/initialize',{email:u.email,amount:Math.round(amount*100),currency,reference:ref,callback_url:env.CALLBACK_URL,metadata:{uid:u.localId,categories:cats,durationMs:31536000000,product:'eduwills_activation',country:body.country||'INT',email:u.email,fullName,username}});return json({reference:data.reference,authorization_url:data.authorization_url,access_code:data.access_code},200,origin);}catch(e){return json({error:e?.message||'PAYMENT_INITIALIZATION_FAILED'},500,origin);}}
if(url.pathname==='/redeem'){try{const idToken=(req.headers.get('authorization')||'').replace(/^Bearer /,'');const body=await req.json(),code=String(body.code||'').trim().toUpperCase();if(!/^[A-Z0-9]{10}$/.test(code))return json({error:'Invalid activation code format.'},400,origin);return json(await redeemCode(env,idToken,code),200,origin);}catch(e){const map={AUTH_REQUIRED:['Authentication required.',401],INVALID_ACTIVATION_CODE:['That activation code is invalid.',404],CODE_NOT_FOR_USER:['That activation code belongs to another account.',403],ACTIVATION_CODE_ALREADY_USED:['This activation code has already been used.',409],ACTIVATION_CODE_EXPIRED:['This activation code has expired.',410]};const [msg,status]=map[e.message]||[e.message||'Activation failed.',500];return json({error:msg},status,origin);}}
return json({error:'Not found'},404,origin);}
export default {fetch(req,env){return handle(req,env).catch(e=>json({error:e.message||'Server error'},500,req.headers.get('origin')||'*'));}};
