const ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const PRICES = { Primary: 2000, 'Junior Secondary': 3000, 'Senior Secondary': 3000, 'Book Learner': 4000 };
const COUNTRY_CURRENCY = { NG: 'NGN', US: 'USD', GB: 'GBP', GH: 'GHS', KE: 'KES', ZA: 'ZAR', CI: 'XOF' };
const PAYSTACK_CURRENCIES = new Set(['NGN', 'USD', 'GHS', 'KES', 'ZAR', 'XOF']);
const json = (body, status=200) => new Response(JSON.stringify(body), { status, headers: { 'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-headers':'authorization,content-type','access-control-allow-methods':'POST,OPTIONS' } });
const cleanCategories = c => [...new Set((Array.isArray(c)?c:[]).map(String).filter(x => Object.hasOwn(PRICES,x)))];
const baseTotal = c => cleanCategories(c).reduce((s,x)=>s+PRICES[x],0);
const makeCode = () => Array.from({length:10},()=>ALPHABET[Math.floor(Math.random()*ALPHABET.length)]).join('');
const b64 = a => btoa(String.fromCharCode(...new Uint8Array(a))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');

async function googleAccessToken(env) {
  const sa = JSON.parse(env.FIREBASE_SERVICE_ACCOUNT_JSON);
  const header = b64(new TextEncoder().encode(JSON.stringify({alg:'RS256',typ:'JWT'})));
  const now = Math.floor(Date.now()/1000);
  const claim = b64(new TextEncoder().encode(JSON.stringify({iss:sa.client_email,scope:'https://www.googleapis.com/auth/datastore https://www.googleapis.com/auth/cloud-platform',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600})));
  const keyData = sa.private_key.replace(/\\n/g,'\n');
  const key = await crypto.subtle.importKey('pkcs8', pemToDer(keyData), {name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'}, false, ['sign']);
  const sig = await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(`${header}.${claim}`));
  const jwt = `${header}.${claim}.${b64(sig)}`;
  const r = await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:`grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion=${encodeURIComponent(jwt)}`});
  if(!r.ok) throw new Error('GOOGLE_AUTH_FAILED');
  return (await r.json()).access_token;
}
function pemToDer(pem){const s=pem.replace(/-----BEGIN PRIVATE KEY-----|-----END PRIVATE KEY-----|\s/g,'');const bin=atob(s);const out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out.buffer;}
async function fsGet(env,path){const token=await googleAccessToken(env);const r=await fetch(`https://firestore.googleapis.com/v1/projects/${env.FIREBASE_PROJECT_ID}/databases/(default)/documents/${path}`,{headers:{Authorization:`Bearer ${token}`}});if(r.status===404)return null;if(!r.ok)throw new Error('FIRESTORE_READ_FAILED');return r.json();}
const fsVal = v => typeof v==='string'?{stringValue:v}:typeof v==='number'?{doubleValue:v}:{booleanValue:v};
async function fsWrite(env,path,fields){const token=await googleAccessToken(env);const r=await fetch(`https://firestore.googleapis.com/v1/projects/${env.FIREBASE_PROJECT_ID}/databases/(default)/documents/${path}`,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({fields:Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,fsVal(v)]))})});if(!r.ok)throw new Error('FIRESTORE_WRITE_FAILED');return r.json();}
async function authLookup(env,idToken){const r=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=${env.FIREBASE_WEB_API_KEY}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({idToken})});if(!r.ok)throw new Error('AUTH_REQUIRED');const d=await r.json();return d.users?.[0];}
async function fxRate(from,to){if(from===to)return 1;const r=await fetch(`https://open.er-api.com/v6/latest/${from}`);if(!r.ok)throw new Error('FX_PROVIDER_UNAVAILABLE');const d=await r.json();const rate=Number(d?.rates?.[to]);if(!rate)throw new Error('FX_RATE_UNAVAILABLE');return rate;}
async function paystack(env,path,body){const r=await fetch(`https://api.paystack.co/${path}`,{method:'POST',headers:{Authorization:`Bearer ${env.PAYSTACK_SECRET_KEY}`,'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok||!d.status)throw new Error(d.message||'PAYSTACK_ERROR');return d.data;}
async function sendEmail(env,to,name,code,categories,amount,currency,codeExpires){if(!env.RESEND_API_KEY)return;const safe=String(name||'EduWills learner').replace(/[<>]/g,'');const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({from:env.RESEND_FROM_EMAIL||'EduWills <onboarding@resend.dev>',to:[to],subject:'Your EduWills activation code',html:`<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto;padding:32px"><h2>EduWills</h2><p>Hello ${safe},</p><p>Your payment has been confirmed. Your activation code is:</p><div style="font-size:28px;font-weight:800;letter-spacing:5px;text-align:center;padding:20px;background:#f1f5f9">${code}</div><p><b>Category:</b> ${categories.join(', ')}</p><p><b>Payment:</b> ${currency} ${amount}</p><p><b>Redeem by:</b> ${new Date(codeExpires).toLocaleString('en-NG')}</p><p>After redemption, your activation lasts <b>1 year</b>.</p><p>For your security, this code can only be redeemed once.</p><p>Thank you for choosing EduWills.</p></div>`})});if(!r.ok)throw new Error('EMAIL_SEND_FAILED');}
async function processPayment(env,tx){if(tx?.metadata?.product!=='eduwills_activation'||tx.status!=='success')return;const uid=String(tx.metadata.uid||'');const categories=cleanCategories(tx.metadata.categories);if(!uid||!categories.length)throw new Error('INVALID_PAYMENT_METADATA');const code=makeCode();const now=Date.now();const codeExpires=now+7*86400000;const activationExpires=now+365*86400000;const amount=Number(tx.amount||0)/100;const currency=String(tx.currency||'NGN').toUpperCase();const path=`williTokens/${code}`;if(await fsGet(env,path))return;const user=await fsGet(env,`users/${uid}`);if(!user)throw new Error('USER_NOT_FOUND');const f=user.fields||{};const email=f.email?.stringValue||'';const name=f.fullName?.stringValue||f.displayName?.stringValue||'';await fsWrite(env,path,{token:code,code,userId:uid,uid,email,categories:JSON.stringify(categories),duration:'1 year',durationMs:31536000000,createdAt:new Date(now).toISOString(),expiresAt:new Date(activationExpires).toISOString(),codeExpiresAt:new Date(codeExpires).toISOString(),used:false,redeemed:false,active:false,source:'paystack',paymentReference:String(tx.reference||''),paymentCurrency:currency,paymentAmount:amount,paymentId:Number(tx.id||0),paymentStatus:'success'});await fsWrite(env,`users/${uid}`,{pendingActivationCode:code,pendingActivationCodeExpiresAt:new Date(codeExpires).toISOString(),pendingActivationCategories:JSON.stringify(categories),pendingActivationPaymentReference:String(tx.reference||''),pendingActivationPaymentStatus:'success',activationPaymentAmount:amount,activationPaymentCurrency:currency});if(email)await sendEmail(env,email,name,code,categories,amount,currency,codeExpires);}
async function validHmac(secret, raw, signature){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-512'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(raw));const hex=[...new Uint8Array(sig)].map(b=>b.toString(16).padStart(2,'0')).join('');return signature.length===hex.length&&signature===hex;}
async function handle(req,env){if(req.method==='OPTIONS')return json({},204);if(req.method!=='POST')return json({error:'POST required'},405);const url=new URL(req.url);if(url.pathname==='/paystack/webhook'){const raw=await req.text();const sig=req.headers.get('x-paystack-signature')||'';if(!(await validHmac(env.PAYSTACK_SECRET_KEY,raw,sig)))return json({error:'Invalid signature'},401);const event=JSON.parse(raw);if(event.event==='charge.success')await processPayment(env,event.data);return new Response('OK',{status:200});}
if(url.pathname==='/paystack/quote'){try{const idToken=(req.headers.get('authorization')||'').replace(/^Bearer /,'');const u=await authLookup(env,idToken);if(!u?.emailVerified)return json({error:'Verify your email before paying for activation.'},403);const body=await req.json();const cats=cleanCategories(body.categories);if(!cats.length)return json({error:'Select at least one category.'},400);const country=String(body.country||'INT').toUpperCase();const requestedCurrency=String(body.currency||COUNTRY_CURRENCY[country]||'USD').toUpperCase();const ngnTotal=baseTotal(cats);if(country==='NG')return json({localCurrency:'NGN',localAmount:ngnTotal,paymentCurrency:'NGN',paymentAmount:ngnTotal,baseAmount:ngnTotal});const usdRate=await fxRate('NGN','USD');const usdAmount=ngnTotal*usdRate+1;const localCurrency=requestedCurrency==='NGN'?'USD':requestedCurrency;if(!PAYSTACK_CURRENCIES.has(localCurrency)&&localCurrency!=='GBP')return json({error:'Currency not supported.'},400);const localRate=await fxRate('USD',localCurrency);const localAmount=Math.round(usdAmount*localRate*100)/100;return json({localCurrency,localAmount,paymentCurrency:'USD',paymentAmount:Math.round(usdAmount*100)/100,baseAmount:ngnTotal});}catch(e){return json({error:e.message||'Could not calculate quote.'},500);}}
if(url.pathname==='/paystack/initialize'){try{const idToken=(req.headers.get('authorization')||'').replace(/^Bearer /,'');const u=await authLookup(env,idToken);if(!u?.emailVerified)return json({error:'Verify your email before paying for activation.'},403);const body=await req.json();const cats=cleanCategories(body.categories);if(!cats.length)return json({error:'Select at least one category.'},400);const amount=Number(body.amount);const currency=String(body.currency||'NGN').toUpperCase();if(!Number.isFinite(amount)||amount<=0||!PAYSTACK_CURRENCIES.has(currency))return json({error:'Invalid payment amount or currency.'},400);const ref=`EW-${u.localId.slice(0,8)}-${Date.now()}-${crypto.randomUUID().slice(0,8)}`;const data=await paystack(env,'transaction/initialize',{email:u.email,amount:Math.round(amount*100),currency,reference:ref,callback_url:env.CALLBACK_URL,metadata:{uid:u.localId,categories:cats,durationMs:31536000000,product:'eduwills_activation',country:body.country||'INT'}});return json({reference:data.reference,authorization_url:data.authorization_url,access_code:data.access_code});}catch(e){return json({error:e.message},500);}}
return json({error:'Not found'},404);}
export default {fetch(req,env){return handle(req,env).catch(e=>json({error:e.message||'Server error'},500));}};
