'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Check, Crown, Image as ImageIcon, LogOut, Save, Shield, Trash2, UserPlus, Users } from 'lucide-react';
import { onAuthStateChanged } from 'firebase/auth';
import { arrayRemove, arrayUnion, collection, doc, getDoc, getDocs, limit, onSnapshot, query, serverTimestamp, setDoc, updateDoc, where } from 'firebase/firestore';
import { auth, db } from '@/lib/firebase';

const BASE='/eduwills';
const rules=[
  ['Be respectful','Treat every learner, admin and teacher with respect. No insults, harassment, bullying or targeted humiliation.'],
  ['Keep it academic','Use the group primarily for learning, revision, school collaboration and useful educational discussion.'],
  ['No harmful or illegal content','Do not share threats, instructions for wrongdoing, explicit sexual content, scams, malware or other unlawful material.'],
  ['No cheating services','Do not sell, request or distribute exam leaks, stolen papers, impersonation services or answers intended to facilitate academic dishonesty.'],
  ['Protect privacy','Do not post another person’s phone number, private messages, passwords, documents or personal information without permission.'],
  ['No spam or scams','No repeated advertising, referral spam, fake giveaways, suspicious payment requests or deceptive links.'],
  ['Respect intellectual property','Share books, notes and files only when you have permission or the right to distribute them.'],
  ['Follow admin decisions','Admins may remove content, restrict members or escalate serious violations. Do not bypass moderation actions.'],
  ['Report problems','Report suspicious, abusive or unsafe activity to an admin rather than retaliating.'],
  ['Understand possible penalties','Serious or repeated violations may lead to content removal, group restrictions, loss of group privileges, account suspension or other action under EDUWILLS policies.'],
];

function active(d:any){const e=d?.activationExpiresAt?.toMillis?.()||Date.parse(String(d?.activationExpiresAt||''))||0;return (d?.activationStatus==='active'||d?.activated===true||d?.williTokenActive===true||d?.activationActive===true||d?.isActive===true)&&(!e||e>Date.now());}

export default function GroupDetails(){
 const params=typeof window!=='undefined'?new URLSearchParams(location.search):null;const groupId=params?.get('id')||'';
 const [user,setUser]=useState<any>(null),[group,setGroup]=useState<any>(null),[profile,setProfile]=useState<any>({}),[loading,setLoading]=useState(true),[understood,setUnderstood]=useState(false),[saving,setSaving]=useState(false),[notice,setNotice]=useState(''),[name,setName]=useState(''),[description,setDescription]=useState(''),[avatar,setAvatar]=useState(''),[cover,setCover]=useState(''),[memberSearch,setMemberSearch]=useState(''),[memberResult,setMemberResult]=useState<any>(null),[pending,setPending]=useState<any[]>([]);
 useEffect(()=>onAuthStateChanged(auth,async u=>{if(!u){location.replace(`${BASE}/login/`);return}setUser(u);const s=await getDoc(doc(db,'users',u.uid));const p=s.data()||{};setProfile(p);if(!active(p)){location.replace(`${BASE}/dashboard/activation/`);return}setLoading(false)}),[]);
 useEffect(()=>{if(!groupId||!user)return;return onSnapshot(doc(db,'communityGroups',groupId),s=>{if(!s.exists()){setNotice('This group no longer exists.');setGroup(null);return}const d={id:s.id,...s.data()};setGroup(d);setName(d.name||'');setDescription(d.description||'');setAvatar(d.avatarUrl||'');setCover(d.coverImageUrl||'');setUnderstood(d.creatorRulesAccepted===true)},()=>setNotice('Could not load this group.'))},[groupId,user?.uid]);
 const isAdmin=!!group&&Array.isArray(group.adminIds)&&group.adminIds.includes(user?.uid);const isOwner=group?.ownerId===user?.uid;
 useEffect(()=>{if(!groupId||!isAdmin)return;return onSnapshot(query(collection(db,'communityJoinRequests'),where('groupId','==',groupId),where('status','==','pending'),limit(50)),s=>setPending(s.docs.map(d=>({id:d.id,...d.data()}))),()=>setPending([]))},[groupId,isAdmin]);
 const members=useMemo(()=>Array.isArray(group?.memberProfiles)?group.memberProfiles:[],[group]);
 async function acknowledge(){if(!group||!user)return;setSaving(true);try{await updateDoc(doc(db,'communityGroups',groupId),{creatorRulesAccepted:true,creatorRulesAcceptedAt:serverTimestamp()});setUnderstood(true);setNotice('Rules accepted. Your group workspace is now unlocked.')}catch(e:any){setNotice(e?.message||'Could not save your acknowledgement.')}finally{setSaving(false)}}
 async function saveDetails(){if(!isAdmin)return;setSaving(true);try{await updateDoc(doc(db,'communityGroups',groupId),{name:name.trim()||group.name,description:description.trim(),avatarUrl:avatar.trim(),coverImageUrl:cover.trim(),updatedAt:serverTimestamp(),adminIds:group.adminIds||[user.uid],memberIds:group.memberIds||[user.uid]});setNotice('Group details updated.')}catch(e:any){setNotice(e?.message||'Could not update group.')}finally{setSaving(false)}}
 async function findMember(){const q=memberSearch.trim().toLowerCase();if(!q){setMemberResult(null);return}try{const s=await getDoc(doc(db,'usernameIndex',q));if(s.exists()){const d=s.data();setMemberResult(d.uid===user.uid?null:d)}else setMemberResult(null)}catch{setMemberResult(null)}}
 async function addMember(uid:string){if(!isAdmin||!uid)return;try{await updateDoc(doc(db,'communityGroups',groupId),{memberIds:arrayUnion(uid),updatedAt:serverTimestamp(),adminIds:group.adminIds||[user.uid]});setNotice('Learner added to the group.');setMemberSearch('');setMemberResult(null)}catch(e:any){setNotice(e?.message||'Could not add learner.')}}
 async function approve(r:any){if(!isAdmin)return;try{await updateDoc(doc(db,'communityGroups',groupId),{memberIds:arrayUnion(r.userId),updatedAt:serverTimestamp(),adminIds:group.adminIds||[user.uid]});await updateDoc(doc(db,'communityJoinRequests',r.id),{status:'approved',reviewedBy:user.uid,reviewedAt:serverTimestamp()});setNotice(`${r.username?'@'+r.username:'Learner'} approved.`)}catch(e:any){setNotice(e?.message||'Could not approve request.')}}
 async function promote(uid:string){if(!isOwner||uid===user.uid)return;try{await updateDoc(doc(db,'communityGroups',groupId),{adminIds:arrayUnion(uid),updatedAt:serverTimestamp(),memberIds:group.memberIds||[user.uid]});setNotice('Member promoted to admin.')}catch(e:any){setNotice(e?.message||'Could not promote member.')}}
 async function removeMember(uid:string){if(!isAdmin||uid===group.ownerId||uid===user.uid)return;try{await updateDoc(doc(db,'communityGroups',groupId),{memberIds:arrayRemove(uid),adminIds:arrayRemove(uid),updatedAt:serverTimestamp()});setNotice('Member removed.')}catch(e:any){setNotice(e?.message||'Could not remove member.')}}
 async function leave(){if(!user||!group||isOwner){setNotice(isOwner?'The owner cannot leave. Transfer ownership or delete the group instead.':'');return}try{await updateDoc(doc(db,'communityGroups',groupId),{memberIds:arrayRemove(user.uid),adminIds:arrayRemove(user.uid),updatedAt:serverTimestamp()});location.assign(`${BASE}/dashboard/community/`)}catch(e:any){setNotice(e?.message||'Could not leave group.')}}
 async function removeGroup(){if(!isOwner)return;if(!confirm('Delete this group? This cannot be undone.'))return;try{await setDoc(doc(db,'communityGroups',groupId),{deleted:true,visibility:'private',memberIds:[],adminIds:[],updatedAt:serverTimestamp()},{merge:true});location.assign(`${BASE}/dashboard/community/`)}catch(e:any){setNotice(e?.message||'Could not delete group.')}}
 if(loading)return <main className="grid min-h-screen place-items-center bg-paper text-slate-500">Loading group…</main>;
 if(!group)return <main className="min-h-screen bg-paper p-6 text-ink"><a href={`${BASE}/dashboard/community/`} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-black"><ArrowLeft size={17}/> Community</a><div className="mx-auto mt-10 max-w-xl rounded-3xl bg-white p-8 text-center shadow-sm"><Users className="mx-auto text-slate-300" size={42}/><h1 className="mt-4 text-2xl font-black">Group unavailable</h1><p className="mt-2 text-sm text-slate-500">{notice||'This group could not be found.'}</p></div></main>;
 if(!understood)return <main className="min-h-screen bg-paper p-5 pb-10 text-ink sm:p-8"><div className="mx-auto max-w-3xl"><a href={`${BASE}/dashboard/community/`} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-black"><ArrowLeft size={17}/> Back to Community</a><section className="mt-6 overflow-hidden rounded-[2rem] bg-ink p-7 text-white shadow-2xl sm:p-10"><p className="text-[10px] font-black uppercase tracking-[.2em] text-cyan-200">Before you enter</p><h1 className="mt-3 text-3xl font-black sm:text-4xl">{group.name} has responsibilities.</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-300">Please read the group-owner and community rules before accessing your new group workspace. This protects you, your members and EDUWILLS.</p></section><section className="mt-5 rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><h2 className="text-xl font-black">Group do's & don'ts</h2><div className="mt-5 space-y-3">{rules.map(([title,text],i)=><article key={title} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-ink text-xs font-black text-white">{i+1}</span><div><h3 className="font-black">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{text}</p></div></div></article>)}</div><div className="mt-7 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-xs font-bold leading-6 text-amber-950">By continuing, you acknowledge that you have read these rules and understand that violations can lead to moderation or account/group penalties under EDUWILLS policies.</div><div className="mt-6 flex flex-col gap-3 sm:flex-row"><a href={`${BASE}/dashboard/community/`} className="rounded-xl border border-slate-200 px-5 py-3 text-center text-sm font-black">Cancel</a><button disabled={saving} onClick={acknowledge} className="rounded-xl bg-ink px-5 py-3 text-sm font-black text-white disabled:opacity-50">{saving?'Saving…':'Understood! Continue'}</button></div></section></div></main>;
 return <main className="min-h-screen bg-paper pb-12 text-ink"><header className="sticky top-0 z-40 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-5 py-4"><a href={`${BASE}/dashboard/community/`} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-black"><ArrowLeft size={17}/> Community</a><span className="inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-2 text-[10px] font-black text-emerald-700"><Check size={14}/> RULES ACKNOWLEDGED</span></div></header><div className="mx-auto max-w-6xl px-5 py-6 sm:px-8 sm:py-10">{notice&&<div className="mb-5 rounded-2xl border border-cyan-100 bg-cyan-50 p-4 text-sm font-bold text-cyan-950">{notice}</div>}<section className="overflow-hidden rounded-[2rem] bg-ink text-white shadow-2xl">{group.coverImageUrl&&<img src={group.coverImageUrl} alt="" className="h-40 w-full object-cover opacity-80"/>}<div className="flex flex-col gap-5 p-6 sm:flex-row sm:items-center sm:p-8"><div className="grid h-20 w-20 shrink-0 place-items-center overflow-hidden rounded-3xl border border-white/15 bg-white/10">{group.avatarUrl?<img src={group.avatarUrl} alt="" className="h-full w-full object-cover"/>:<Users size={32}/>}</div><div className="min-w-0 flex-1"><p className="text-[10px] font-black uppercase tracking-[.2em] text-cyan-200">STUDY GROUP</p><h1 className="mt-2 text-3xl font-black">{group.name}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">{group.description||'A focused EDUWILLS learning community.'}</p></div><div className="rounded-2xl bg-white/10 px-5 py-4 text-center"><b className="block text-2xl">{Array.isArray(group.memberIds)?group.memberIds.length:0}</b><span className="text-[10px] font-black uppercase tracking-wider text-slate-300">Members</span></div></div></section>
 <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_.8fr]">{isAdmin&&<section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><Shield size={19}/><h2 className="text-xl font-black">Group management</h2></div><div className="mt-5 grid gap-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Group name" className="rounded-xl border border-slate-200 bg-paper px-4 py-3 text-sm font-bold"/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Group description" className="min-h-24 rounded-xl border border-slate-200 bg-paper px-4 py-3 text-sm font-bold"/><div className="grid gap-3 sm:grid-cols-2"><label className="rounded-xl border border-slate-200 p-3"><span className="flex items-center gap-2 text-xs font-black"><ImageIcon size={15}/> Group picture URL</span><input value={avatar} onChange={e=>setAvatar(e.target.value)} className="mt-2 w-full bg-transparent text-xs outline-none" placeholder="https://…"/></label><label className="rounded-xl border border-slate-200 p-3"><span className="flex items-center gap-2 text-xs font-black"><ImageIcon size={15}/> Cover picture URL</span><input value={cover} onChange={e=>setCover(e.target.value)} className="mt-2 w-full bg-transparent text-xs outline-none" placeholder="https://…"/></label></div><button disabled={saving} onClick={saveDetails} className="inline-flex items-center justify-center gap-2 rounded-xl bg-ink px-5 py-3 text-sm font-black text-white"><Save size={16}/>{saving?'Saving…':'Save group details'}</button></div></section>}
 <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-700">MEMBERS</p><h2 className="text-xl font-black">People in this group</h2></div><span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-black">{Array.isArray(group.memberIds)?group.memberIds.length:0}</span></div>{isAdmin&&<div className="mt-4 flex gap-2"><input value={memberSearch} onChange={e=>setMemberSearch(e.target.value)} placeholder="Username to add" className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-paper px-4 py-3 text-sm font-bold"/><button onClick={findMember} className="rounded-xl bg-ink px-4 py-3 text-xs font-black text-white">Find</button></div>}{memberResult&&<div className="mt-3 flex items-center justify-between rounded-2xl border border-cyan-100 bg-cyan-50 p-3"><span className="text-sm font-bold">@{memberResult.username}</span><button onClick={()=>addMember(memberResult.uid)} className="rounded-xl bg-ink px-3 py-2 text-xs font-black text-white"><UserPlus size={14}/></button></div>}<div className="mt-5 space-y-2">{(group.memberIds||[]).slice(0,100).map((uid:string)=><div key={uid} className="flex items-center gap-3 rounded-2xl border border-slate-200 p-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-slate-100 text-xs font-black">{uid===group.ownerId?'★':'•'}</span><span className="min-w-0 flex-1"><b className="block truncate">{uid===user.uid?'You':uid===group.ownerId?'Group owner':`Member ${uid.slice(0,6)}`}</b><small className="text-slate-400">{(group.adminIds||[]).includes(uid)?'Admin':'Member'}</small></span>{isOwner&&uid!==user.uid&&uid!==group.ownerId&&!(group.adminIds||[]).includes(uid)&&<button onClick={()=>promote(uid)} className="rounded-lg border border-slate-200 px-2 py-1.5 text-[10px] font-black">Make admin</button>}{isAdmin&&uid!==user.uid&&uid!==group.ownerId&&<button onClick={()=>removeMember(uid)} className="rounded-lg border border-red-200 px-2 py-1.5 text-[10px] font-black text-red-700">Remove</button>}</div>)}{(group.memberIds||[]).length>100&&<p className="text-center text-xs font-bold text-slate-400">Showing first 100 members.</p>}</div></section>
 <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><Crown size={18}/><h2 className="text-xl font-black">Admins</h2></div><div className="mt-4 flex flex-wrap gap-2">{(group.adminIds||[]).map((uid:string)=><span key={uid} className="rounded-full bg-slate-100 px-3 py-2 text-xs font-black">{uid===group.ownerId?'👑 Owner':'🛡️ Admin'} · {uid.slice(0,8)}</span>)}</div>{isAdmin&&<p className="mt-4 text-xs leading-5 text-slate-500">Admins can moderate the group. The owner can promote additional admins.</p>}</section>
 {isAdmin&&pending.length>0&&<section className="rounded-3xl border border-amber-200 bg-amber-50 p-6 shadow-sm"><h2 className="text-xl font-black">Join requests</h2><div className="mt-4 space-y-2">{pending.map(r=><div key={r.id} className="flex items-center gap-3 rounded-2xl bg-white p-3"><span className="min-w-0 flex-1 text-sm font-bold">@{r.username||'learner'}</span><button onClick={()=>approve(r)} className="rounded-xl bg-ink px-3 py-2 text-xs font-black text-white">Approve</button></div>)}</div></section>}
 <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Safety & actions</h2><p className="mt-2 text-sm leading-6 text-slate-500">Keep the group focused and safe. You can leave at any time unless you are the owner.</p><div className="mt-5 flex flex-wrap gap-2"><button onClick={leave} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-xs font-black"><LogOut size={15}/> Leave group</button>{isOwner&&<button onClick={removeGroup} className="inline-flex items-center gap-2 rounded-xl border border-red-200 px-4 py-3 text-xs font-black text-red-700"><Trash2 size={15}/> Delete group</button>}</div></section></div></div></main>;
}
