'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,Check,ImagePlus,MessageCircle,Save,Settings,Shield,Send,Trash2,UserPlus,Users} from 'lucide-react';
import {onAuthStateChanged} from 'firebase/auth';
import {addDoc,arrayRemove,arrayUnion,collection,doc,getDoc,onSnapshot,orderBy,query,serverTimestamp,updateDoc,where,limit} from 'firebase/firestore';
import {auth,db} from '@/lib/firebase';
import DeviceImageUpload from '@/components/DeviceImageUpload';
const BASE='/eduwills';
const rules=[['Be respectful','No harassment, bullying, insults or targeted humiliation.'],['Keep it academic','Use the group for learning, revision and useful educational collaboration.'],['No nudity or sexual content','Profile, group and shared images must not contain nudity or sexually explicit material.'],['No scams or harmful content','No malware, threats, illegal content, scams or deceptive links.'],['Protect privacy','Do not expose another person’s private information without permission.'],['No exam leaks','Do not share stolen papers, leaked answers or services that facilitate cheating.'],['Respect copyright','Only share files you have permission or the right to distribute.'],['Follow moderation','Admins may remove content and escalate serious violations.']];
const active=(d:any)=>{const e=d?.activationExpiresAt?.toMillis?.()||Date.parse(String(d?.activationExpiresAt||''))||0;return(d?.activationStatus==='active'||d?.activated===true||d?.williTokenActive===true||d?.activationActive===true||d?.isActive===true)&&(!e||e>Date.now())};
export default function Group(){const id=new URLSearchParams(typeof window!=='undefined'?location.search:'').get('id')||'';const[user,setUser]=useState<any>(null),[profile,setProfile]=useState<any>({}),[g,setG]=useState<any>(null),[loading,setLoading]=useState(true),[understood,setUnderstood]=useState(false),[tour,setTour]=useState(true),[settings,setSettings]=useState(false),[name,setName]=useState(''),[desc,setDesc]=useState(''),[avatar,setAvatar]=useState(''),[cover,setCover]=useState(''),[messages,setMessages]=useState<any[]>([]),[draft,setDraft]=useState(''),[notice,setNotice]=useState(''),[members,setMembers]=useState<any[]>([]),[memberSearch,setMemberSearch]=useState('');
 useEffect(()=>onAuthStateChanged(auth,async u=>{if(!u){location.replace(BASE+'/login/');return}setUser(u);const s=await getDoc(doc(db,'users',u.uid));const p=s.data()||{};setProfile(p);if(!active(p)){location.replace(BASE+'/dashboard/activation/');return}setLoading(false)}),[]);
 useEffect(()=>{if(!id||!user)return onSnapshot(doc(db,'communityGroups',id),()=>{});return onSnapshot(doc(db,'communityGroups',id),s=>{if(!s.exists()){setNotice('This group no longer exists.');setG(null);return}const d={id:s.id,...s.data()};if(d.deleted){setNotice('This group has been deleted.');setG(null);return}setG(d);setName(d.name||'');setDesc(d.description||'');setAvatar(d.avatarUrl||'');setCover(d.coverImageUrl||'');setUnderstood(d.creatorRulesAccepted===true||d.ownerId!==user.uid)})},[id,user?.uid]);
 useEffect(()=>{if(!g||!user||!understood)return;return onSnapshot(query(collection(db,'communityGroups',id,'messages'),orderBy('createdAt','asc'),limit(200)),s=>setMessages(s.docs.map(x=>({id:x.id,...x.data()}))),()=>setMessages([]))},[g?.id,understood]);
 const isAdmin=!!g?.adminIds?.includes(user?.uid),isOwner=g?.ownerId===user?.uid;
 async function acknowledge(){try{await updateDoc(doc(db,'communityGroups',id),{creatorRulesAccepted:true,creatorRulesAcceptedAt:serverTimestamp()});setUnderstood(true);setTour(true)}catch(e:any){setNotice(e?.message||'Could not save your acknowledgement.')}}
 async function save(){if(!isAdmin)return;try{await updateDoc(doc(db,'communityGroups',id),{name:name.trim()||g.name,description:desc.trim(),avatarUrl:avatar,coverImageUrl:cover,updatedAt:serverTimestamp(),memberCount:Array.isArray(g.memberIds)?g.memberIds.length:0});setNotice('Settings saved.')}catch(e:any){setNotice(e?.message||'Could not save settings.')}}
 async function send(){if(!draft.trim()||!user)return;const text=draft.trim();setDraft('');try{await addDoc(collection(db,'communityGroups',id,'messages'),{senderId:user.uid,senderUsername:profile.username||'',senderName:profile.fullName||'Learner',senderPhotoURL:profile.photoURL||profile.avatarUrl||'',text,createdAt:serverTimestamp()})}catch(e:any){setNotice(e?.message||'Message could not be sent.')}}
 async function addByUsername(){const q=memberSearch.trim().toLowerCase();if(!q||!isAdmin)return;try{const s=await getDoc(doc(db,'usernameIndex',q));if(!s.exists())throw new Error('Username not found.');await updateDoc(doc(db,'communityGroups',id),{memberIds:arrayUnion(s.data().uid),updatedAt:serverTimestamp()});setMemberSearch('');setNotice('Learner added.')}catch(e:any){setNotice(e?.message||'Could not add learner.')}}
 async function remove(){if(!isOwner)return;if(!confirm('Delete this group?'))return;try{await updateDoc(doc(db,'communityGroups',id),{deleted:true,visibility:'private',memberIds:[],adminIds:[],updatedAt:serverTimestamp()});location.assign(BASE+'/dashboard/community/')}catch(e:any){setNotice(e?.message||'Could not delete group.')}}
 if(loading)return <main className="grid min-h-screen place-items-center bg-paper font-bold text-slate-500">Loading group…</main>;
 if(!g)return <main className="min-h-screen bg-paper p-6"><a href={BASE+'/dashboard/community/'} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-3 text-sm font-black"><ArrowLeft size={17}/> Community</a><div className="mx-auto mt-12 max-w-xl rounded-3xl bg-white p-8 text-center"><Users className="mx-auto text-slate-300" size={40}/><h1 className="mt-4 text-2xl font-black">Group unavailable</h1><p className="mt-2 text-sm text-slate-500">{notice}</p></div></main>;
 if(!understood)return <main className="min-h-screen bg-paper p-5 text-ink"><div className="mx-auto max-w-3xl"><a href={BASE+'/dashboard/community/'} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-3 text-sm font-black"><ArrowLeft size={17}/> Community</a><section className="mt-5 rounded-[2rem] bg-ink p-7 text-white"><p className="text-[10px] font-black uppercase tracking-[.2em] text-cyan-200">GROUP OWNER ONBOARDING</p><h1 className="mt-3 text-3xl font-black">Before you open {g.name}</h1><p className="mt-3 text-sm leading-6 text-slate-300">Read the rules. After you acknowledge them, the group environment opens immediately and the admin guidance begins inside the workspace.</p></section><section className="mt-5 max-h-[60vh] overflow-y-auto rounded-3xl border bg-white p-5">{rules.map((r,i)=><article key={r[0]} className="border-b border-slate-100 py-4 last:border-0"><div className="flex gap-3"><b className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-ink text-xs text-white">{i+1}</b><div><h2 className="font-black">{r[0]}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{r[1]}</p></div></div></article>)}</section><button onClick={acknowledge} className="mt-5 w-full rounded-xl bg-ink px-5 py-4 text-sm font-black text-white">Understood! Continue</button></div></main>;
 return <main className="min-h-screen bg-paper pb-8 text-ink"><header className="sticky top-0 z-40 border-b bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-5 py-4"><a href={BASE+'/dashboard/community/'} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-black"><ArrowLeft size={17}/> Community</a><div className="flex items-center gap-2"><span className="hidden rounded-full bg-emerald-50 px-3 py-2 text-[10px] font-black text-emerald-700 sm:inline">GROUP OPEN</span>{isAdmin&&<button onClick={()=>setSettings(v=>!v)} className="rounded-xl bg-ink p-3 text-white" title="Settings"><Settings size={18}/></button>}</div></div></header><div className="mx-auto max-w-6xl px-5 py-6"><section className="overflow-hidden rounded-[2rem] bg-ink text-white shadow-2xl">{g.coverImageUrl&&<img src={g.coverImageUrl} className="h-36 w-full object-cover opacity-80"/>}<div className="flex flex-col gap-4 p-6 sm:flex-row sm:items-center sm:p-8"><div className="grid h-20 w-20 shrink-0 place-items-center overflow-hidden rounded-3xl bg-white/10">{g.avatarUrl?<img src={g.avatarUrl} className="h-full w-full object-cover"/>:<Users size={32}/>}</div><div className="min-w-0 flex-1"><p className="text-[10px] font-black uppercase tracking-[.2em] text-cyan-200">STUDY GROUP</p><h1 className="mt-2 text-3xl font-black">{g.name}</h1><p className="mt-2 text-sm leading-6 text-slate-300">{g.description||'EDUWILLS academic community'}</p></div><div className="rounded-2xl bg-white/10 px-5 py-4 text-center"><b className="block text-2xl">{g.memberIds?.length||1}</b><span className="text-[10px] font-black text-slate-300">MEMBERS</span></div></div></section>
 {tour&&isAdmin&&<section className="mt-5 rounded-3xl border-2 border-cyan-200 bg-cyan-50 p-5"><p className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-700">ADMIN QUICK TOUR</p><h2 className="mt-1 text-xl font-black">Your group workspace is ready.</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-white p-4"><Settings className="text-cyan-700" size={19}/><p className="mt-2 font-black">Settings button</p><p className="mt-1 text-xs leading-5 text-slate-500">Edit the group name, description and pictures.</p></div><div className="rounded-2xl bg-white p-4"><ImagePlus className="text-cyan-700" size={19}/><p className="mt-2 font-black">Upload button</p><p className="mt-1 text-xs leading-5 text-slate-500">Upload a group picture or cover directly from your device.</p></div><div className="rounded-2xl bg-white p-4"><UserPlus className="text-cyan-700" size={19}/><p className="mt-2 font-black">Members</p><p className="mt-1 text-xs leading-5 text-slate-500">Add learners, manage membership and appoint admins.</p></div><div className="rounded-2xl bg-white p-4"><MessageCircle className="text-cyan-700" size={19}/><p className="mt-2 font-black">Message box</p><p className="mt-1 text-xs leading-5 text-slate-500">Type directly in the group conversation below.</p></div></div><button onClick={()=>setTour(false)} className="mt-4 rounded-xl bg-ink px-4 py-3 text-xs font-black text-white">Got it</button></section>}
 <div className="mt-6 grid gap-6 lg:grid-cols-[.8fr_1.2fr]">{isAdmin&&settings&&<section className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><Settings size={19}/><h2 className="text-xl font-black">Settings</h2></div><div className="mt-5 space-y-3"><input value={name} onChange={e=>setName(e.target.value)} className="w-full rounded-xl border bg-paper px-4 py-3 text-sm font-bold" placeholder="Group name"/><textarea value={desc} onChange={e=>setDesc(e.target.value)} className="min-h-24 w-full rounded-xl border bg-paper px-4 py-3 text-sm font-bold" placeholder="Description"/><div className="rounded-2xl border p-4"><p className="mb-2 text-xs font-black">Group picture</p><DeviceImageUpload uid={user.uid} path={'community/'+id} label="Upload group picture" onUploaded={u=>setAvatar(u)}/>{avatar&&<img src={avatar} className="mt-3 h-20 w-20 rounded-2xl object-cover"/>}</div><div className="rounded-2xl border p-4"><p className="mb-2 text-xs font-black">Cover picture</p><DeviceImageUpload uid={user.uid} path={'community/'+id} label="Upload cover picture" onUploaded={u=>setCover(u)}/>{cover&&<img src={cover} className="mt-3 h-24 w-full rounded-2xl object-cover"/>}</div><button onClick={save} className="inline-flex items-center gap-2 rounded-xl bg-ink px-5 py-3 text-sm font-black text-white"><Save size={16}/>Save settings</button>{isOwner&&<button onClick={remove} className="ml-2 inline-flex items-center gap-2 rounded-xl bg-red-600 px-5 py-3 text-sm font-black text-white"><Trash2 size={16}/>Delete group</button>}</div></section>}
 <section className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-700">GROUP CHAT</p><h2 className="text-xl font-black">Conversation</h2></div><span className="rounded-full bg-slate-100 px-3 py-1.5 text-[10px] font-black">{g.memberIds?.length||1} members</span></div><div className="mt-4 h-[55vh] min-h-80 space-y-3 overflow-y-auto rounded-2xl bg-slate-50 p-4">{messages.length?messages.map(m=><div key={m.id} className={'flex gap-3 '+(m.senderId===user.uid?'justify-end':'')}><div className="max-w-[85%] rounded-2xl border bg-white px-4 py-3"><div className="flex items-center gap-2"><div className="grid h-7 w-7 place-items-center overflow-hidden rounded-full bg-ink text-[9px] font-black text-white">{m.senderPhotoURL?<img src={m.senderPhotoURL} className="h-full w-full object-cover"/>:String(m.senderName||m.senderUsername||'L')[0]}</div><span className="text-[10px] font-black text-slate-400">{m.senderName||m.senderUsername||'Learner'}</span></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{m.text}</p></div></div>):<div className="grid h-full place-items-center text-center"><div><MessageCircle className="mx-auto text-slate-300" size={35}/><p className="mt-3 font-black">Start the conversation.</p><p className="mt-1 text-xs text-slate-400">Your message box is right here.</p></div></div>}</div><div className="mt-3 flex gap-2"><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Type a message…" className="min-w-0 flex-1 rounded-xl border bg-paper px-4 py-3 text-sm font-bold"/><button onClick={send} className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-ink text-white"><Send size={17}/></button></div></section></div></div></main>}
