'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2, GraduationCap, Sparkles, Target, Trophy, Brain, Clock3, LibraryBig, FileText } from 'lucide-react';
import { onAuthStateChanged } from 'firebase/auth';
import { doc, getDoc } from 'firebase/firestore';
import { auth, db } from '@/lib/firebase';

const BASE = '/eduwills';
const CATEGORIES = {
  primary: { label: 'Primary', eyebrow: 'FOUNDATION LEARNING', description: 'Build strong foundations with age-appropriate practice, revision and confidence-building activities.', subjects: ['English Language', 'Mathematics', 'Basic Science', 'General Knowledge'], modes: ['Normal Test'], tips: ['Practise a little every day', 'Strengthen reading and numeracy', 'Review mistakes before moving on'], action: 'Start daily practice' },
  junior: { label: 'Junior Secondary', eyebrow: 'JUNIOR SECONDARY', description: 'Build steady JSS progress through subject practice, revision and preparation for Nigerian junior-secondary examinations.', subjects: ['English Language', 'Mathematics', 'Basic Science', 'Social Studies'], modes: ['BECE', 'NECO', 'Normal Test'], tips: ['Master your core subjects', 'Practise exam-style questions', 'Use mistakes to guide revision'], action: 'Start JSS practice' },
  senior: { label: 'Senior Secondary', eyebrow: 'SENIOR SECONDARY', description: 'Prepare for WAEC, JAMB and NECO while building strong subject knowledge and exam confidence.', subjects: ['English Language', 'Mathematics', 'Biology', 'Chemistry'], modes: ['WAEC', 'JAMB', 'NECO', 'Normal Test'], tips: ['Mix revision with timed practice', 'Study your weak areas first', 'Review explanations after every test'], action: 'Start exam practice' },
  book: { label: 'Book Learner', eyebrow: 'BOOK LEARNING', description: 'Turn the books you are learning into active practice with grounded quizzes and focused recall.', subjects: ['Characters & relationships', 'Events & chronology', 'Themes & conflicts', 'Distinctive details'], modes: ['Book Quiz'], tips: ['Read before testing yourself', 'Use chapter details as evidence', 'Revisit questions you miss'], action: 'Create a book quiz' },
} as const;

type CategoryId = keyof typeof CATEGORIES;
function normalizeCategory(value: string | null): CategoryId { const v = String(value || '').trim().toLowerCase(); if (v === 'primary') return 'primary'; if (v === 'junior' || v === 'jss' || v === 'junior-secondary') return 'junior'; if (v === 'senior' || v === 'sss' || v === 'senior-secondary') return 'senior'; return 'book'; }

export default function CategoryHub() {
  const [category, setCategory] = useState<CategoryId>('book'); const [allowed, setAllowed] = useState(true); const [loading, setLoading] = useState(true);
  useEffect(() => { const requested = normalizeCategory(new URLSearchParams(window.location.search).get('category')); setCategory(requested); const unsubscribe = onAuthStateChanged(auth, async (u) => { if (!u) { window.location.replace(`${BASE}/login/`); return; } try { const snap = await getDoc(doc(db, 'users', u.uid)); const d = snap.data() || {}; const values = [...(Array.isArray(d.categories) ? d.categories : []), ...(Array.isArray(d.educationLevels) ? d.educationLevels : []), ...(Array.isArray(d.schoolLevels) ? d.schoolLevels : []), d.category, d.educationLevel, d.schoolLevel].map(x => String(x || '').toLowerCase()); const active = String(d.activeCategoryId || d.activeCategory || '').toLowerCase(); setAllowed(requested === 'book' || values.some(v => v.includes(requested)) || active === requested); } catch { setAllowed(false); } finally { setLoading(false); } }); return () => unsubscribe(); }, []);
  const config = CATEGORIES[category];
  const modeLinks = useMemo(() => config.modes.map(mode => ({ mode, href: category === 'book' ? `${BASE}/dashboard/quiz/` : `${BASE}/dashboard/category-quiz/?category=${category}&mode=${encodeURIComponent(mode.toLowerCase().replace(/\s+/g, '-'))}` })), [category, config]);
  if (loading) return <main className="min-h-screen bg-paper p-8 text-center font-bold text-slate-500">Loading your learning category…</main>;
  if (!allowed) return <main className="min-h-screen bg-paper p-5 text-ink"><div className="mx-auto max-w-3xl py-16"><a href={`${BASE}/dashboard/`} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-black"><ArrowLeft size={17}/> Dashboard</a><section className="mt-7 rounded-[2rem] border border-amber-200 bg-amber-50 p-7 text-amber-950 shadow-sm"><p className="text-xs font-black uppercase tracking-[.18em]">Category access</p><h1 className="mt-2 text-3xl font-black">This category is not assigned to your account.</h1><p className="mt-3 text-sm leading-6">Return to Personal and select one of your assigned learning categories.</p><a href={`${BASE}/dashboard/personal/`} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-amber-950 px-5 py-3 text-sm font-black text-white">Switch category <ArrowRight size={16}/></a></section></div></main>;
  return <main className="min-h-screen bg-paper pb-24 text-ink"><header className="sticky top-0 z-40 border-b border-slate-200/80 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 sm:px-8"><a href={`${BASE}/dashboard/`} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2 text-sm font-black"><ArrowLeft size={17}/> Dashboard</a><div className="flex items-center gap-2 text-sm font-black"><span className="grid h-9 w-9 place-items-center rounded-xl bg-ink text-white"><BookOpen size={17}/></span> EDUWILLS</div></div></header>
    <div className="mx-auto max-w-7xl px-5 py-7 sm:px-8 sm:py-10"><section className="relative overflow-hidden rounded-[2rem] bg-ink p-7 text-white shadow-2xl sm:p-10 lg:p-12"><div className="pointer-events-none absolute -right-20 -top-24 h-80 w-80 rounded-full bg-cyan-400/10 blur-3xl"/><div className="relative grid gap-10 lg:grid-cols-[1.25fr_.75fr] lg:items-end"><div><p className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-[10px] font-black uppercase tracking-[.2em] text-cyan-200"><GraduationCap size={13}/>{config.eyebrow}</p><h1 className="mt-5 text-3xl font-black leading-tight sm:text-5xl">Learn with purpose.<br/><span className="text-cyan-200">Grow with every session.</span></h1><p className="mt-5 max-w-2xl text-sm leading-7 text-slate-300">{config.description}</p><div className="mt-7 flex flex-wrap gap-3"><a href={modeLinks[0]?.href || `${BASE}/dashboard/quiz/`} className="inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3.5 text-sm font-black text-ink">{config.action} <ArrowRight size={17}/></a><a href={`${BASE}/dashboard/history/`} className="inline-flex items-center gap-2 rounded-xl border border-white/15 bg-white/10 px-5 py-3.5 text-sm font-black">View progress <Trophy size={16}/></a></div></div><div className="rounded-3xl border border-white/10 bg-white/5 p-6 backdrop-blur"><p className="text-[10px] font-black uppercase tracking-[.18em] text-slate-400">Your study direction</p><div className="mt-5 space-y-4">{config.tips.map((tip,i)=><div key={tip} className="flex gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-cyan-400/10 text-xs font-black text-cyan-200">{i+1}</span><p className="pt-1 text-sm font-bold leading-5 text-slate-200">{tip}</p></div>)}</div></div></div></section>
      <section className="mt-7 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-7"><div className="flex items-start justify-between gap-5"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-700">Core subjects</p><h2 className="mt-2 text-2xl font-black">What will you work on?</h2><p className="mt-2 text-sm leading-6 text-slate-500">Choose a subject to enter focused practice. Your selected category stays attached to the learning session.</p></div><Brain className="text-cyan-600" size={27}/></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{config.subjects.map((subject,i)=><a key={subject} href={modeLinks[0]?.href || `${BASE}/dashboard/quiz/`} className="group rounded-2xl border border-slate-200 p-4 transition hover:-translate-y-0.5 hover:border-cyan-300 hover:shadow-md"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100"><BookOpen size={17}/></span><div><p className="text-sm font-black">{subject}</p><p className="mt-0.5 text-[11px] font-bold text-slate-400">{i===0?'Recommended starting point':'Focused practice'}</p></div><ArrowRight className="ml-auto text-slate-300 group-hover:text-cyan-600" size={17}/></div></a>)}</div></div><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-7"><p className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-700">Study smarter</p><h2 className="mt-2 text-2xl font-black">Build active recall.</h2><p className="mt-3 text-sm leading-6 text-slate-500">Testing yourself is more useful than simply rereading. Use explanations and results to decide what deserves another review.</p><div className="mt-6 space-y-3"><div className="flex gap-3 rounded-2xl bg-slate-50 p-4"><Target className="mt-0.5 text-cyan-600" size={19}/><div><p className="text-sm font-black">Set a clear target</p><p className="mt-1 text-xs leading-5 text-slate-500">Choose one subject or exam mode for the next session.</p></div></div><div className="flex gap-3 rounded-2xl bg-slate-50 p-4"><Clock3 className="mt-0.5 text-cyan-600" size={19}/><div><p className="text-sm font-black">Practise consistently</p><p className="mt-1 text-xs leading-5 text-slate-500">Short, focused sessions can build stronger recall over time.</p></div></div><div className="flex gap-3 rounded-2xl bg-slate-50 p-4"><CheckCircle2 className="mt-0.5 text-cyan-600" size={19}/><div><p className="text-sm font-black">Review what you miss</p><p className="mt-1 text-xs leading-5 text-slate-500">Use explanations and repeat weak areas instead of guessing again.</p></div></div></div></div></section>
      <section className="mt-7 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-700">Practice pathways</p><h2 className="mt-2 text-2xl font-black">Choose how you want to practise.</h2></div><Sparkles className="text-cyan-600" size={24}/></div><div className="mt-6 flex flex-wrap gap-3">{modeLinks.map(({mode,href})=><a key={mode} href={href} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-black transition hover:border-cyan-300 hover:bg-white"><FileText size={16} className="text-cyan-600"/>{mode}<ArrowRight size={15} className="text-slate-400"/></a>)}</div><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-cyan-50 p-5"><LibraryBig className="text-cyan-700" size={21}/><p className="mt-3 text-sm font-black">Curriculum-focused</p><p className="mt-1 text-xs leading-5 text-slate-600">Practice is aligned to the selected Nigerian learning pathway.</p></div><div className="rounded-2xl bg-slate-50 p-5"><Brain className="text-slate-700" size={21}/><p className="mt-3 text-sm font-black">Active recall</p><p className="mt-1 text-xs leading-5 text-slate-600">Use questions to expose what you know and what needs work.</p></div><div className="rounded-2xl bg-amber-50 p-5"><Trophy className="text-amber-700" size={21}/><p className="mt-3 text-sm font-black">Progress over time</p><p className="mt-1 text-xs leading-5 text-slate-600">When available, review your results and let performance guide revision.</p></div></div></section>
    </div>
    <nav className="fixed bottom-0 left-0 right-0 z-50 border-t border-slate-200 bg-white/95 px-2 py-2 backdrop-blur"><div className="mx-auto flex max-w-3xl items-center justify-between gap-1"><a href={`${BASE}/dashboard/`} className="flex min-w-0 flex-1 flex-col items-center gap-1 rounded-xl py-2 text-[10px] font-black text-slate-500"><GraduationCap size={18}/>HOME</a><a href={`${BASE}/dashboard/category/?category=${category}`} className="flex min-w-0 flex-1 flex-col items-center gap-1 rounded-xl bg-slate-100 py-2 text-[10px] font-black text-ink"><Sparkles size={18}/>PRACTICE</a><a href={`${BASE}/dashboard/history/`} className="flex min-w-0 flex-1 flex-col items-center gap-1 rounded-xl py-2 text-[10px] font-black text-slate-500"><Clock3 size={18}/>RECORDS</a><a href={`${BASE}/dashboard/personal/`} className="flex min-w-0 flex-1 flex-col items-center gap-1 rounded-xl py-2 text-[10px] font-black text-slate-500"><Target size={18}/>PERSONAL</a></div></nav>
  </main>;
}
