'use client';

import { useEffect, useState } from 'react';
import { ArrowRight, BookOpen, Bot, ChevronRight, Clock3, GraduationCap, LogOut, Menu, MessageCircle, Sparkles, UserRound, WalletCards, X, Target, Trophy, MoreHorizontal, FileText } from 'lucide-react';
import { onAuthStateChanged, signOut } from 'firebase/auth';
import { doc, getDoc, setDoc, serverTimestamp } from 'firebase/firestore';
import { auth, db } from '@/lib/firebase';
import { createPublicId } from '@/lib/publicIdentity';
import EducationFeed from '@/components/EducationFeed';

const BASE='/eduwills';
const LABELS:Record<string,string>={primary:'Primary',pupil:'Primary',pupils:'Primary','primary school':'Primary',junior:'Junior Secondary',jss:'Junior Secondary','junior secondary':'Junior Secondary',senior:'Senior Secondary',sss:'Senior Secondary','senior secondary':'Senior Secondary',book:'Book Learner','book learner':'Book Learner',books:'Book Learner'};
const label=(v:any)=>LABELS[String(v||'').trim().toLowerCase()]||String(v||'Book Learner');
function expiry(v:any){if(!v)return 0;if(typeof v.toMillis==='function')return v.toMillis();if(v.seconds)return v.seconds*1000;const n=Date.parse(String(v));return Number.isFinite(n)?n:0;}
function active(d:any){const e=expiry(d?.activationExpiresAt);return (d?.activationStatus==='active'||d?.activated===true||d?.williTokenActive===true||d?.activationActive===true||d?.isActive===true)&&(!e||e>Date.now());}

export default function DashboardPage(){
 const [name,setName]=useState('Learner'),[category,setCategory]=useState('Book Learner'),[activated,setActivated]=useState(false),[loading,setLoading]=useState(true),[more,setMore]=useState(false),[menu,setMenu]=useState(false),[locked,setLocked]=useState('');
 useEffect(()=>onAuthStateChanged(auth,async u=>{if(!u){window.location.replace(`${BASE}/login/`);return;}try{const ref=doc(db,'users',u.uid),s=await getDoc(ref),d:any=s.exists()?s.data():{};setName(String(d.fullName?.split(' ')[0]||u.displayName||d.username||'Learner'));let id=String(d.publicId||'');if(!/^EW[A-Za-z0-9]{10}$/.test(id)){id=createPublicId();await setDoc(ref,{publicId:id,publicIdVersion:1},{merge:true});try{await setDoc(doc(db,'publicUserIndex',id),{uid:u.uid,username:String(d.username||''),fullName:String(d.fullName||''),publicId:id,createdAt:serverTimestamp()},{merge:true});}catch{}}const params=new URLSearchParams(location.search);setCategory(label(params.get('category')||d.activeCategory||sessionStorage.getItem('eduwills_active_category')||localStorage.getItem('eduwills_active_category')||d.categories?.[0]||d.category));setActivated(active(d));}catch(e){console.error(e)}finally{setLoading(false)}}),[]);
 const quizHref=`${BASE}/dashboard/category/?category=${encodeURIComponent(category.toLowerCase().replace(/\s+/g,'-'))}`;
 const examHref=category==='Senior Secondary'?`${BASE}/dashboard/exam/?level=senior`:category==='Junior Secondary'?`${BASE}/dashboard/exam/?level=junior`:`${BASE}/dashboard/exam/`;
 const recordsHref=`${BASE}/dashboard/category-records/?category=${encodeURIComponent(category)}`;
 const primary=[{n:'HOME',i:GraduationCap,h:`${BASE}/dashboard/`},{n:'EXAM',i:FileText,h:examHref},{n:'QUIZ',i:Sparkles,h:quizHref},{n:'COMMUNITY',i:MessageCircle,h:`${BASE}/dashboard/community/`}];
 const open=(n:string,h:string)=>{if((n==='RECORDS'||n==='EDUWILLS AI')&&!activated){setLocked(n);setMore(false);return;}setMore(false);location.assign(h)};
 if(loading)return <main className="grid min-h-screen place-items-center bg-slate-50 text-slate-500"><Sparkles className="animate-pulse"/></main>;
 return <main className="min-h-screen bg-paper pb-28 text-ink">
  <header className="sticky top-0 z-40 border-b border-slate-200/80 bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 sm:px-8"><a href={`${BASE}/`} className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-ink text-white"><BookOpen size={20}/></span><span><b className="font-black">EDUWILLS</b><span className="ml-2 hidden text-[10px] font-black uppercase tracking-[.18em] text-slate-400 sm:inline">{category}</span></span></a><button onClick={()=>setMenu(v=>!v)} className="grid h-11 w-11 place-items-center rounded-xl border border-slate-200 bg-white shadow-sm md:hidden">{menu?<X/>:<Menu/>}</button><div className="hidden items-center gap-3 md:flex"><span className="rounded-full bg-cyan-50 px-3 py-1.5 text-xs font-black text-cyan-800">{category}</span><span className={`rounded-full px-3 py-1.5 text-xs font-black ${activated?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{activated?'Activated':'Free access'}</span></div></div>{menu&&<div className="border-t border-slate-100 bg-white p-4 md:hidden"><button onClick={()=>open('RECORDS',recordsHref)} className="flex w-full items-center justify-between rounded-xl p-3 font-black">Records <ChevronRight size={17}/></button><button onClick={()=>open('EDUWILLS AI',`${BASE}/dashboard/ai/`)} className="flex w-full items-center justify-between rounded-xl p-3 font-black">EDUWILLS AI <ChevronRight size={17}/></button><a href={`${BASE}/dashboard/personal/`} className="flex w-full items-center justify-between rounded-xl p-3 font-black">Personal <ChevronRight size={17}/></a></div>}</header>
  <div className="mx-auto max-w-7xl px-5 py-7 sm:px-8 sm:py-10"><section className="relative overflow-hidden rounded-[2rem] bg-ink p-7 text-white shadow-2xl sm:p-10 lg:p-12"><div className="pointer-events-none absolute -right-24 -top-28 h-80 w-80 rounded-full bg-cyan-400/10 blur-3xl"/><p className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-[10px] font-black uppercase tracking-[.2em] text-cyan-200"><GraduationCap size={13}/> LEARNING DASHBOARD</p><h1 className="mt-5 max-w-3xl text-3xl font-black leading-tight sm:text-5xl">Good to see you, {name}.<br/><span className="text-cyan-200">What will you learn today?</span></h1><p className="mt-5 max-w-2xl text-sm leading-7 text-slate-300">Your EDUWILLS dashboard keeps learning first. Choose your exam, practise a topic, connect with other learners or review your progress.</p><div className="mt-7 flex flex-wrap gap-3"><a href={quizHref} className="inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3.5 text-sm font-black text-ink">Start a quiz <ArrowRight size={17}/></a><a href={examHref} className="inline-flex items-center gap-2 rounded-xl border border-white/20 bg-white/10 px-5 py-3.5 text-sm font-black">Explore exams <FileText size={16}/></a></div></section>
   <section className="mt-7 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-7"><p className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-700">Your learning space</p><h2 className="mt-2 text-2xl font-black">{category}</h2><p className="mt-2 text-sm leading-6 text-slate-500">Study, practise and track progress for this category. Records are separated by learning category so the same account can have distinct learning histories.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><a href={quizHref} className="group rounded-2xl border border-slate-200 p-4 hover:border-cyan-300 hover:shadow-md"><Sparkles className="text-cyan-600" size={20}/><p className="mt-3 font-black">Practice & Quiz</p><p className="mt-1 text-xs text-slate-500">Build recall and test yourself.</p><ArrowRight className="mt-3 text-slate-300 group-hover:text-cyan-600" size={16}/></a><a href={recordsHref} className="group rounded-2xl border border-slate-200 p-4 hover:border-cyan-300 hover:shadow-md"><Trophy className="text-amber-600" size={20}/><p className="mt-3 font-black">{activated?'Category records':'Unlock records'}</p><p className="mt-1 text-xs text-slate-500">Review results for {category} only.</p><ArrowRight className="mt-3 text-slate-300 group-hover:text-cyan-600" size={16}/></a></div></div><div className="rounded-3xl border border-cyan-100 bg-cyan-50 p-6"><Target className="text-cyan-700" size={24}/><p className="mt-4 text-[10px] font-black uppercase tracking-[.18em] text-cyan-700">Community</p><h3 className="mt-1 text-xl font-black">Learn with people</h3><p className="mt-2 text-sm leading-6 text-slate-600">Search learners, discover suggested study groups and connect with school communities.</p><a href={`${BASE}/dashboard/community/`} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-ink px-4 py-3 text-xs font-black text-white">Open community <MessageCircle size={15}/></a></div></section>
   <EducationFeed />
   <section className="mt-7 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-5"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-slate-400">Access</p><h2 className="mt-1 text-xl font-black">{activated?'Your activated tools are ready.':'Free learning is available.'}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{activated?'Use your category records, EDUWILLS AI and community features.':'Keep learning within the free limits, then activate when you want broader access and protected premium tools.'}</p></div><WalletCards className={activated?'text-emerald-600':'text-amber-600'} size={25}/></div>{!activated&&<a href={`${BASE}/dashboard/activation/`} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-ink px-5 py-3 text-sm font-black text-white">Activate EDUWILLS <ArrowRight size={16}/></a>}</section>
  </div>
  <nav className="fixed bottom-0 left-0 right-0 z-50 px-3 pb-[max(8px,env(safe-area-inset-bottom))] pt-2"><div className="mx-auto flex max-w-lg items-center gap-1 rounded-[1.5rem] border border-slate-200/80 bg-white/95 p-1.5 shadow-2xl backdrop-blur">{primary.map(({n,i:Icon,h})=><a key={n} href={h} className="flex min-w-0 flex-1 flex-col items-center gap-1 rounded-2xl py-2 text-[9px] font-black text-slate-500 transition hover:bg-slate-100"><Icon size={18}/><span>{n}</span></a>)}<button onClick={()=>setMore(v=>!v)} className={`flex min-w-0 flex-1 flex-col items-center gap-1 rounded-2xl py-2 text-[9px] font-black transition ${more?'bg-ink text-white':'text-slate-500'}`}><MoreHorizontal size={18}/><span>MORE</span></button></div></nav>
  {more&&<div className="fixed inset-0 z-[60]" onClick={()=>setMore(false)}><div className="absolute inset-x-3 bottom-24 mx-auto max-w-lg" onClick={e=>e.stopPropagation()}><div className="rounded-[1.75rem] border border-slate-200 bg-white p-3 shadow-2xl"><div className="grid gap-1 sm:grid-cols-2"><button onClick={()=>open('RECORDS',recordsHref)} className="flex items-center gap-3 rounded-2xl p-4 text-left hover:bg-slate-50"><Clock3 size={19}/><span><b className="block text-sm">Records</b><small className="text-xs text-slate-400">{category} history</small></span></button><button onClick={()=>open('EDUWILLS AI',`${BASE}/dashboard/ai/`)} className="flex items-center gap-3 rounded-2xl p-4 text-left hover:bg-slate-50"><Bot size={19}/><span><b className="block text-sm">EDUWILLS AI</b><small className="text-xs text-slate-400">Academic assistant</small></span></button><a href={`${BASE}/dashboard/activation/`} className="flex items-center gap-3 rounded-2xl p-4 hover:bg-slate-50"><WalletCards size={19}/><span><b className="block text-sm">Activation</b><small className="text-xs text-slate-400">Access & payment</small></span></a><a href={`${BASE}/dashboard/personal/`} className="flex items-center gap-3 rounded-2xl p-4 hover:bg-slate-50"><UserRound size={19}/><span><b className="block text-sm">Personal</b><small className="text-xs text-slate-400">Profile & settings</small></span></a><button onClick={()=>signOut(auth).then(()=>location.replace(`${BASE}/`))} className="flex items-center gap-3 rounded-2xl p-4 text-left text-red-600 hover:bg-red-50"><LogOut size={19}/><span><b className="block text-sm">Logout</b></span></button></div></div></div></div>}
  {locked&&<div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/40 p-5 backdrop-blur-sm" onClick={()=>setLocked('')}><div className="w-full max-w-sm rounded-3xl bg-white p-7 text-center shadow-2xl" onClick={e=>e.stopPropagation()}><WalletCards className="mx-auto text-cyan-600" size={30}/><h2 className="mt-4 text-xl font-black">{locked} is activated-only</h2><p className="mt-2 text-sm leading-6 text-slate-500">Activate your EDUWILLS account to unlock this feature.</p><a href={`${BASE}/dashboard/activation/`} className="mt-5 inline-flex rounded-xl bg-ink px-5 py-3 text-sm font-black text-white">Activate now</a></div></div>}
 </main>;
}
